### ISSUE TITLE
provide feedback on cloud.gov customer listening questions

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1013]
## Background Information

cloud.gov is doing a customer listening tour; @DsaleGov asked for input on [the questions](https://docs.google.com/document/d/1MoXrVvOVZbBQzZLcqpGw3nboRU5s3ZTe0rbs4EkVtow/edit?ts=5fb7e21b).

## Acceptance Criteria

- [x] Feedback provided on questions
   - [x] @afeld 
   - [x] @JJediny

**Comment by JJediny** [comment]
@afeld good to close I think?

**Comment by afeld** [comment]
Yep! We can continue discussion in comments if they have feedback on our feedback.
