### ISSUE TITLE
gather infrastructure roadmap from each TTS team

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1020]
## Background Information

Prerequisite/parallel to https://github.com/18F/tts-tech-portfolio/issues/827. Rather than thinking top-down in terms of goals, it could be helpful to find what TTS teams are planning to do around their systems and find commonalities there.

## Implementation Steps
- [x] Create a template
- [x] Current and desired states are reflected

## Acceptance Criteria

- [x] There is a documented roadmap around infrastructure for all systems at TTS

**Comment by JJediny** [comment]
Interview with Data.gov - https://drive.google.com/file/d/1sqKjICFnhpaE1qUZDCnWLl2Ye1PSOzPF/view

**Comment by its-a-lisa-at-work** [comment]
@JJediny can you drop a link to all of the interviews you've had so far? I think that'll be good for the max.gov devs to watch since we're just starting out and will want to avoid any pitfalls.

**Comment by JJediny** [comment]
Interviews completed and requirements have been distilled into https://github.com/18F/aws-admin/tree/main/docs
