### ISSUE TITLE
decommission feedback-staging.usa.gov

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1054]
i.e. an old Touchpoints staging site. @ryanwoldatwork Feel free to add/remove items, as applicable.

_Add/remove items, as applicable._

- [ ] ~~Notify any users of the system, via banner across the site, email, Slack, etc. Ideally, help them find alternatives, make sure they're off in time, etc.~~
- [ ] ~~Export any relevant [records](https://handbook.tts.gsa.gov/records-management/) and store in Google Drive.~~
- [x] Clean up infrastructure
  - [ ] ~~cloud.gov organization deleted ([contact](https://cloud.gov/contact/))~~
  - [ ] ~~Delete any associated AWS resources, and decommission any AWS accounts. Ask in [#infrastructure](https://gsa-tts.slack.com/messages/infrastructure) for help.~~
  - [ ] ~~If the site was operated on Federalist, contact [federalist-support@gsa.gov](mailto:federalist-support@gsa.gov) to deprovision the [custom domain](https://cloud.gov/docs/management/custom-domains/) for the site~~
- [ ] ~~[Archive the GitHub repositor(ies)](https://help.github.com/articles/archiving-repositories/). Ask in [#admins-github](https://gsa-tts.slack.com/messages/admins-github) if you need help.~~
- [x] Domain changes
  - [x] Clean up any DNS entries that are no longer needed, from [the DNS repository](https://github.com/18F/dns) or elsewhere.
  - [ ] ~~If site was still in use, do one of the following:~~
    - ~~[Set up redirect(s)](https://github.com/18F/pages-redirects#domain-redirects)~~
    - ~~Point to Google Form asking about usage—see [the Fugacious page](https://fugacious.18f.gov/) ([code](https://github.com/18F/fugacious-landing)) as an example~~
  - [ ] [Delete the domain registration from DotGov](https://home.dotgov.gov/management/#how-do-i-delete-my-domain)
  - [x] Update inventories
    - [ ] [TTS subdomains](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1884617968)
    - [x] [GSA websites](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit#gid=2013137748)
- [x] Notify other parts of GSA
  - [x] Notify your ISSM
  - [ ] ~~Notify the Privacy Office ([gsa.privacyact@gsa.gov](mailto:gsa.privacyact@gsa.gov)) to take down the [privacy impact assessment (PIA)](https://www.gsa.gov/reference/gsa-privacy-program/privacy-impact-assessments-pia) and/or privacy threshold assessment (PTA)~~
- [ ] ~~Clean up integrations/usage of any [third-party software](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0) (add checkboxes below)~~
  - [ ] ~~Remove (sub)accounts~~
    - [ ] ~~New Relic - [#admins-newrelic](https://gsa-tts.slack.com/messages/admins-newrelic)~~
  - [ ] ~~Remove any external integrations~~
    - [ ] ~~[Slack](https://handbook.tts.gsa.gov/slack/#integrations)~~
  - [ ] ~~Archive the Slack channel~~
  - [ ] ~~Archive the issue tracker (Trello, etc.)~~

**Comment by afeld** [comment]
@ryanwoldatwork Just checking in to see if there's been progress on this.

**Comment by ryanwoldatwork** [comment]
No, the Helpdesk ticket still open.

**Comment by afeld** [comment]
@smileytech Are you able to help nudge?

**Comment by afeld** [comment]
Missed [the confirmation](https://gsa-tts.slack.com/archives/CCPESKPFU/p1622212341000100?thread_ts=1612915206.000500&cid=CCPESKPFU) about the DNS from @ryanwoldatwork — this is finally done!
