### ISSUE TITLE
Create a TTS Technology Governance Structure

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1057]
## Background Information

Currently, TTS manages a few different technologies (Mural, Trello, HackerOne, GitHub, etc) and there are a few others that we leverage (Smartsheet, ServiceNow, Archer) and right now each of those either have zero group management or scattered group management. 

## Implementation Steps
- [ ] Research governance structures
- [ ] Interview stakeholders

## Acceptance Criteria

- [ ]

**Comment by afeld** [comment]
I think this is covered by other issues.
