### ISSUE TITLE
Gather TTS Tech Portfolio thoughts on Transparency 

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1065]
## Background Information

generally, within the government and within TTS
## Implementation Steps
- [ ] 

## Acceptance Criteria

- [ ] 

https://docs.google.com/document/d/1hM6gmQeFM6gJfO2r2JGbFmJlsbSk0xXVk26MvgKbe5A/edit

**Comment by afeld** [comment]
@its-a-lisa-at-work Can you provide more details here, or can we close?

**Comment by its-a-lisa-at-work** [comment]
We can close; going to work with @tbaxter-18f on this
