### ISSUE TITLE
As someone decommissioning a TTS site, I want an easy way to set up redirects

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#109]
- https://before-you-ship.18f.gov/infrastructure/decommissioning/
- https://trello.com/c/vR366rg6/44-site-redirects

Currently, we are using Federalist sites with `<meta>` tags (often via [JekyllRedirectFrom](https://github.com/jekyll/jekyll-redirect-from)) to redirect TTS from sites that we take down. This leaves a lot of scattered cruft in Federalist, and isn't ideal, as those redirects come with a status code of 200 rather than 3xx.

A few ideas for how this could work:

- [Use S3](https://docs.aws.amazon.com/en_pv/AmazonS3/latest/dev/how-to-page-redirect.html)
   - Doesn't require running any servers
   - Not portable
- Deploy a little reverse proxy that does the redirects
   - cloud.gov supports the [nginx buildpack](https://docs.cloudfoundry.org/buildpacks/nginx/index.html)
   - [Equivalent example using Apache](https://bitbucket.org/usdawcmaas/static-redirector-service/src/master/docroot/.htaccess) from @ronwilliams

cc @amirbey

**Comment by afeld** [comment]
Heh, someone else had this idea already.

https://github.com/18F/pages-redirects

**Comment by adborden** [comment]
FYI, an example of doing the redirect with the static buildpack on cloud.gov https://github.com/18F/cg-dashboard/tree/master/redirects/cg-deck

**Comment by adborden** [comment]
... oh, and this https://github.com/18f/cf-redirect

**Comment by afeld** [comment]
Yep, see https://github.com/18F/pages-redirects, which is an evolution of that approach.
