### ISSUE TITLE
consider use of security.txt

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#110]
An RFC standard in https://securitytxt.org/ has been proposed to include a `security.txt` file in any sites `/.well-known/` path to provide security researchers with the information they need to properly report/communicate vulnerabilities. We should assess whether it should be required for all TTS systems:

example `security.txt`
```
# If you would like to report a security issue
Contact: https://hackerone.com/tts
Contact: devops@gsa.gov
Policy: https://github.com/18F/vulnerability-disclosure-policy/blob/master/vulnerability-disclosure-policy.md
```

**Comment by its-a-lisa** [comment]
Consolidating into 18F/tts-tech-portfolio#202

**Comment by afeld** [comment]
cc https://github.com/18F/handbook/issues/2173
