### ISSUE TITLE
Outreach + Strategic Partnerships Consulting Support for a Joint Kanban Board

### ISSUE THREAD

**Issue by rebeccamcbride** [18F/tts-tech-portfolio#1107]
## Background Information
Hello! Outreach and Strategic Partnerships would like to consolidate tracking into one framework that allows us to collaborate on initiatives and campaigns, shows updates and assignees per task, and ideally allows for analysis (either WIP or story size, etc). We'd like to get the recommendation of the TTS Tech Portflio team to make sure we're using something that fits within the larger vision for orchestrated Front Office views one day.

## Implementation Steps
- [x] Meet with Dahianna Salazar, Kristina Britt, and Rebecca McBride  ] 

## Acceptance Criteria

- [x] Tool is identified and access is granted

**Comment by melanienleopold** [comment]
Received! Thanks for coming to us on this one. We will let you know what we need from you all. Look forward to working with you on this!

**Comment by rebeccamcbride** [comment]
Thanks Melanie! Excited to work it with yall =-)

**Comment by rebeccamcbride** [comment]
Hey Team! Just wanted to check in and see if anything was needed on my end
=-) Hope you had a wonderful holiday season!

**Comment by melanienleopold** [comment]
Getting to this today! I will likely put some time on the calendar for next week to discuss.

**Comment by rebeccamcbride** [comment]
Hey Melanie! Just circling back again and adding Kristina and Dahianna -
I'm guessing we're looking at next week now. It's a bit wonky on my end so
wanted to loop K & D in on the thread. Hope we can meet on this soon so we
can all get in a tool!

Rebecca

**Comment by melanienleopold** [comment]
Sorry for the delay, it's been very busy around here! I will see if I can find some time Thursday or Friday this week.

**Comment by melanienleopold** [comment]
Meeting with Outreach set for 1/25 to go over options.

**Comment by rebeccamcbride** [comment]
Thank you - I don't see the invite though and would love to join!

**Comment by melanienleopold** [comment]
Using as an example for new software concierge process.

**Comment by melanienleopold** [comment]
Spoke to Alyssa, and she said TTS is looking for Dave Z to make a call that SmartSheet will be the project management tool.

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/1213

**Comment by melanienleopold** [comment]
Gave @rebeccamcbride the information on how to get access to GSA IT Jira.

**Comment by afeld** [comment]
Just talked with Kristina; sounds like Outreach is going with a separate board/tool than Strategic Partnerships. She thinks that a paid Trello (https://github.com/18F/tts-tech-portfolio/issues/1176) may meet their needs.
