### ISSUE TITLE
update team onboarding documentation

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#111]
https://docs.google.com/document/d/1kF41y1AbVCkdXE5XStuthOM-1VIA48UimN9W3E9Jk68/edit

- [x] Turn onboarding documentation into a checklist

- [x] Validate checklist with 3 onboarders and 3 offboarders

**Comment by its-a-lisa** [comment]
I created a [spreadsheet](https://docs.google.com/spreadsheets/d/1wJv3hJ3tRUo-e14y3Mw3_l3XQ9HDA7ZTIpWG3s6Be00/edit?usp=sharing) from the word document to match the TTS onboarding spreadsheet for better consistency.
