### ISSUE TITLE
Ongoing Security Authorization Costs

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1112]
## Background Information

Breakout from https://github.com/18F/tts-tech-portfolio/issues/1084

## Implementation Steps
- [ ] 

## Acceptance Criteria

- [ ] Able to articulate what the security sustainment cost of a simple cloud.gov app is

**Comment by JJediny** [comment]
closing in favor of https://github.com/18F/tts-tech-portfolio/issues/1260
