### ISSUE TITLE
review Request Tracker submission for Google Cloud AutoML

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1131]
https://gsa.lightning.force.com/lightning/r/Request_Tracker__c/a1Zt0000000fysqEAA/view

## Implementation status

- [x] Ensure the [Google services spreadsheet](https://docs.google.com/spreadsheets/d/1h0338doPlHIfslS7Huypzs7TlJTFVw_-98oPnum0Cvo/edit#gid=467863101) reflects the current state

## Acceptance criteria

- [x] Issues created for any action items

**Comment by its-a-lisa-at-work** [comment]
[Salesforce request](https://gsa.lightning.force.com/lightning/r/Request_Tracker__c/a1Zt0000000oPzYEAU/view) was just `Approved`.

**Comment by melanienleopold** [comment]
[Salesforce request](https://gsa.lightning.force.com/lightning/r/Request_Tracker__c/a1Zt0000000fysqEAA/view) is being canceled. The requestor has what they need.
