### ISSUE TITLE
put forth proposal for a Solutions Engineering conference

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1145]
## Background Information

[The idea](https://docs.google.com/document/d/1jm5mDHeZQtwulXVtldBU8te7WyeH_MKwNTgoXvGGM7U/edit#bookmark=id.7sg5reg64x3r) came up in a Engineering @ Solutions meeting. "Conference" meaning a day or two of talks/workshops.

## Implementation Steps
- [ ] Write a one-pager with a proposal for the format, loose agenda, etc.

## Acceptance Criteria

- [ ] 👍 from the Solutions leads

**Comment by JJediny** [comment]
Closing will reopen if an ask or need re-surfaces for this
