### ISSUE TITLE
Common Control Activity: System Architecture

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1150]
## Background Information

Me and @JJediny were talking about https://github.com/18F/aws-admin/issues/114 which led to reviewing the [list of AWS Accounts](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0) and taking a closer look at which systems would benefit from the common control platform. 

This was one of the first times I really looked at the list with a fresh set of eyes and had asked whether or not there was a system architecture/diagram that described what is common to these infrastructures/ what is common to them. 

## Implementation Steps
- [ ] Create a system architecture

## Acceptance Criteria

- [ ] TBD

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/aws-admin/issues/131.
