### ISSUE TITLE
understand the Federalist boundary

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1163]
As I'm trying to do https://github.com/18F/bug-bounty/issues/34 and https://github.com/18F/tts-tech-portfolio/issues/784 I am trying to make sure all of the Federalists websites are identified. Because I believe that if they are not, they should be added to the [TTS System Assessment Schedule](https://docs.google.com/spreadsheets/d/19wyA91KhGoZvnAA0fihC0WF_mU79YLRTHzDd-Frs8Qs/edit#gid=0) and treated as individual systems

**Comment by its-a-lisa-at-work** [comment]
I got started to work out my understanding of where the boundaries could lie in a [boundary diagram](https://docs.google.com/presentation/d/1W1E_cuAPSS7e3eCgwVws4kS0Sp2VQzE84V01xYjSS7o/edit)

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/1165

**Comment by its-a-lisa-at-work** [comment]
Ideally, all of the TTS systems that are created under the TTS boundary have some common baseline so that the security tasks are minimal.
