### ISSUE TITLE
correlate system information to support system authorizations

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1164]
Right now, we are tracking TTS System Assessments in a [schedule](https://docs.google.com/spreadsheets/d/19wyA91KhGoZvnAA0fihC0WF_mU79YLRTHzDd-Frs8Qs/edit#gid=0). We want to make sure we are planning the assessments as far in advance as possible. 
- We are in the process of making sure all of the systems are added to the bug bounty program. These are listed based on their website urls. 
- We are also in the process of adding systems to the software assurance tool.  These are listed based on their GitHub repos. 

So, in order to make sure that we have a system covered for software assurance, we need to know all of the urls and GitHub repos associated with a system.

**Comment by afeld** [comment]
Thoughts on closing in favor of https://github.com/18F/tts-tech-portfolio/issues/1179?

**Comment by its-a-lisa-at-work** [comment]
sounds good to me
