### ISSUE TITLE
Stay under Mural license limit

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1168]
## Background information

Mural licenses are capped at 230. We cannot be over that number of users or we will antideficient and not have funds to pay for them. There are a lot of TTS members who continue to ask for access to Mural. When the next option period is exercised we will have 10 more licenses available for a total of 240. We need to determine how to keep licenses under the 240 cap.

Some options are:
- Limit who is allowed to have a Mural license
- Add another CLIN to the contract

## Acceptance criteria

- [ ] Documented process in the Handbook for OpsRotation to keep us under the Mural license limit on an ongoing basis

**Comment by melanienleopold** [comment]
Here's a [quick writeup](https://docs.google.com/document/d/1pNrrIYNowJYjW4owinOFDIu73sgyXYyKIiaFM5dqLpM/edit#). I put 60 days, but not sure what Ops Rotation has been using as the Benchmark. It might be good to put this in the Mural Handbook page. I can do that if you all agree.

**Comment by afeld** [comment]
Let's start with 90 days. Otherwise, looks good! Game to add to the Handbook?

**Comment by melanienleopold** [comment]
@JJediny would you mind giving this a quick review?
