### ISSUE TITLE
FormService - architecture review

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1182]
## Implementation Steps
- [ ] @its-a-lisa-at-work Get list of options
- [ ] Review architecture

## Acceptance Criteria

- [ ] Comments have been provided to the FormService team on what portions of the architecture need to be updated

**Comment by afeld** [comment]
@JJediny will document / link to our feedback and create specific follow-up issues, but this is otherwise done.

**Comment by its-a-lisa-at-work** [comment]
Provided assess to the devops@gsa.gov team to view the [document](https://docs.google.com/presentation/d/1QN1OKLAgWE-ZXPMNY9d698dyyeYHF3LqYLt_35M4Q80/edit?ts=60185346#slide=id.p16) put together related to the architecture; let me know if you have any other questions; taking my name off now :)

**Comment by saz33m** [comment]
Having an architecture review next week with CISO will include you @JJediny

**Comment by afeld** [comment]
Considering this done from the Tech Portfolio's perspective.
