### ISSUE TITLE
offboard Amit

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1183]
Assignee: The tasks below are organized by the role needed to complete them. If you canʼt complete
any of the items on your checklist personally, you are responsible for ensuring that an appropriate person
does it.
For compliance tracking purposes we need to show when offboarding actions happened; many need to
occur in a 24-hour window. As you do this work, comment on this GitHub issue as you complete each
task. (PS-4: Personnel termination)

## Assignee

Remove them from:

- [x] Ops Rotation, fixing the schedule
- [x] Google Groups
  - [x] [TTS Software](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-software/add)
  - [x] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add)
  - [x] [TTS Vulnerability Reports](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)
- [x] [The employee list in SmartSheet](https://app.smartsheet.com/sheets/Q2CgG9V897x8rRmv8XhGGjrhFRxVVqgVx5hCmW41?view=grid)
- [x] [The Everyone issue template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/everyone.md)

**Comment by JJediny** [comment]
Cannot remove some smartsheet but confirmed all groups and accounts removed

**Comment by afeld** [comment]
Offboarding will be the reverse of the following from the onboarding checklist:

### Required items for all team members

Add them to:

- [ ] [The @tech-portfolio user group in Slack](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group)
- [ ] [The @18F/tts-tech-portfolio team in GitHub](https://github.com/orgs/18F/teams/tts-tech-portfolio/members)
- [ ] [The Everyone issue template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/everyone.md)
- [ ] The OpsRotation schedule
- [ ] [The TTS Tech Portfolio Roles](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/roles.md)
- [ ] [The employee list in SmartSheet](https://app.smartsheet.com/sheets/Q2CgG9V897x8rRmv8XhGGjrhFRxVVqgVx5hCmW41?view=grid)

### Google Groups

- [ ] [TTS Software](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-software/add)
- [ ] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add)
- [ ] [TTS Vulnerability Reports](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)

### Account Access

Add as an admin to:

- [ ] AWS, via [cross-account access](https://github.com/18F/aws-admin#cross-account-access)
- [ ] [DockerHub](https://hub.docker.com/orgs/18fgsa)
- [ ] [18F GitHub org](https://github.com/orgs/18F/people)
- [ ] HackerOne
  - [ ] [Public team](https://hackerone.com/tts/team_members)
  - [ ] [Private team](https://hackerone.com/tts-private/team_members)
- [ ] [InVision](https://gsa.invisionapp.com/d/main?origin=v7#/company/members)
- [ ] [Mural](https://app.mural.co/t/gsa6/settings/members)
- [ ] [New Relic](https://account.newrelic.com/accounts/562946/users)
- [ ] [NPM](https://www.npmjs.com/settings/18f/members)
- [ ] [Slack](https://handbook.tts.gsa.gov/tools/slack/user-management/#offboarding)

**Comment by afeld** [comment]
Done!
