### ISSUE TITLE
EPIC: Workflow tooling

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#119]
We have a number of use cases for workflows within TTS:

- FITARA tracking
- Job applicants
- IaaS invoice approvals
- Event approvals
- IAAs
- Purchases
- Software requests
- Offboarding

which is done in a number of tools:

- Trello
- Email
- Slack channels
- Google Forms
- Google Sheets (sometimes with Google Scripts)

All of these are, frankly, sub-par for this purpose. Business Process Management tools are a solved problem, so we should look at various tools that are available within GSA and see if there's one that would meet our needs that we can migrate to. Known options:

- C2 (reviving it from the dead)
- Acitiviti
- ServiceNow
- SalesForce
- [Slack workflows](https://slack.com/features/workflow-automation)

Such a tool would need to handle:

- Intake (a form)
- Notifications
- Reminders
- Approvals
- Routing
- Tracking across requests
- Reporting
- Programmatic access (an API)

cc @ethanheppner

**Comment by JJediny** [comment]
http://bpmn.io/ Open Source Components for the enterprise version at https://camunda.com/ has been previously considered. BPMN solutions tend to be based on complex legacy XML specs/schemas that make it harder to understand by anyone without domain knowledge of the sometimes obscure concepts in them. 

Risk is that if we pick a common solution for workflow we could be restricting feedback/flexibility in the modeling/wireframe phase of the discovery work needed.

**Comment by ethanheppner** [comment]
I've heard recommendations of Camunda and Activiti before (I'm wondering,
did Bret mention this to you now that he's back :)? It's on my radar, but
it's going to take some time to thoughtfully look into whether this is the
right solution for us (ensuring there is enough feedback and flexibility as
John mentioned). There's a tension between solving the more immediate
process issues (getting off unsupported C2, reducing the heavy amount of
data entry work that goes into hiring action, etc.) and thinking longer
term about these sorts of tools which could support us across many
different functions. Let's discuss more to figure out how we appropriately
prioritize and get started this.

Ethan Heppner
Program Analyst, TTS Business Operations
https://gsa.gov/tts

**Comment by mogul** [comment]
I am just seeing this thread, so no, but you correctly pinned me as having an opinion.

Camunda is the modern, well-supported and better all-around fork of Activiti. See [the thread in Slack](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1553631273125900?thread_ts=1553623096.106100&cid=C02CD5VUQ) where I wouldn't shut up about this.

**Comment by afeld** [comment]
[Asked in Chatter](https://gsa.lightning.force.com/lightning/r/0D5t000001RR9evCAD/view) what it takes to get permissions to make Templates in DocuSign, since it came up for something else.

**Comment by JJediny** [comment]
Closing in favor of epic https://github.com/18F/tts-tech-portfolio/issues/207
