### ISSUE TITLE
Smartsheet - Tool familiarity

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1195]
## Background Information

It got brought up at the Dave Shive AMA that folks would appreciate increased information to get familiar with the tool that is lead by someone internal to TTS. 

## Implementation Steps
- [ ] Better understand the problem that needs to be solved

## Acceptance Criteria

- [ ]

**Comment by afeld** [comment]
cc https://github.com/18F/handbook/issues/2269

**Comment by afeld** [comment]
Closing as stale.
