### ISSUE TITLE
Zendesk LISaaS extension request - due 2/9

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1220]
cc #978

**Comment by melanienleopold** [comment]
[Write up](https://docs.google.com/document/d/1rFiI4dcqvUC3REFEcdGREnl8LtFZ-Bk0tm123lGLlxs/edit#) for ATO extension.

**Comment by afeld** [comment]
Suggested some small edits. Thanks!

**Comment by melanienleopold** [comment]
@afeld am I good to send it on to security?

**Comment by afeld** [comment]
Yep! Email Nate Ciano and just remind him that you're reaching out on behalf of the Tech Portfolio. Thanks!

**Comment by melanienleopold** [comment]
Email sent to Nate 2/11.
