### ISSUE TITLE
Bug Bounty Transfer to GSA IT Security - due 9/1/21

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1224]
## Background information

Follow up from https://github.com/18F/bug-bounty/issues/41 

~~Was informed that there isn't any extra money now and that the timeline is somewhere around FY22 for TTS programs to transfer over.~~

## Implementation step

- [x] Consensus around whether to retain the TTS Bug Bounty in name
- [x] Maintain records
- [x] Determine how migration would happen
- [x] Determine pricing and funding mechanism(s)
- [x] Funding transferred
- [x] Create issue around close-out of old program - see emails `H1 | TTS Program Closure Process` and `H1| GSA + TTS Program Transition Plan`
   - [x] Notify TTS participants
- [x] Create issue around updating documentation
   - [x] [Vulnerability Disclosure Policy](https://18f.gsa.gov/vulnerability-disclosure-policy/)
   - [x] [Public program page](https://hackerone.com/tts)
   - [x] [Private program page](https://hackerone.com/tts-private)

## Acceptance criteria

- [x] GSA Security responsible for managing Bug Bounty of TTS' assets

**Comment by afeld** [comment]
Set soft due date for initiating this so we have enough lead time.

**Comment by afeld** [comment]
Emailed Security with the ask.

**Comment by afeld** [comment]
Waiting on pricing model from Security.

**Comment by afeld** [comment]
[Meeting notes](https://docs.google.com/document/d/193q-UTMCCDIPdYnK3ugnoPhfBVSF7YzzDegaJB8JIEg/edit)

**Comment by afeld** [comment]
Emailed to confirm next steps.

**Comment by afeld** [comment]
Gave @KMcGov-GSA access to the TTS Bug Bounty accounts. He confirmed that next steps are on him to work on a consolidation plan.

**Comment by adborden** [comment]
@JJediny will update the issue about getting TTS folks access to the GSA program.
