### ISSUE TITLE
Create recap document from the TTS Tech Portfolio All Hands

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#123]
As a new team, we came together #82  and worked on stuff like  #80  and 18F/handbook#1300

- [x] review [agenda](https://docs.google.com/spreadsheets/d/1QIJSNjEK_ATJT72YZic2Ma3JLQDZ3FCcl7vWUAPKPPs/edit#gid=0)
- [x] review [notes](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#heading=h.klwwh4ewy228)
- [x] capture TODOs
- [x] Present at [retro](https://calendar.google.com/calendar/r/eventedit/N29ya2ZybXFiaXRqbGR0OWg1Ymg1djM2aGhfMjAxOTEwMTFUMTMzMDAwWiBhbHlzc2EuZmVvbGFAZ3NhLmdvdg)

**Comment by afeld** [comment]
"capture TODOs" is about taking action items and moving them into issues, yes?

**Comment by its-a-lisa** [comment]
I hadn't thought that far ahead -- I'm not exactly sure -- do you want an issue for cancelling the one on one meetings? Should we have an issue for moving the slackbots? Those to me seem like small enough tasks that just need to be captured on a list rather than having issues created around them. But it goes back to 'this is all still a little fuzzy'.

**Comment by afeld** [comment]
I would rather we err on too many issues (or checklist items in a larger issue) than too few. Closing them out is satisfying, anyway 😉 

For something like moving the Slackbot, that could be a task in a (slightly) larger issue around "distinguish Slack channels for internal/external coordination" or something like that.
