### ISSUE TITLE
offboard Alyssa

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1233]
Assignee: The tasks below are organized by the role needed to complete them. If you canʼt complete
any of the items on your checklist personally, you are responsible for ensuring that an appropriate person
does it.
For compliance tracking purposes we need to show when offboarding actions happened; many need to
occur in a 24-hour window. As you do this work, comment on this GitHub issue as you complete each
task. (PS-4: Personnel termination)

## Departing Person

- [ ] [Initiate the process](https://handbook.tts.gsa.gov/leaving-tts/)

## Assignee

Remove them from:

- [ ] Google Groups
  - [ ] [TTS Software](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-software/add)
  - [ ] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add)
  - [ ] [TTS Vulnerability Reports](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)
- [ ] [The employee list in SmartSheet](https://app.smartsheet.com/sheets/Q2CgG9V897x8rRmv8XhGGjrhFRxVVqgVx5hCmW41?view=grid)
- [ ] [The Everyone issue template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/everyone.md)

**Comment by JJediny** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/1245
