### ISSUE TITLE
revise engineering org structures overview with initial feedback - due 2/16

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1239]
## Background Information

Follow-up to https://github.com/18F/tts-tech-portfolio/issues/1050. Presented to a few folks in TTS Solutions; want to incorporate their feedback

## Implementation Steps
- [ ] Go through [notes](https://docs.google.com/document/d/10c67oU37KAi_hhg10zWkcp-5TWqLXvEJL-0iR8nuIn0/edit#heading=h.bd7icdsjffvm)
- [ ] Edit [slides](https://docs.google.com/presentation/d/1aNpduPDUVgoPY7X12cBbCUuDvw5QZ52nXedwUMIzzDE/edit#slide=id.p)

## Acceptance Criteria

- [ ] Feedback incorporated

**Comment by its-a-lisa-at-work** [comment]
@afeld mind sharing for review? I am plan on suggesting a better Cybersecurity support structure w/in TTS, so want to make sure it is alignment with the eng org structure where possible
