### ISSUE TITLE
offboard @its-a-lisa-at-work

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1245]
Assignee: The tasks below are organized by the role needed to complete them. If you canʼt complete
any of the items on your checklist personally, you are responsible for ensuring that an appropriate person
does it.
For compliance tracking purposes we need to show when offboarding actions happened; many need to
occur in a 24-hour window. As you do this work, comment on this GitHub issue as you complete each
task. (PS-4: Personnel termination)

## Departing Person

- [x] [Initiate the process](https://handbook.tts.gsa.gov/leaving-tts/)

## Assignee

Remove them from:

- [x] Google Groups
  - [x] [TTS Software](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-software/add)
  - [x] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add)
  - [x] [TTS Vulnerability Reports](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)
- [ ] [The employee list in SmartSheet](https://app.smartsheet.com/sheets/Q2CgG9V897x8rRmv8XhGGjrhFRxVVqgVx5hCmW41?view=grid)
- [x] [The Everyone issue template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/everyone.md)

**Comment by its-a-lisa-at-work** [comment]
Would also include
- [ ] cancel any reoccurring meetings Alyssa set up and send them out by someone else

**Comment by afeld** [comment]
> cancel any reoccurring meetings Alyssa set up and send them out by someone else

Have any in mind? I _think_ them being on the team calendar makes the ownership essentially shared.

**Comment by its-a-lisa-at-work** [comment]
Ok, maybe I just need to be offboarded from the team calendar?

Its less about them being shared, and more about me 1) being off of them
and 2) someone else being able to control them.

That way I don't get notifications any longer, they don't show up on my
calendar and folks don't need me to move them.

The specific ones I had in mind were the co-working sessions, OpsRotation
and monthly All Hands

**Comment by afeld** [comment]
Just to confirm:

- Do you still see Tech Portfolio events on your calendar?
- Are you still getting notifications for any Tech Portfolio meetings?

If yes to either, you can try [transferring any remaining ownership](https://support.google.com/calendar/answer/78739?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Ctransfer-an-event-to-a-calendar-you-dont-own) to me. I don't think I've run into any issues editing Tech Portfolio meetings, so all good there.

**Comment by JJediny** [comment]
@afeld confirmed account removal from all team groups. Cannot edit smartsheet and I see your still waiting to address meeting ownership.

**Comment by its-a-lisa-at-work** [comment]
OK, not seeing anything on my calendar anytmore. 

@JJediny do I need to do anything with smartsheet?

**Comment by afeld** [comment]
> do I need to do anything with smartsheet?

I don't think so. Thanks though!

---

Offboarding will be the reverse of the following from the onboarding checklist:

### Required items for all team members

Add them to:

- [ ] [The @tech-portfolio user group in Slack](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group)
- [ ] [The @18F/tts-tech-portfolio team in GitHub](https://github.com/orgs/18F/teams/tts-tech-portfolio/members)
- [ ] [The Everyone issue template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/everyone.md)
- [ ] The OpsRotation schedule
- [ ] [The TTS Tech Portfolio Roles](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/roles.md)
- [ ] [The employee list in SmartSheet](https://app.smartsheet.com/sheets/Q2CgG9V897x8rRmv8XhGGjrhFRxVVqgVx5hCmW41?view=grid)

### Google Groups

- [ ] [TTS Software](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-software/add)
- [ ] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add)
- [ ] [TTS Vulnerability Reports](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)

### Account Access

Add as an admin to:

- [ ] AWS, via [cross-account access](https://github.com/18F/aws-admin#cross-account-access)
- [ ] [DockerHub](https://hub.docker.com/orgs/18fgsa)
- [ ] [18F GitHub org](https://github.com/orgs/18F/people)
- [ ] HackerOne
  - [ ] [Public team](https://hackerone.com/tts/team_members)
  - [ ] [Private team](https://hackerone.com/tts-private/team_members)
- [ ] [InVision](https://gsa.invisionapp.com/d/main?origin=v7#/company/members)
- [ ] [Mural](https://app.mural.co/t/gsa6/settings/members)
- [ ] [New Relic](https://account.newrelic.com/accounts/562946/users)
- [ ] [NPM](https://www.npmjs.com/settings/18f/members)
- [ ] [Slack](https://handbook.tts.gsa.gov/tools/slack/user-management/#offboarding)

**Comment by afeld** [comment]
Wasn't able to downgrade in DockerHub due to https://github.com/18F/tts-tech-portfolio/issues/983#issuecomment-809516800, but otherwise complete.
