### ISSUE TITLE
Complete the purchase of FY21 domain renewals - due 3/18

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1255]
## Implementation

- [x] Submit purchase requests
- [ ] Notify [System Owners on the need for Micropurchase Requests](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=824448842)

## Acceptance Criteria
- [ ] DNS Records due in FY21 are renewed

**Comment by afeld** [comment]
No longer necessary, apparently!

https://twitter.com/CISAgov/status/1387117104390971397

**Comment by afeld** [comment]
Reopening, pending confirmation there’s nothing to be done.

**Comment by saracope** [comment]
In the system, I don't actually see how to request a renewal for the domain. Do you? Will they auto-renew? I'm not finding any good info on the site. @afeld

**Comment by afeld** [comment]
No idea!

**Comment by afeld** [comment]
Waiting on response from DotGov support.

**Comment by afeld** [comment]
We confirmed that .gov domain renewals (in terms of $$) are no longer a thing, so this is no longer necessary.
