### ISSUE TITLE
Transition COR role for Hackerone

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1256]
## Implementation 

- [x] @jjediny to Provide CO with COR certification
- [x] CO notifies and changes COR on file 

## Acceptance
- All official roles and duties have been transitioned to @jjediny for the Hackerone Contract

**Comment by afeld** [comment]
I believe the plan is for this to coincide with https://github.com/18F/tts-tech-portfolio/issues/1185.

**Comment by afeld** [comment]
Signed.
