### ISSUE TITLE
Assist OCP initiative with issuing TLS certs for their top level domains

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1267]
## Implementation
- [ ] advise on ways to acquire/apply TLS certs
   - [ ] GSA issued/purchased *wildcard cert for each 3 CSP domains
   - [ ] Setup LetsEncrypt with TTS DNS delegation

## Acceptance Criteria 
- [ ] OCP effort has TLS configured for their domains
- [ ] Lessons learned are documented

**Comment by afeld** [comment]
Complete.
