### ISSUE TITLE
SaaS budget projection for FY21 - due 3/10

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1280]
## Background Information

Splitting out from https://github.com/18F/tts-tech-portfolio/issues/944#issuecomment-789340457:

> If we continued SaaS purchases as current levels (just renewals, without buying anything new), how much would we have left over at the end of FY21?

## Implementation Steps
- [ ] 

## Acceptance Criteria

- [x] A prediction of the budget remainder

**Comment by JJediny** [comment]
https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=694889283
