### ISSUE TITLE
update the SaaS inventory

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#129]
https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0

Particularly the "person in charge of licensing."

**Comment by JJediny** [comment]
done/WIP no need to track as an item https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0
