### ISSUE TITLE
SaaS Request Textio

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1299]
## Background information

The TTS Talent team would like to use Textio. It is an augmented writing platform aimed at creating more inclusive and persuasive job postings, candidate outreach and employer branding. We will use this technology to improve our job postings, website content and email outreach to candidates.

## Implementation Steps
- [ ] Set up meeting with Talent to conduct software concierge interview

## Acceptance Criteria
- [ ] Confirm what solution we want to pursue for an augmented writing platform

**Comment by afeld** [comment]
[Responses to intake questions](https://docs.google.com/document/d/1ptPoVd85ckNmImmUGx6Xe0Ym-1FUN-9W83hgehPkypU/edit#)
