### ISSUE TITLE
catch up on AWS Sandbox requests - due 7/18

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#13]
- https://docs.google.com/forms/d/1bacCvH8dyu9iIEfCMbTIP4uyyUeveLtOH76DSSoCO3k/edit#responses
- https://before-you-ship.18f.gov/infrastructure/sandbox/#aws-sandbox-accounts

**Comment by JJediny** [comment]
It looks like the previous form was setup by a former TTS member and the response sheet is no longer available to review. 

I propose we either:
- [ ] create a new google form
- [ ] create an issue template for requesting a sandbox account in 18f/Infrastructure.

**Comment by afeld** [comment]
If you have the URL, we could potentially ask GSA IT for access to the Google Sheet, but either of the others are fine too.

**Comment by afeld** [comment]
Account is 001907687576 (AWS-GSA-18F-Sandbox).

**Comment by afeld** [comment]
Done, with [a spreadsheet to track which are done](https://docs.google.com/spreadsheets/d/1aa6s1K3AtrorvD0KewKqdneTm-PsF0KKiy95jwfThk8/edit#gid=1066095098). We can revisit if we want to take these requests a different way later.
