### ISSUE TITLE
Resolve New Relic SSO mis-configuration

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1316]
New Relic SSO using GSA Secure Auth isn't working off (and now while on GSA Network)

## Implementation
- [x] Discovery on root cause
- [ ] Get a solve by date
- [ ] Determine if we need to temporarily disable until a fix is patched

## Acceptance Criteria
- [ ] New Relic is accessible on and off GSA network

**Comment by JJediny** [comment]
Closing until we can update progress, current status https://gsa-tts.slack.com/archives/C14EF2XEC/p1620144603008300

**Comment by afeld** [comment]
Issue around documenting the current state: https://github.com/18F/before-you-ship/issues/512
