### ISSUE TITLE
Hand off management of Agari from login.gov to Tech Portfolio

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#133]
Placeholder:
https://docs.google.com/document/d/1wIBWsPQOf19wiL88V8keJwcwCKu9B5QEpE7JOxpsMY0/edit?ts=5da8d961#

**Comment by afeld** [comment]
@brodygov Let us know how you'd like us to proceed here, assuming we heard correctly that you do!

**Comment by brodygov** [comment]
I sent account invitations a while back to folks, not sure if anyone has had a chance to log in yet.

**Comment by afeld** [comment]
I did, thanks! Have not done anything beyond that.

**Comment by JJediny** [comment]
If DMARC/SPF tracing needs across TTS programs comes up we'll create a new issue to inactionable at this point.
