### ISSUE TITLE
decommission infrastructure org in cloud.gov - due 5/27

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1336]
## Background Information

There's a [`gsa-tts-infrastructure`](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/fab37005-7506-463d-8d07-ede6aa693bf0/spaces) org in cloud.gov that has existed for a while but shouldn't have any running apps and [doesn't have an active agreement](https://gsa-tts.slack.com/archives/C0DF6LAMQ/p1620221369009400), so should be a shut down.

## Implementation Steps
- [x] Decommission CodiMD - #968 
- [x] Notify cloud.gov it's ready to be deleted

## Acceptance Criteria

- [x] Organization deleted

**Comment by afeld** [comment]
<img width="1764" alt="Screen Shot 2021-05-05 at 6 34 00 PM" src="https://user-images.githubusercontent.com/86842/117218075-7d2f8080-add0-11eb-947f-2bb466ec4a1c.png">

**Comment by JJediny** [comment]
Org has been cleaned out @kelleyconfer the organization can be safely deleted cc @afeld 
<img width="1087" alt="Screen Shot 2021-05-24 at 2 18 07 PM" src="https://user-images.githubusercontent.com/6350035/119390535-2d3f2d80-bc9b-11eb-9309-845679371ffd.png">

**Comment by afeld** [comment]
[Deleted.](https://gsa-tts.slack.com/archives/C0DF6LAMQ/p1621904953007800)
