### ISSUE TITLE
Onboard Fellow - due 6/7

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1347]
**NewPerson and Buddy:** Try to go through your checklists in order.

**Buddy:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that someone with the correct access completes that item_.

### Getting to know TTS Tech Portfolio

- [ ] Read [the Tech Portfolio Handbook page](https://handbook.tts.gsa.gov/tech-portfolio/) and things linked from there
- [ ] Read [the team onboarding document](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/onboarding.md) for more context about TTS Tech Portfolio.
- [ ] Read the [TTS Tech Portfolio Handbook page](https://handbook.tts.gsa.gov/tech-portfolio/) for an overview of what we do
- [ ] Read the [Workflow document](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/workflow.md) to learn about how we work.
- [ ] Submit a pull request to make the Tech Portfolio's onboarding documentation/checklist better.

### Required items for all team members

Ensure you know what's happening on the team:

- [ ] Subscribe to the [Tech Portfolio team calendar](https://calendar.google.com/calendar?cid=Z3NhLmdvdl82aDI5YnF1ZGx0NGVoZTVzOWswOGlmdGZxMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) (click the + in the bottom right) so you know when assorted team meetings are happening. Tip: When you plan Out of Office time, make a calendar event for that on the TTS Tech Portfolio calendar so that your teammates know you'll be away.
- [ ] [Watch](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions#configuring-your-watch-settings-for-an-individual-repository) [our repositories](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/github.md)

Learn our policies and procedures:

- [ ] Coordinate with your onboarding buddy to go through [Incident Response Training](https://docs.google.com/presentation/d/1AZjQE8zBzMRWZIFUuJPkJLted1ykGtALrLPoPRx5Vls/edit#slide=id.p) within 60 days of joining the team (and annually after that). This will cover the following document, which you should also review before or after training:
- [ ] Read [Before You Ship](https://before-you-ship.18f.gov/)
- [ ] Coordinate with your onboarding buddy to go through [nonpublic information training](https://docs.google.com/presentation/d/1rXSZZ0t0kadsoP1EMJoM0T7ROkGD3Pr5wojWnf2GksI/edit#slide=id.g1a2cf8d6b3_0_273) within 60 days of joining the team (and annually after that). This will cover the following documents, which you should also review before or after training:
- [ ] Review the [18F open source policy guidance about protecting sensitive information](https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information)
  - [ ] Review the [TTS requirements for password management](https://handbook.tts.gsa.gov/password-requirements/)

Learn about what we do:

- [ ] [DNS](https://github.com/18F/dns)
- [ ] [How to create GitHub issues in our board](https://docs.google.com/presentation/d/1q8aCGgzBfP9B8yJrMHfavTwAYPupgdT94ktGPsHzjVU/edit)

## Buddy checklist

- [ ] Introduce yourself to the new team member and give them some of your background so they know who you are; if you are comfortable, share your Readme and encourage them to create their own
- [ ] Identify a straightforward, well-groomed story in progress that involves their skills domain, schedule a meeting with the owner for an introduction (if it's not you), and setup pairing sessions several times in the first week on the project.
- [ ] Have the person shadow whomever is on [OpsRotation](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/ops_rotation.md), so they can see how we handle support and read with those within TTS.

### Required items for all team members

Add them to:

- [ ] [The @tech-portfolio user group in Slack](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group)
- [ ] [The @18F/tts-tech-portfolio team in GitHub](https://github.com/orgs/18F/teams/tts-tech-portfolio/members)
- [ ] [The Everyone issue template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/everyone.md)
- [ ] The OpsRotation schedule
- [ ] [The TTS Tech Portfolio Roles](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/roles.md)
- [ ] [The employee list in SmartSheet](https://app.smartsheet.com/sheets/Q2CgG9V897x8rRmv8XhGGjrhFRxVVqgVx5hCmW41?view=grid)

### Google Groups

- [ ] [TTS Software](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-software/add)
- [ ] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add)
- [ ] [TTS Vulnerability Reports](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)

### Account Access

Add as an admin to:

- [ ] AWS, via [cross-account access](https://github.com/18F/aws-admin#cross-account-access)
- [ ] [DockerHub](https://hub.docker.com/orgs/18fgsa)
- [ ] [`TTS-managed` GitHub orgs](https://handbook.tts.gsa.gov/github/#organizations)
- [ ] HackerOne
  - [ ] [Public team](https://hackerone.com/tts/team_members)
  - [ ] [Private team](https://hackerone.com/tts-private/team_members)
- [ ] [InVision](https://gsa.invisionapp.com/d/main?origin=v7#/company/members)
- [ ] [Mural](https://app.mural.co/t/gsa6/settings/members)
- [ ] [New Relic](https://account.newrelic.com/accounts/562946/users)
- [ ] [NPM](https://www.npmjs.com/settings/18f/members)
- [ ] [Slack](https://handbook.tts.gsa.gov/tools/slack/user-management/#offboarding)

**Comment by adborden** [comment]
Updated template from https://github.com/18F/tts-tech-portfolio/pull/1354

**Comment by afeld** [comment]
[Spreadsheet checklist for general onboarding](https://docs.google.com/spreadsheets/d/1xmW2yBjw_xjebFslxVw1azwr8U3o75qbof30zD7Suh8/edit#gid=0)

**Comment by afeld** [comment]
Lots of these tasks won't be applicable. Added some they will need to the spreadsheet checklist, so closing this.
