### ISSUE TITLE
fix Terraform CI error

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1365]
## Background Information

From [build log](https://app.circleci.com/pipelines/github/18F/tts-tech-portfolio/216/workflows/5f74e588-382f-45d9-a1bc-dfa998e6e63d/jobs/230):

```
Too many command line arguments. Did you mean to use -chdir?
```

Not sure if [the orb we are using for Terraform](https://circleci.com/developer/orbs/orb/circleci/terraform) is out of date or we need to specify the directory a different way or what.

## Implementation Steps

- [ ]

## Acceptance Criteria

- [ ] `terraform validate` passes in continuous integration for this repository

**Comment by adborden** [comment]
Heh, I suggest not debugging this and just moving to GH actions. @mogul mentioned https://github.com/dflook/terraform-github-actions, and they really are well done. Based on [example workflows](https://github.com/GSA/datagov-iam/tree/main/.github/workflows) from data.gov, it would be a quick implementation of copy paste and moving secrets into GH.

Any reason to stick with CircleCI and the orb?

**Comment by afeld** [comment]
I don’t feel strongly about CircleCI vs. Actions, though that seems like a relatively large change to sidestep this issue. However we get checks working again is fine by me.
