### ISSUE TITLE
free up private repos in 18F org

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1405]
## Background Information

We've hit the limit (125) on our legacy plan. We did a pass to delete ones without meaningful content (records) a few months(?) ago, so not sure doing so again would help.

## Implementation Steps

- [ ] Transfer some private repos to the GSA org, which shouldn't have a private repo limit

## Acceptance Criteria

- [ ] We have 10+ private repo slots under @18F

**Comment by gbinal** [comment]
For what it's worth, I'd also encourage:

* being willing to sort by recent and make some unilateral calls on deleting any that seem incredibly likely to be old and no longer needed
* sort by stars and visually skim any that have zero stars, forks, open issues, or open pull requests (the four metrics easily seen at a glance) and then open up those to see if possibly the repo was unused, or perhaps just ised to a de minimus amount
* sort alphabetically and see if there's any groupings of similarly named repos that could easily have their content consolidated

**Comment by afeld** [comment]
Very few of our private repos are still in use (I imagine), but we keep them around for records retention purposes.

**Comment by adborden** [comment]
I started from the [end of the list (least recently updated)](https://github.com/18F?language=&page=5&q=&sort=&type=private) looking at archived private repositories. I'm trying to select repos that are:
- not related to 18F projects
- not related to internal 18F work (e.g. staffing repos)
- have only a few commits
- have only a few issues

Here's a list of 10 repos https://gsa-tts.slack.com/archives/CNW3GL70S/p1625615930003400

**Comment by adborden** [comment]
@JJediny transferred the 10 repos to @GSA.
