### ISSUE TITLE
complete OLU training - due 6/30

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1418]
_DESCRIPTION GOES HERE_

## Procedure

1. Once anyone has started it, move the issue into `In Progress`.
1. Once an individual has completed it, they should be removed from the assignment.
1. When the last person has completed it, close the issue.

## Acceptance criteria

- [ ] GSA 2021 Employee Accountability for GSA Personal Property for Curriculum 2021 GSA Mandatory Training Refresher for Employees that is due on 6/30/2021 11:59 PM America/New York.
- [ ] GSA 2021 Enhancing Customer Experience at GSA for Curriculum 2021 GSA Mandatory Training Refresher for Employees that is due on 6/30/2021 11:59 PM America/New York.
- [ ] GSA 2021 Plain Language for Curriculum 2021 GSA Mandatory Training Refresher for Employees that is due on 6/30/2021 11:59 PM America/New York.

**Comment by adborden** [comment]
I've completed my trainings for June, un-assigning myself.

**Comment by JJediny** [comment]
Completed
