### ISSUE TITLE
Use CODEOWNERS to automatically ping the Tech Portfolio for review

### ISSUE THREAD

**Issue by dylanirlbeck** [18F/tts-tech-portfolio#1427]
## Background Information

The CODEOWNERS file allows project owners to assign individuals or teams to various files. If changes are proposed to their files, code owners will automatically be added as reviewers. 

For repos that the Tech Portfolio oversees, it would be preferable to have a CODEOWNERS file. For projects where the content is completely owned by the Tech Portfolio, this file will have one `*   @18F/tts-tech-portfolio` rule. For other projects, the file could get more complex.

This issue is inspired by [this Slack conversation](https://gsa-tts.slack.com/archives/C0DCAMLQH/p1625005919006500).

## Acceptance Criteria

- [ ] All Tech Portfolio repos have a CODEOWNERS file

**Comment by afeld** [comment]
This is more valuable on repositories with shared ownership (e.g. the Handbook and join.tts.gsa.gov), versus ones that are fully owned by the Tech Portfolio and thus all pull requests will be reviewed by the OpsRotation person.

**Comment by afeld** [comment]
We have this in place for the Handbook. Since repositories are reviewed as part of OpsRotation anyway, not going to worry about this.
