### ISSUE TITLE
"SmartCard certificate is not trusted" message is misleading

### ISSUE THREAD

**Issue by adunkman** [18F/tts-tech-portfolio#143]
> As a TTS member, I want to know what to do when I encounter a “SmartCard certificate is not trusted” error.

This error has come up a number of times in recent memory and is now occupies a part of my brain in the “useful things to tell a new hire” folder:

- https://gsa-tts.slack.com/archives/C028WFKN1/p1571682499028500
- https://gsa-tts.slack.com/archives/C039MHHF8/p1571320030061600
- https://gsa-tts.slack.com/archives/CBY8D3M6E/p1567523246077200?thread_ts=1567518384.070100&cid=CBY8D3M6E
- https://gsa-tts.slack.com/archives/CBY8D3M6E/p1567523527077800?thread_ts=1567518384.070100&cid=CBY8D3M6E
- https://gsa-tts.slack.com/archives/C04KL9ZN2/p1570024296222000?thread_ts=1569938734.206500&cid=C04KL9ZN2

The solution seems to be that the PIV card isn’t making good contact with the reader, which is a relatively easy fix — but the error message is computer-focused and therefore pretty misleading.

Would it be low-hanging fruit to change this message? Just spitballing: 

> Your SmartCard wasn’t recognized. Try wiping off the chip and trying again. If the issue persists, contact GSA IT. (Error: certificate not trusted)

Also, long-time lurker, first time issuer. Let me know if this isn’t your jam, or if this is better suited for another place, and I’ll reach out there.

**Comment by its-a-lisa** [comment]
@adunkman thanks for the submission! Appreciate it and keep them coming. 
@bengerman13 FYI, this might be helpful for when we tag up with GSA IT today to chat about fixing the pop up. I'm not exactly sure if this 100% related, but its useful background information if not.

**Comment by its-a-lisa** [comment]
@adunkman I brought up this suggestion, and was told it was resolved via a hardware fix (provided different PIV readers) rather than software fix (updating message) ... I will be on the lookout to see if this question comes up more, and if so, elevate it then; but based on the current response, I am going to close this issue as is now.
