### ISSUE TITLE
Cyber EO concerns for cloud.gov applications

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1433]
- [ ] Plan for egress control - due ? - https://github.com/18F/aws-admin/issues/125
- [ ] End-to-end encryption in cloud.gov - due ?

**Comment by rpalmer-gsa** [comment]
Cloud.gov Concerns

Cyber EO requires End to End Encryption of all data. Cloud.gov does not provide a mechanism for End to End Encryption from External -> App, not does it provide a easy way to implement container to container encryption. 
SC-8 (1), SC-28(1)

Cloud.gov does not allow for tenants to implement Egress Control. SC-7c. This is a significant.

Cloud.gov does not utilize or provide tenants the ability to use FIPS 140-2 Validated modules. Strong Crypto, TLS 1.2+ GSA, FIPS, NIST approved can meet partial implementation.

**Comment by pburkholder** [comment]
https://docs.google.com/document/d/1305gdMf8Q6OIzwfmuT4XJaw4-lTR0DNa10346wZDRcA/edit Discusses E2E

**Comment by rpalmer-gsa** [comment]
Brief of FedRAMP team.

ATO conditions are being added for these controls. Egress control and End to End Crypto per Cyber EO.

**Comment by rpalmer-gsa** [comment]
Splitting issue.

**Comment by afeld** [comment]
See https://github.com/18F/aws-admin/issues/125 re: egress control.

**Comment by rpalmer-gsa** [comment]
Closing and splitting. 

https://github.com/18F/tts-tech-portfolio-private/issues/1009
https://github.com/18F/tts-tech-portfolio-private/issues/1010

**Comment by rpalmer-gsa** [comment]
Can't close due to permissions.

**Comment by rocheller123** [comment]
@rpalmer-gsa Aaron may have fixed this. Please try closing the issue again.
