### ISSUE TITLE
onboard Rochelle

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1439]
**NewPerson and Buddy:** Try to go through your checklists in order.

**Buddy:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that someone with the correct access completes that item_.

### Getting to know TTS Tech Portfolio

- [x] Read [the Tech Portfolio Handbook page](https://handbook.tts.gsa.gov/tech-portfolio/) and things linked from there.
- [x] Read [the team onboarding document](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/onboarding.md).
- [x] Read about [how we work](https://github.com/18F/tts-tech-portfolio/tree/main/how_we_work#readme) and things linked from there.
  - [x] [Team workflow](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/workflow.md)
- [x] Submit a pull request to make the Tech Portfolio's onboarding documentation/checklist better.

### Required items for all team members

Ensure you know what's happening on the team:

- [x] Subscribe to the [Tech Portfolio team calendar](https://calendar.google.com/calendar?cid=Z3NhLmdvdl82aDI5YnF1ZGx0NGVoZTVzOWswOGlmdGZxMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) (click the + in the bottom right) so you know when assorted team meetings are happening. Tip: When you plan Out of Office time, make a calendar event for that on the TTS Tech Portfolio calendar so that your teammates know you'll be away.
- [x] [Watch](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions#configuring-your-watch-settings-for-an-individual-repository) [our repositories](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/github.md)

Learn our policies and procedures:

- [x] Coordinate with your onboarding buddy to go through [Incident Response Training](https://docs.google.com/presentation/d/1AZjQE8zBzMRWZIFUuJPkJLted1ykGtALrLPoPRx5Vls/edit#slide=id.p) within 60 days of joining the team (and annually after that). This will cover the following document, which you should also review before or after training:
- [x] Read [Before You Ship](https://before-you-ship.18f.gov/)
- [x] Coordinate with your onboarding buddy to go through [nonpublic information training](https://docs.google.com/presentation/d/1rXSZZ0t0kadsoP1EMJoM0T7ROkGD3Pr5wojWnf2GksI/edit) within 60 days of joining the team (and annually after that). This will cover the following documents, which you should also review before or after training:
- [x] Review the [18F open source policy guidance about protecting sensitive information](https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information)
  - [x] Review the [TTS requirements for password management](https://handbook.tts.gsa.gov/password-requirements/)

Learn about what we do:

- [x] [DNS](https://github.com/18F/dns)
- [x] [How to create GitHub issues in our board](https://docs.google.com/presentation/d/1q8aCGgzBfP9B8yJrMHfavTwAYPupgdT94ktGPsHzjVU/edit)

## Buddy checklist

- [x] Introduce yourself to the new team member and give them some of your background so they know who you are; if you are comfortable, share your Readme and encourage them to create their own
- [x] Identify a straightforward, well-groomed story in progress that involves their skills domain, schedule a meeting with the owner for an introduction (if it's not you), and setup pairing sessions several times in the first week on the project. - [brainstorming doc](https://docs.google.com/document/d/1yVxWRDfw6sbljHFMelOjKxUHQMBICGnFyaO_aXkSU24/edit)
- [x] Have the person shadow whomever is on [OpsRotation](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/ops_rotation.md), so they can see how we handle support and read with those within TTS.

### Required items for all team members

Add them to:

- [x] [The @tech-portfolio user group in Slack](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group)
- [x] [The @18F/tts-tech-portfolio team in GitHub](https://github.com/orgs/18F/teams/tts-tech-portfolio/members)
- [x] [The Everyone issue template](https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/everyone.md)
- [x] The OpsRotation schedule
- [x] [The TTS Tech Portfolio Roles](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/roles.md)
- [x] [The employee list in SmartSheet](https://app.smartsheet.com/sheets/Q2CgG9V897x8rRmv8XhGGjrhFRxVVqgVx5hCmW41?view=grid)

### Google Groups

- [x] [TTS Software](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-software/add)
- [x] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add)
- [x] [TTS Vulnerability Reports](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)

### Account Access

Add as an admin to:

- [x] AWS, via [cross-account access](https://github.com/18F/aws-admin#cross-account-access)
- [x] ~[DockerHub](https://hub.docker.com/orgs/18fgsa)~ [#983](https://github.com/18F/tts-tech-portfolio/issues/983#issuecomment-809516800)
- [x] [`TTS-managed` GitHub orgs](https://handbook.tts.gsa.gov/github/#organizations)
- [x] HackerOne
  - [x] [Public team](https://hackerone.com/tts/team_members)
  - [x] [Private team](https://hackerone.com/tts-private/team_members)
- [x] [InVision](https://gsa.invisionapp.com/d/main?origin=v7#/company/members)
- [x] [Mural](https://app.mural.co/t/gsa6/settings/members)
- [x] [New Relic](https://account.newrelic.com/accounts/562946/users)
- [x] (@afeld) [npm](https://www.npmjs.com/settings/18f/members)
- [x] [Slack](https://handbook.tts.gsa.gov/tools/slack/user-management/#offboarding)

**Comment by adborden** [comment]
Going through the Buddy checklist but running into some snags:
- I can't find the teams settings in Slack to add Rochelle to the Tech Portfolio team, or as a Slack admin
- Not sure what it means to add Rochelle to OpsRoation... Do I need to edit all the calendar invites?
- I requested access to the employee list in SmartSheet
- I don't have ownership permission to add Rochelle to [devops@](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add) or [tts-vulnerability-reports@](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)
- The seat count is full for DockerHub, we can't add anyone new ([#983](https://github.com/18F/tts-tech-portfolio/issues/983#issuecomment-809516800))
- I'm not an admin of these GitHub orgs and cannot add Rochelle
  - [@cloud-gov](https://github.com/cloud-gov)
  - [@digital-analytics-program](https://github.com/digital-analytics-program)
  - [@digitalgov](https://github.com/digitalgov)
  - [@federalist-users](https://github.com/federalist-users)
  - [@fedramp](https://github.com/fedramp)
  - [@fellows-in-innovation](https://github.com/fellows-in-innovation)
  - [@project-open-data](https://github.com/project-open-data)
  - [@presidential-innovation-fellows](https://github.com/presidential-innovation-fellows)
  - [@usagov](https://github.com/usagov)
  - [@uswds](https://github.com/uswds)
- I'm not sure I'm a member of the [npm](https://www.npmjs.com/settings/18f/members) org and can't see the member settings

Not sure if I don't have the correct permissions or maybe we just need to update the checklist. We can clarify that the Buddy should grab an admin (or assign tasks to an admin) when the Buddy can't complete a task.

**Comment by adborden** [comment]
Rochelle, once you send me your GH handle, I can finish the GH tasks and get you assigned to this issue :)

**Comment by rocheller123** [comment]
it's rocheller123

**Comment by adborden** [comment]
@rocheller123 can you provide your https://www.npmjs.com/ handle and @afeld will add you to the 18f org?

**Comment by rocheller123** [comment]
@adborden https://www.npmjs.com/ handle is rori123

**Comment by afeld** [comment]
> I'm not an admin of these GitHub orgs and cannot add Rochelle

Addressing via https://github.com/18F/tts-tech-portfolio/pull/1464.

**Comment by afeld** [comment]
NPM invite sent.
