### ISSUE TITLE
anonymous feedback?

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#144]
We should consider providing a mechanism for anonymous feedback to be provided internally.

- [x] Confirm this is something we want to do
- [x] Create Google Form (or equivalent)
- [x] Fold into on-call activities
- [x] Document

**Comment by its-a-lisa** [comment]
Some good questions that could be included in the form 

https://beyondleanagile.com/2018/12/12/enterprise-business-agility-maturity-survey/

**Comment by its-a-lisa** [comment]
@afeld & @JJediny i did this for myself, it was really simple!

I’m going to go ahead and do this for us as a team unless ours something wet don’t want to do.

**Comment by afeld** [comment]
Sure! The trick will be figuring out how to promote it so we actually get submissions.

**Comment by its-a-lisa** [comment]
Moving to Waiting/Blocked until the following pull requests are merged (sorry they're so many, I was having trouble w/ GitHub)

- https://github.com/18F/tts-tech-portfolio/pull/370
- https://github.com/18F/tts-tech-portfolio/pull/371
- https://github.com/18F/tts-tech-portfolio/pull/372
- https://github.com/18F/tts-tech-portfolio/pull/373

**Comment by its-a-lisa** [comment]
All pull request have been merged; closing.
