### ISSUE TITLE
retro with CTO team {GROOM THIS}

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1453]
## Implementation Steps

- [x] Send invite 
- [x] Do retro
- [ ] Create issues for follow-up tasks

## Acceptance Criteria

- [ ] Follow-up TODOs created from the takeaways

**Comment by josephderosales** [comment]
**[Retrospective Minutes](https://docs.google.com/document/d/1i4jxW0gPKNJMzAJmiCq_JnhxUAV_haIw-6ksMFVFGKg/edit#heading=h.5k0dfwtu1uf)**
