### ISSUE TITLE
Prep for Digital Council presentation/discussion on BYS decomissioning - due 7/26

### ISSUE THREAD

**Issue by dylanirlbeck** [18F/tts-tech-portfolio#1473]
Prepare to discuss my experience decomissioning (or merging) before-you-ship.18f.gov into handbook.tts.gsa.gov during the Digital Council weekly meeting.

**Comment by afeld** [comment]
Ideas about what to cover:

- What's involved
   - Can talk them through the [checklist](https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/decommission.md#readme)
- Level of effort
- Challenges
- Things to consider for future decommissioning

Note the audience has a mixed level of technical expertise.

**Comment by dylanirlbeck** [comment]
Outline:
* Discuss the high-level decommissioning (what I did)
* Create a checklist for decommissioning content sites/microsites
   * Let search.gov know so they can re-index
   * Setting up redirects.
   * Archiving repositories and communicating about the decomissioning on the README.
* Level of effort: moderate. Mostly tedious -- setting up redirects, converting formatting from BYS into Handbook-amenable format, fixing broken internal links.
   * This work is mostly technical, but there could be some training involved to ramp people up depending on how many sites will be decomissioned. 
* Things to consider
   * My read is that this work is not easily automatable: of course, I may be wrong.
   * Breaking things up into incremental pieces -- set up one redirect at a time.
   * Whether guides -- like the ux-guide, content-guide, engineering-guide -- should be in the Handbook or digital.gov?
