### ISSUE TITLE
check on empty position

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1484]
## Implementation Steps

- [ ]

## Acceptance Criteria

- [ ]

**Comment by adborden** [comment]
I got confirmation from @LeighFinkel that it's too late to catch this round of hiring. @HuixianXu is currently on leave, but will check with her on headcount when she returns.

**Comment by afeld** [comment]
To be more specific about why the question came up: Under `My Team` in HRLinks, I see

```
Empty Position 90017479
IT Specialist (INFOSEC)
```

**Comment by adborden** [comment]
I reached out to @martyspence that we're at the limit of 3 FTEs for FY22, but there are vacancies overall and we could go through Dave Z to leverage that.
