### ISSUE TITLE
Create process for deleting pending invitations in Mural

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1487]
## Background Information

In order to prevent stale invites to Mural from being abused, TTS Tech Portfolio wants stale invites to Mural deleted after X days.

[Mural maintains a list of Pending Invitations](https://app.mural.co/t/gsa6/settings/members), some of which are as old as 2018. These invitation include Guest and Member access to Mural and are not managed with the same process for active users. It has the potential to be abused for unauthorized access to Mural.

## Implementation Steps

- [ ]

## Acceptance Criteria

- [ ]

**Comment by adborden** [comment]
I manually removed all invitations older than 90 days.

**Comment by afeld** [comment]
Probably makes sense to do this with https://github.com/18F/tts-tech-portfolio/issues/1385.

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio-private/issues/1008.
