### ISSUE TITLE
Migrate away from Microsoft Office for Mac 2016

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#151]
Action: Initiate Transition strategy to migrate away from Microsoft Office for Mac 2016

Problem we're trying to solve:

Actions to take:
- [ ] Consider other options like libreoffice.org

Acceptance criteria:

Related issues: 
#150

**Comment by afeld** [comment]
See also: https://trello.com/c/SuRExGFu/88-straighten-out-licensing-for-office-for-mac
