### ISSUE TITLE
Improve offboarding template

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1512]
## Background Information

In order to be sure that offboarding has been done securely and correctly, TTS programs want the Tech Portfolio to have clear and explicit offboarding instructions.

The offboarding issue says:
>  - Copy in the onboarding buddy checklist
>    - Adjust/reverse as appropriate

This leaves offboarding ambiguous an implicit.

**Examples:**
[Data.gov offboarding](https://github.com/GSA/datagov-deploy/blob/master/.github/ISSUE_TEMPLATE/offboard-team-member.md) includes this instruction:
> All tasks should be checked and completed. For tasks that are not applicable, perhaps because the team member did not have this particular access, please confirm that the team member in fact has no access before marking the task complete.

## Implementation Steps

- [x] If we want to have a single source of truth, let's make the offboarding issue the explicit list, and make the onboarding the one that you copy to.

## Acceptance Criteria

- [x] WHEN I review the [offboarding template](https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/offboarding.md)
  THEN I see a clear and explicit list of tasks to complete
  AND the list is not open to subjectivity or modification (e.g. If x, then remove access)
  AND by completing the check list, the outgoing team member will have no access to Tech Portfolio systems

**Comment by afeld** [comment]
We want to balance having clear offboarding instructions (for security reasons) with not having to maintain a mirrored list in two places. Compromise is to make the offboarding list the canonical one and copy into onboarding, since there's more room for error in the latter.

**Comment by rocheller123** [comment]
Another issue ([#1551](https://github.com/18F/tts-tech-portfolio/pull/1551)) was created that contains the actual changes to the offboarding template.
