### ISSUE TITLE
complete data types data call for Zendesk - due 8/6

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1517]
## Background Information

Pranjali reached out and asked us to complete this ASAP:

https://docs.google.com/forms/d/e/1FAIpQLScICNWAoY5ILAga0HXRo0jybwMFNBm_XwCI3zPKzp5K66yT-A/viewform

## Implementation Steps

- [ ]

## Acceptance Criteria

- [ ]

**Comment by JJediny** [comment]
Completed form submitted 8/6
