### ISSUE TITLE
Payer account raising root_login CloudWatch alarm

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1518]
## Background Information

https://groups.google.com/a/gsa.gov/g/18fsoftware/c/-bJ5XOzF7As

Payer account is raising the `root_login` alarm. It's unclear what action should be taken to prevent this. Ideally it would be directed to the person logging in to encourage them to use an IAM account with MFA instead of the root login.

Opened as part of [ops rotation](https://github.com/18F/tts-tech-portfolio/issues/1485).

## Implementation Steps

- [x] Confirm reseller was the one using the credentials

## Acceptance Criteria

- [x] GIVEN I receive an alarm notification
  WHEN I review the content of the alarm
  THEN it is clear what action should be taken.

**Comment by adborden** [comment]
... or if we're the only ones with root access on the payer account, we can rewrite this story to be the action that cleans that up (configure an IAM account with MFA).

**Comment by JJediny** [comment]
Reseller confirmed this was a AWS action and that they will otherwise refrain from root account
