### ISSUE TITLE
determine on source of truth for Solutions contracts

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#155]
Coordinate with Acquisition and Solutions leadership to finalize. Can keep the scope narrowed to awarded (in flight) contracts if that's helpful.

- TTS-wide
    - [TTS OA Post-Award Management Trello board](https://trello.com/b/E6jsnfRZ/tts-oa-post-award-management)
    - [TTS Wide Contract Inventory spreadsheet](https://docs.google.com/spreadsheets/d/1ugJMb5lzwriP0e0Jkf2GMrxbBtjrsvQkSGUJZUA5e44/edit#gid=98184677)
        - [`OPP2` sheet](https://docs.google.com/spreadsheets/d/1ugJMb5lzwriP0e0Jkf2GMrxbBtjrsvQkSGUJZUA5e44/edit#gid=978587416) pulls from TTS Solutions Contract Inventory
    - [Contract Inventory Beta 3.0 spreadsheet](https://docs.google.com/spreadsheets/d/1iJqFcTIYjAeRiMSqL2NhlGxGQ6tB4HphcwiU45bWPe4/edit#gid=1462414068)
    - [TTS FY20 Projected Contract Support](https://docs.google.com/spreadsheets/d/1ZOLrpVGBeZUl4r2fyfXH5zzXdBjWLF9zCP1iih49NYg/edit#gid=0)
- Solutions/FCSF
    - [TTS Solutions Contract Inventory spreadsheet](https://docs.google.com/spreadsheets/d/1S9cUnhRwfdsxcgT_h8ynHBbOQBxHgWlN-pzQ3yHw5_E/edit#gid=0)
    - [FY20 FCSF Contracts spreadsheet](https://docs.google.com/spreadsheets/d/1iGf5ygdJyZBUpg09UgL3TN64M2SipdaDPcWPQ8d-wF0/edit?usp=sharing)
    - [OPP Contracts spreadsheet](https://docs.google.com/spreadsheets/d/1wQoOlnBvshnAmLatqtoEY-BNVMi-wl_Jf92Hc4ZnKiQ/edit#gid=86433535)
- [Mapping of columns between the different inventories](https://docs.google.com/spreadsheets/d/18UvVsjeS5OoaGCXaGonrRTj1JccssHHwRVNYvIz99rg/edit#gid=0)

Threads:

- Email with subject `Contract Inventory`
- [Thread in `#sol-leads`](https://gsa-tts.slack.com/archives/C3F3HR717/p1572025215047800)
- [Thread in `#tts-oa`](https://gsa-tts.slack.com/archives/CD4F3TGB1/p1572620847023200)

## Acceptance criteria

- There is a single place to look to find current contracts for Solutions (if not all of TTS), linked from https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/internal_links.md

**Comment by afeld** [comment]
Should say: it doesn't need to be (and arguably shouldn't be) the Tech Portfolio that makes the determination; tracking here for lack of a better place.

**Comment by afeld** [comment]
Per @thecapacity, [this is being taken care of](https://gsa-tts.slack.com/archives/C3F3HR717/p1578347930005700?thread_ts=1576700904.018400&cid=C3F3HR717) as part of the [FY20 spend plan](https://docs.google.com/spreadsheets/d/1YSfw_5ByfgB03gFOYcc0VkrFxh1vMtx5D0DpwaYUpBI/edit#gid=239859745).

**Comment by afeld** [comment]
@stephencarroll Who did you say is going to be working on this?

**Comment by michellepetryszyn** [comment]
Daisy Tamberino

**Comment by afeld** [comment]
Per @stephencarroll, this is actively being worked on 🎉

**Comment by stephencarroll** [comment]
@michellepetryszyn - If Daisy at a place where she could brief Aiden et al on where she is at this point?

**Comment by michellepetryszyn** [comment]
Sorry for the late response. Yeah, I think Aidan and Daisy should meet and discuss.

**Comment by afeld** [comment]
Closing this, since it a) is more of an Acquisitions thing than a Tech Portfolio one, and b) doesn't seem like it's going to get finished anytime soon.
