### ISSUE TITLE
OLU training - due 10/1

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1564]
_DESCRIPTION GOES HERE_

## Procedure

1. Once anyone has started it, move the issue into `In Progress`.
1. Once an individual has completed it, they should be removed from the assignment.
1. When the last person has completed it, close the issue.

## Acceptance criteria

- [ ] Everyone (previously) assigned has [FILL IN]

**Comment by adborden** [comment]
✅ I've completed COOP and Records Management, all training due 10/1.
