### ISSUE TITLE
develop RFI for digital whiteboarding

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1566]
[**RFI**](https://docs.google.com/document/d/1P2XS6HJonJCCUrb5NSliqvdV6ZX5HOBOq1XSastHl24/edit?usp=sharing)

## Background Information

cc https://github.com/18F/tts-tech-portfolio-private/issues/1008

## Implementation Steps

- [ ]

## Acceptance Criteria

- [ ]

**Comment by adborden** [comment]
This is done.
