### ISSUE TITLE
reconcile FITARA approval instructions

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#157]
- https://docs.google.com/document/d/1DRuM05nVsCKhZrhyQHs7oa1vQY_Llb29QKv2IdA_SPI/edit?ts=5d13741d#
- https://handbook.18f.gov/fitara/#approval-process

cc @josephderosales

**Comment by afeld** [comment]
Better yet, perhaps we make a [card template](https://blog.trello.com/trello-card-templates) for the requests that has a checklist.

**Comment by JJediny** [comment]
We've meet with OA and products and agreed to endorse the current trello->pdf->docusign approach for the FY20 batch of SaaS approvals. The shared procedure is https://docs.google.com/document/d/1nLgvqN17Yi-l70kkVt46_I6T59cYKLD73OPbaaG6Kss/edit?ts=5de97dd2 

Will create a new issue if/when improvements or new tooling/workflow is being considered
