### ISSUE TITLE
Offboard aidan.feldman@gsa.gov

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1582]
Assignee: The tasks below are organized by the role needed to complete them. If you canʼt complete
any of the items on your checklist personally, you are responsible for ensuring that an appropriate person
does it.
For compliance tracking purposes we need to show when offboarding actions happened; many need to
occur in a 24-hour window. As you do this work, comment on this GitHub issue as you complete each
task. (PS-4: Personnel termination)

## Departing Person

- [x] [Initiate the process](https://handbook.tts.gsa.gov/leaving-tts/)

## Assignee

- [x] Remove them from #tts-tech-portfolio-private
- [x] Copy in the [onboarding buddy checklist](hhttps://raw.githubusercontent.com/18F/tts-tech-portfolio/main/.github/ISSUE_TEMPLATE/onboarding.md)
  - [x] Adjust/reverse as appropriate
---

### Required items for all team members

Ensure you know what's happening on the team:

- [x] Unsubscribe to the [Tech Portfolio team calendar](https://calendar.google.com/calendar?cid=Z3NhLmdvdl82aDI5YnF1ZGx0NGVoZTVzOWswOGlmdGZxMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) (click the + in the bottom right) so you know when assorted team meetings are happening. Tip: When you plan Out of Office time, make a calendar event for that on the TTS Tech Portfolio calendar so that your teammates know you'll be away.
- [x] Remove from [our repositories](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/github.md)

Remove them from:

- [x] [The @tech-portfolio user group in Slack](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group)
- [x] [The @18F/tts-tech-portfolio team in GitHub](https://github.com/orgs/18F/teams/tts-tech-portfolio/members)
- [x] [The Everyone issue template](https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/everyone.md)
- [x] The OpsRotation schedule by editing the existing calendar invites (it's a little tedious, but you'll be inserting a new invite, shifting others, and adjusting the recurrence)
- [ ] [The TTS Tech Portfolio Roles](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/roles.md)
- [x] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add) (devops) as a Member
- [x] [GSA Archer](https://handbook.tts.gsa.gov/launching-software/lifecycle/#rsa-archer) read access to system security plans (SSPs)
  - [x] Check the boxes for [all TTS FISMA systems](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1235102795&fvid=1731762212)

### Account Access

Add as an admin to:

- [x] Create new user in tts-prod AWS account
  - [x] Create the user using their email address as the username, with console access, with autogenerated password, and require a password reset on first login
  - [x] Send their temporary credentials over a secure channel, like Google Chat
  - [x] Assign the user to the tts-tech-portfolio-admins group
- [x] [DockerHub](https://hub.docker.com/orgs/18fgsa)
- [x] Assign team member [Owner role in 18F GitHub org](https://github.com/orgs/18F/people/pending_invitations)
- [x] HackerOne
  - [x] Add team member to the `Admin` and `TTS Bug Bounty Team` groups on the [Public team](https://hackerone.com/tts/team_members) 
  - [x] Add team member to the `Admin` and `TTS Private Bug Bounty Team` groups on the [Private team](https://hackerone.com/tts-private/team_members)
- [ ] Invite team member to [InVision](https://gsa.invisionapp.com/teams/people/members), then Change their Role to Admin
- [x] Invite team member to [Mural](https://app.mural.co/t/gsa6/settings/members), then give them Workspace Admin permissions
- [x] [New Relic](https://account.newrelic.com/accounts/562946/users)
- [x] Add team member as Owner to [npm](https://www.npmjs.com/settings/18f/members) organization

**Comment by JJediny** [comment]
@rocheller123 will create the icebox issue to change the invision owner separately
