### ISSUE TITLE
Update TTS SaaS Inventory with latest ATO/FITARA status

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#161]
https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0

**Comment by afeld** [comment]
I was curious about fetching data from Google Sheets to keep this in sync automatically—see the [example sheet with IT Standards data](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=74703898). Would be cool to have the ATO expirations pull from that!

**Comment by afeld** [comment]
Similarly, got FedRAMP status into [another sheet](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=244522641) using an App Script.
