### ISSUE TITLE
transfer NSF SBIR

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#163]
This project ended a long time ago.

https://github.com/18F/nsf-sbir

- [ ] Contact NSF
- [ ] Initiate transfer of repository
- [ ] Transfer repository

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
