### ISSUE TITLE
web-based brainstorming and collaboration tool

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#164]
- [x] Determine if Mural plans to pursue FedRAMP
- [x] Confirm extension
- [x] Confirm expiration in GEAR is updated

**Comment by its-a-lisa** [comment]
Sent an email on 12/16 in pursuit of this activity
@Ryan Hoesing - QQC -- can you confirm that Mural is pursuing FedRAMP tailored? 

@Joseph de Rosales - I / @Cindy Smith - IG  -- can we get GEAR updated? It was mentioned that the comments have been updated, but I'm not seeing it. 

On 12/17 Ryan Hoesing reached out to Mural

On 12/30 I pinged Ryan to see if he was able to tag up with Mural

Putting in the Waiting/Blocked column until I hear back from him

**Comment by its-a-lisa** [comment]
we just got word that the Mural LiSaaS ATO was extended until 12/20/20 -- with the expectation that they get a FedRAMP Low authorization prior to the expiration

**Comment by its-a-lisa** [comment]
mural has been updated to approval extension date of 12/18/20 with comment "Note - A 1 year ATO has been signed for Mural with the following condition in place; The vendor shall complete, prior to the ATO expiration date (12/18/20), an ongoing FedRamp Low authorization for continued use of the service by GSA."
