### ISSUE TITLE
Aidan: hand off responsibilities for 11/25-12/10 vacation - due 11/22

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#167]
- [x] Convert items from the [personal stormdraining](https://docs.google.com/document/d/1wh_XH_LGA7_WU79zXSMWhF9L6Ps8Ifs2UCLWVk9LcFs/edit#) to checklists in this issue to hand off (temporarily or indefinitely)

**Comment by its-a-lisa** [comment]
Looks like this was done in #181  so we should close this
