### ISSUE TITLE
Evaluate Zoom License Model

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#175]
Assess quote for annual licenses and increasing the capacity for your standard Zoom license to 200 seats per meeting and 1 to 2 Large Meeting 500 licenses. 

https://drive.google.com/drive/folders/1bdHiS8d4VDUcvUtxKt6kcClaUJzD1KUq

**Comment by its-a-lisa** [comment]
Submitted micropurchase request https://mail.google.com/mail/u/0/?tab=rm&ogbl#all/FMfcgxwGBmxPRnKVlRgGdRRwMCGzZLjx

**Comment by JJediny** [comment]
We are proceeding with the switch to the new tier account tomorrow, the micropurchase is completed we just need to make the switch which is scheduled for tomorrow. Closing this as this was for the decision to switch which was made.
