### ISSUE TITLE
move the Documents for Infrastructure into our Handbook page

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#177]
- https://handbook.18f.gov/tech-portfolio/
- https://docs.google.com/document/d/1qIms6TcYOQ24BerQrxAFzTKAqVS6VNCpWklwTsxBmWA/edit

## TODOs

- [ ] Move that list into the Handbook page
- [x] Mark the document as deprecated

**Comment by its-a-lisa** [comment]
Instead of moving it to the Handbook page, I moved it to the [wiki](https://github.com/18F/tts-tech-portfolio/wiki/Documents-for-TTS-Tech-Porfolio) and linked to it in the Handbook under the "Read more about us" section
