### ISSUE TITLE
align security and acquisition/procurement incentives for SaaS

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#189]
Follow-up to #46.

In short: Could services that get FedRAMP authorized be automatically added to the GSA Schedule? [Details.](https://docs.google.com/document/d/1_N1YkUGzBMIwJEv53VQUpfYVxykjYHvWXeOkrpFER4I/edit?ts=5d485306#heading=h.x8w6v54kgcpl)

**Comment by its-a-lisa** [comment]
@afeld is this issue still open? Is it in progress based on our meeting w/ Ashley & Crystal?

**Comment by afeld** [comment]
Yep! I'd say our side of it is done; we can open up follow-up issues if there's anything actionable.
