### ISSUE TITLE
EPIC: Authentication/Authorization Management

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#19]
What software-as-a-service (SaaS) do we use that can be hooked up to existing in-house authentication providers?

Authentication options:

- SecureAuth
   - https://drive.google.com/file/d/1BWTSFMAfUzPqgQ2p3Ks-oVDbXZZzHtOq/view
   - https://docs.google.com/document/d/1_tJlC_GcUG6n6641iIg4QSfwSb3h8ginLhIW3EFj4C0/edit
- login.gov
- [cloud.gov UAA](https://cloud.gov/docs/apps/leveraging-authentication/)
- Google
- GitHub
- [AWS SSO](https://aws.amazon.com/single-sign-on/)
- ForgeRock through FAS
- Okta
- [MAX.gov Authentication](https://login.max.gov/cas/login)

Authorization options:

- IAM?
- GitHub teams?
- [Sailpoint](https://www.sailpoint.com/solutions/) - being rolled out by GSA
- [AWS Directory Service](https://aws.amazon.com/directoryservice/)
- [AWS Cognito](https://aws.amazon.com/cognito/)

We may need separate systems to handle authentication and authorization. The benefits for users are having fewer accounts to manage and fewer credentials. The big potential benefit on the administration side is automatic granting/revoking of access, based on things like:

- Having an `@gsa.gov` email address
- Being [a member of the 18F staff Github team](https://github.com/orgs/18F/teams/18f-staff/members)

This could cut out a lot of need for `#admin-*` acitivites, which is purely [toil](https://landing.google.com/sre/sre-book/chapters/eliminating-toil/), making onboarding and offboarding easier and more consistent. Example services that would be good candidates:

- Trello - requires [Business Class](https://trello.com/en-US/business-class)
- [Slack](https://get.slack.help/hc/en-us/articles/203772216-SAML-single-sign-on)
- GitHub - [SAML requires Enterprise](https://help.github.com/en/articles/about-authentication-with-saml-single-sign-on), but could sync team additions/removals
- [HackerOne](https://docs.hackerone.com/programs/single-sign-on-sso-via-saml.html)
- [AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers.html)
- Mural - requires [Enterprise](https://mural.co/enterprise) for SAML
- [HubSpot](https://knowledge.hubspot.com/articles/kcs_article/account/can-i-use-single-sign-on-sso-with-hubspot)
- [CloudCheckr](https://success.cloudcheckr.com/article/dfynksflvz-sso-cloud-checkr-single-sign-on)
- [StatusPage](https://help.statuspage.io/help/single-sign-on-2)
- [New Relic](https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/set-sso)
- [Adobe](https://helpx.adobe.com/enterprise/using/set-up-identity.html)

Will make sense to break each out to a separate issue once we want to prioritize them.

cc #27

**Comment by afeld** [comment]
Per @mogul [in Slack](https://gsa-tts.slack.com/archives/CBY8D3M6E/p1562972363406400?thread_ts=1562967746.405700&channel=CBY8D3M6E&message_ts=1562972363.406400):

> [SecureAuth is] SAML 2.0. There's likely traffic on the topic in the cloud-gov-operators Google Group with someone in GSA IT

**Comment by amoose** [comment]
HubSpot, too? Login.gov is going to get an enterprise license for HubSpot which supports external IdPs.

**Comment by afeld** [comment]
[Notes from 8/2 meeting.](https://docs.google.com/document/d/1mWouEcrUNgJuIJscSJytCQ-zPpTqnerKJSeLoIWYW5Q/edit)

**Comment by afeld** [comment]
Split the list at the top into authentication and authorization. Please double-check, and feel free to edit directly if I got any wrong.

**Comment by brittag** [comment]
For cloud.gov, GSA SecureAuth and Google SSO are by far the best auth options for our security compliance requirements (because GSA SecureAuth is a "corporate" service that we use already, and G Suite has a Moderate FedRAMP authorization and we use it already). Anything else may require extra paperwork for us and could potentially be a blocker for us. For example, our authorizing team has previously disapproved of us using GitHub auth for non-GitHub services, especially because our use of GitHub does not have a FedRAMP Authorization (only the GitHub Enterprise Cloud product does, and that's only Low impact).

**Comment by amoose** [comment]
SecureAuth utilizes SHA1 signatures, redirects to arbitrary URLs and does not validate RP signatures.
