### ISSUE TITLE
Code it Forward project description - due 12/6

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#194]
From email `Code it Forward Interns - Project Descriptions`:

> Each of you has requested a CIF intern for this summer.  In order to move forward we need to provide **project descriptions** no later than **Friday, December 6th.**
>
> [Here](https://drive.google.com/file/d/0BynxjBcHPLcLdXVOc1prckNaWUhRMktFUzVyUHdWYjA2T2lz/view?usp=sharing) is an example provided by the fellowship that you can use as a reference.
>
> If you'd like to review what you submitted last year you can find it in [this folder](https://drive.google.com/drive/folders/1FD2rotviktMQWL7fUaHZzi8wYTIFKnKa?usp=sharing).

Note this may be somewhat blocked by #166.

**Comment by its-a-lisa** [comment]
https://docs.google.com/document/d/1p1uYykrM8V2mgJlVzspjpwziH9rkUiegOLVsWQ23Txo/edit

**Comment by its-a-lisa** [comment]
Sent email with document to @JennMoran today to close out
