### ISSUE TITLE
Reorganization of the TTS Micropurchase Shared Drive

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#215]
The documents associated with micropurchase approvals namely: FITARA, ATO, TOS, Invoices. Have been loosely organized. 

Acceptance Criteria:
- [x] Move folders and documents into a new folder layout that consists of 
- software
- services
- miscellaneous 
- Guidance
- Tracking 
- [x] Ensure Software folders are organized by SaaS 
- Primary folder for the FY
- Subfolder for Invoices with files for FITARA/ATO/TOS artifacts

**Comment by JJediny** [comment]
https://drive.google.com/drive/folders/1R2TAsyc3fXnKdJZeB-1uKDxRIq1ta_4p

**Comment by its-a-lisa** [comment]
Ooops! Reopened the wrong one!
