### ISSUE TITLE
clarify travel budget

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#218]
Broken out from #166.

- [Travel and training tracker](https://docs.google.com/spreadsheets/d/1U7_PfazFAq93I14EBxa3FfPJnLZ4OJ6zbG8bV-dh3eg/edit#gid=1179362210)

## TODOs

- [x] Confirm `Office of TTS Operations (QOA)` is the travel budget we've been using thus far
- [ ] Work with @ethanheppner on FY20 travel budget needs

**Comment by afeld** [comment]
Per https://github.com/18F/tts-tech-portfolio/issues/166#issuecomment-554061956:

- Travel and training come from the same budget line
- We have $3k per year per person ($9k) as a baseline
- There is some flexibility to use more if we need, as:
   - It was understood that I would travel to DC regularly
   - We share a budget line with the other shared services, and they regularly underspend on travel/training

**Comment by afeld** [comment]
From Matt Ryan:

> for the time being your travel will come out of the TTS front office LoA.  `2020 - 285X - 00 - DS00 - Q00OA000 - DO1 - AF200`

**Comment by its-a-lisa** [comment]
Can we call this done for now and open a new card once the LoA changes?

**Comment by afeld** [comment]
I think we are good with the LoA - need to find out how much of that we are clear to use.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
