### ISSUE TITLE
Board Grooming (December)

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#222]
#### Acceptance Criteria
- [ ] strip out all EPICs from Issues into one issue with links to all related/sub issues.
- [ ] Establish Acceptance Criteria for all actionable tasks per issue.
- [ ] Close out all issues that are not actionable.
- [ ] Close and consolidate related issues `in favor of issue/link`
- [ ] Create or label each issue to their EPIC(s)

Completed review of entire board:
- [ ] @its-a-lisa 
- [ ] @JJediny
- [ ] @feld

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/231.
