### ISSUE TITLE
write up Director responsibilities

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#227]
Part of #262.

I have not done a good enough job clarifying what I see as being responsibilities for the Director of the Technology Portfolio specifically, versus members of the team generally.

## TODOs

- [x] Review the [position description](https://join.tts.gsa.gov/join/technology-portfolio-director/) for ideas
- [x] Write up a list

**Comment by its-a-lisa** [comment]
Include items such as:
- SMT meetings
- Business weekly meetings
- Tag ups with leadership
