### ISSUE TITLE
TTS Organizational Level & Inheritable Documentation

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#229]
## Background information: 
Tier 2 addresses risk from a mission/business process perspective and is informed by the risk
context, risk decisions, and risk activities at Tier 1. 

Tier 2 activities directly affect the activities carried out at Tier 3. 

Enterprise architecture decisions at Tier 2 affect the design of information systems at Tier 3 including the types of information technologies acceptable for use in developing those systems. The activities carried out at Tier 2 can also provide useful feedback to Tier 1, possibly resulting in revisions to the organizational risk frame or affecting risk management activities carried out at Tier 1
## Related Issues: 
[Update TTS Incident Response Documentation](https://github.com/18F/tts-tech-portfolio/issues/265)
[Develop TTS Systems Maintenance Policy](https://github.com/18F/tts-tech-portfolio/issues/263)
[Develop TTS Continuous Monitoring Strategy](https://github.com/18F/tts-tech-portfolio/issues/263)
[Develop TTS Vulnerability Management Plan](https://github.com/18F/tts-tech-portfolio/issues/251)

[Initiate Planning activities for COOP Doucments](https://github.com/18F/tts-tech-portfolio/issues/264)

**Comment by afeld** [comment]
Likely a sub-epic(?) of https://github.com/18F/tts-tech-portfolio/issues/208.

**Comment by its-a-lisa** [comment]
Need to address flowing responsibilities down to systems (ie c[loud.gov managing their own GitHub](https://gsa-tts.slack.com/archives/C039MHHF8/p1583861987143700))

**Comment by afeld** [comment]
This is part of #152.
