### ISSUE TITLE
Determine the source-of-truth inventory of TTS systems

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#23]
## Story
As a member of TTS Tech Portfolio team, I need an authoritative source for custom software created under the TTS organization

## Problem we're trying to solve:
- There are many different lists that have pieces of information. 
- The different sources don't match up with each other.
- The different sources get out of date. 

## Background information: 
- Gear is supposed to be the authoritative source, but there are difficulties with it

## Actions to take:

- [x]  Gather all the [sources]( https://github.com/18F/tts-tech-portfolio/issues/23#issuecomment-511046588)
- [x]  Combine the sources into one [master spreadsheet](https://docs.google.com/spreadsheets/d/1LGn9kZCphzf14V5HpBfV3aYjflu-k9GtHS5LmFvDywM/edit#gid=1961439299)
- [x]  Normalize the data in the spreadsheet
- [x]  Get rid of erroneous information in the spreadsheet

## Acceptance criteria: 
- [x] All known custom software information is capture in one place
- [x] That one place is documented in the [Handbook](https://github.com/18F/handbook/pull/1597)

**Comment by afeld** [comment]
[TTS cloud.gov orgs](https://docs.google.com/spreadsheets/d/1Bdzl9n2E1MXWV4elXvZ-nYuZmmEj4PEU-u5aZlNGZF4/edit#gid=1352278899)

**Comment by its-a-lisa** [comment]
I am going to update the content of this issue to re scope it; but want to save a reference of the original issue here: 

Custom software, as opposed to SaaS (#27  ).

What the names are
Where to find the code
Slack channel(s)
System Owner / project/technical lead(s)
ATO status
GSA-wide, GEAR is supposed to be the canonical source, but it:

Isn't accessible off the GSA network - I had personally been manually exporting it
Isn’t easily updatable (by us)
Doesn’t track all the information we want
I have heard TTS has a spreadsheet (and perhaps knew where it was at one time), but need to find it again. Note this issue has a long history, including the about.yml project.

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/71#issuecomment-557182330
