### ISSUE TITLE
Check for End of Support tooling

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#239]
## Background information

-There is some highly used tooling in the IT field (Windows Server 2008 R2 & Python 2.7) that is getting to end of support in the very near future; would like to assure that we don't have those assets in our inventory; and if so -- what the POA&M for those items are

https://groups.google.com/a/gsa.gov/forum/#!msg/devops/4Y6bg_za-fU/FUtrXV1OBQAJ
https://support.microsoft.com/en-us/lifecycle/search/1163

## User stories
As someone who has a role in the Cybersecurity process (authorizing official) I want to make sure that none of the systems I am accepting the risk for have any End of Support offerings

As someone who manages IaaS, I want to make sure that the environment is setup so that End of Support assets are not used

## Implementation

- Talk with GSA IT Security to understand what role the TTS Tech Portfolio would have in assuring there isn't any End of Support tooling in our inventory

## Acceptance criteria

- Mutual understanding is accomplished

**Comment by afeld** [comment]
Clarify whether this is a one-time thing or a proposal for something ongoing, etc.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
