### ISSUE TITLE
Draft Micro purchase instructions

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#240]
## Supporting Documentation:
https://docs.google.com/document/d/1R9nqvevGpjrEp6ztvHVLS-ncyYbbKgDJ9ta2fKHh2Y8/edit?disco=AAAAJEIj73U
## Related Issues:

**Comment by afeld** [comment]
Note that we have [this Handbook section explaining it](https://handbook.tts.gsa.gov/purchase-requests/#behind-the-scenes)—what else is needed?

**Comment by afeld** [comment]
Calling this done—we can reopen if there are specific clarifications/updates that are needed.
