### ISSUE TITLE
As the Tech Portfolio team, I need admin rights to Infrastructure mailing lists

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#25]
- [x] For individual AWS accounts - we seem to use one Google Group per account
- [x] devops@gsa.gov - REQ0460723/RITM0636509
- [x] 18f-devops@gsa.gov - REQ0461537/RITM0637093 - not sure how much this one is still used
- [x] is-tts@gsa.gov
- [x] tts-vulnerability-reports@gsa.gov - maybe the same as the above?
- [x] 18fsoftware@gsa.gov
- [x] tts-software@gsa.gov
- [x] 18f-pypi@gsa.gov
- [x] Ask GSA IT what GSA mailing lists Kimber/Erik were on

What others am I missing?

cc @rahearn

**Comment by rahearn** [comment]
You should have owner permission on tts-vulnerability-reports@gsa.gov already.

There's a google group for "TTS representatives for guide and policy review" called `IS - TTS` that might be interesting.

**Comment by afeld** [comment]
> You should have owner permission on tts-vulnerability-reports@gsa.gov already.

Yes, thanks! Is this the "TTS Security" list you mentioned the other day? Are there any others that should be on this list?

> There's a google group for "TTS representatives for guide and policy review" called `IS - TTS`

Is that a thing you can add me to? Any idea who the owner is?

**Comment by afeld** [comment]
Contacted the service desk to get on `18f-devops` and `devops` mailing lists - INC2752173.

**Comment by rahearn** [comment]
> Yes, thanks! Is this the "TTS Security" list you mentioned the other day? Are there any others that should be on this list?

Yes, that's the one I was referring to. I'm not on any others that seem like they might be useful to you other than the `IS - TTS` list.

Speaking of that list: I can't add you to it. Blanche Heard and Jerry Morgan are the owners.

**Comment by afeld** [comment]
_Done_ 😅
