### ISSUE TITLE
Develop TTS Configuration Management Plan

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#250]
## Background information:
Recently there was confusion that someone outside of TTS was merging pull requests in our repositories, should have a document that clarifies the process and procedure. 

There was an activity that archived repositories that weren't maintained and a next step from that activity was to improve the merge activity to happen quicker.  
## Supporting Documentation:
https://docs.google.com/document/d/1ajcxPViV_UyiUHTJQ8Qmi5-nVlvM-bXozqPY8HmMWxg/edit
## Related Issues: 
https://github.com/18F/tts-tech-portfolio/issues/17
https://github.com/18F/tts-tech-portfolio/issues/193

**Comment by afeld** [comment]
Small clarification: I think the confusion was around approvals rather than merges. Merging can only be done by someone with write access.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
