### ISSUE TITLE
create proposal around swimlanes

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#257]
**User Story:**

As a member of TTS Tech portfolio, I want to be able to set the vision for tasks

As a member of TTS Tech portfolio, I want to be able to predominately work on tasks that fit into my knowledge, skill and experience

As a member of TTS Tech portfolio, I want to be able to work out the prioritization for task amongst other tasks in the swimlane

As a member of TTS Tech portfolio, I think that having swimlanes will help expedite tasks getting accomplished

As a member of TTS Tech portfolio, I think that having swimlanes will prevent tasks from slipping through the cracks

As the lead of TTS Tech portfolio, I want to make sure our team doesn't become too siloed

**Background information:**
The TTS Tech Portfolio is recently forming as a team and evolving the process and tools for accomplishing the work being done. Recently, the team developed several epics and general guidelines for their agile ceremonies. 

**Implementation:**

- [x] Fill in User Stor(ies) above
- [ ] Write a short proposal (a doc, pull request to the Project Board file...whatever works) on how this could work
- [ ] Solicit feedback from team
- [ ] Create follow-up issues, as necessary

**Acceptance Criteria:**

- The team understands what having swimlanes would mean in terms of our workflow

**Comment by its-a-lisa** [comment]
@afeld 

Notes from our 1:1 today have slightly been captured in what I did for user stories. 

Other highlights include:
- Want to avoid...
   -  all tasks of a certain nature to _only_ going to one person
   -  any one person avoiding a particular category or class of tasks

Suggested path forward
   -  Every epic be assigned an Epic Owner
   -  Epics are the 'swimlanes' 
        -  Tech Portfolio members are encouraged to 
              - create the majority of tasks within their assigned epics
                   - approve the acceptance criteria of tasks within their epic if someone other than themselves created the task 
              - prioritize the tasks within the epic
              - set WIP limits for the epics
       -  Tech Portfolio members shouldn't expect to only work on tasks where they are epic owners
           - Want to avoid...
             -  all tasks of a certain nature to _only_ going to one person
             -  any one person avoiding a particular category or class of tasks

Other considerations:
   -  What if there are epics that nobody wants to own?
   -  What if there are epics that shouldn't have equal ownership from all Tech Portfolio members?

*currently in a back-logged situation and need to develop a roadmap to get to normal operations

**Comment by afeld** [comment]
Nice summary, thanks! I have ideas for the "other considerations," but will save until ready.

[Previous Slack conversation about swimlanes](https://gsa-tts.slack.com/archives/CNW3GL70S/p1576265931006900?thread_ts=1576265931.006900), for reference.

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/356.
