### ISSUE TITLE
As the Finance team, I want the Tech Portfolio to handle small purchases

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#26]
...to take work off their plate. This involves one or more members of the team getting a [P-Card](https://www.gsa.gov/buying-selling/purchasing-programs/gsa-schedules/schedule-buyers/purchase-card-holders).

- [x] Get copy of forms
- [x] Return forms
- [x] Get P-Card

**Comment by JJediny** [comment]
update: completed all required Pcard forms and got access to system, last step complete #68

**Comment by JJediny** [comment]
closing until we have a new pcard purchase
