### ISSUE TITLE
get a better sense of how many issues to plan for each sprint

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#260]
## Background information

In the meeting today working on the team documentation, someone wrote:

> Add in metrics for what we want to track in retros

I'm afraid I don't remember the surrounding details, so will defer to them to fill them in 😄 

## User stories

- As a ..., I want ... so that ...
- As a ..., I want ... so that ...

## Implementation

- [ ] [first small task]
- [ ] [another small task]

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

**Comment by afeld** [comment]
[code.gov metrics](https://github.com/GSA/code-gov-github-metrics/blob/master/DATASCHEMA.md)

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.

**Comment by afeld** [comment]
This hasn't been an active problem for the team, so closing.
