### ISSUE TITLE
Better align TTS Tech Portfolio positions with the NICE Workforce Framework

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#269]
## Background information

In order to be a more efficient team with cybersecurity responsibilities, it would benefit us from aligning with the NICE Workforce Framework. This is a proactive task, and not anything that is being asked of us externally, but a good practice within the government and since Cybersecurity is a function within our Portfolio and we've all been hired under the INFOSEC DHA. 

https://gsa-tts.slack.com/archives/DNYSYC0MU/p1579878197001200

## User stories

- As a a cybersecurity expert, I want my Position Description to align with the NICE Framework so that my CISSP Certification is covered

- As an employer, I would like to have the positions map to the NICE framework so that we can discover where there are gaps with responsibilities and roles or where employees are underutilized. 

- As an employee, I would like a way to visualize if I have the right knowledge, skill and ability to perform the job I'm assigned to do. 

## Implementation

- [ ] Use the [mapping tool ](https://niccs.us-cert.gov/workforce-development/mapping-tool) to get an initial outline
- [ ] Compare against each person's map against Position Description
- [ ] Align each person's position to Functions of the Portfolio
- [ ] Determine if there are any gaps
- [ ] Determine what needs to be changed

## Acceptance criteria

- Positions are mapped using the NICE Workforce Framework

**Comment by JJediny** [comment]
Tool for position assessment - https://niccs.us-cert.gov/workforce-development/mapping-tool/job-description#

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
