### ISSUE TITLE
As the Tech Portfolio, we want to know what third-party services are used in TTS

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#27]
- What software/infrastructure-as-a-service (SaaS/IaaS) and is TTS using?
- Who is using it / has a license?
- Who manages it?
- What does it cost?
- How much headroom do we have in terms of licenses, being under the micro-purchase limit, etc?
- Is there an associated Slack channel? - #16 

Very possible that a spreadsheet for this exists somewhere already. Sources for this information found already:

- [Onboarding/Offboarding Checklist for Infrastructure](https://docs.google.com/document/d/1m_syXUS_scIEz8W9go_EDnBTicx7y5ozEKHQAyNTLLI/edit)
- [Off-boarding tasks](https://docs.google.com/spreadsheets/d/1IlFY5AAvTyuS7yDHk5_odJGHYZDU_MN9HNGKJ2zXwi0/edit#gid=0)
- [Handbook](https://handbook.18f.gov/#software-and-tools)
- [A list in the Infrastructure Leads notes](https://docs.google.com/document/d/1G03trzrQez5BupOLfuZUJy-boooc1Z9oYj21LYTw4cs/edit?pli=1#heading=h.ctp5133ne1fm) - "SaaS services I was able to directly reference from various System Security Plans that have been ATOed but all of these solutions are in authorization limbo"
- [cloud.gov services](https://docs.google.com/document/d/1xZI6mTbJpXVG90rGL1LswgPf6YUN7FM2yBPhfPhRgw8/edit#heading=h.1a3ctkypw7m5)

**Comment by Karentrebon** [comment]
Aidan, here is the SaaS Search.gov uses: ZenDesk, Shared w/DAP, $792.90
EverBridge (GSA wide tool) $703.60
MaxMind $1,080.00
DataDog $540 per month or $6,480.00
Sauce Labs $19 per month or $228

**Comment by afeld** [comment]
Thanks! In case it wasn't clear: Let's create/use a canonical source, rather than collecting them here 😉

**Comment by afeld** [comment]
Going to use [this spreadsheet](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0), so remaining work is to go through all the info above and ensure it's reflected.

**Comment by mzia** [comment]
Please add ELK security pack (https://www.elastic.co/guide/en/x-pack/6.2/elasticsearch-security.html). Login.gov just acquired this.

**Comment by afeld** [comment]
Consolidated from all of the lists. Also [checking with TTS](https://gsa-tts.slack.com/archives/C04KL9ZN2/p1564415045054100) about some that may or may not still be in use - left them with `?`s in the meantime.
