### ISSUE TITLE
consider expanding Bug Bounty

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#273]
...to all of GSA, or as a government-wide offering. While the draft [Vulnerability Disclosure Policy requirement](https://cyber.dhs.gov/bod/20-01/) is explicitly "distinct from a 'bug bounty'," it's very possible that it will drive additional interest.

Agencies that have expressed interest that we should get back to after exploring it:

- DHS
- FEC
- US Tax Court via @waldoj @ominina 

## Implementation

- [x] Determine whether current contract could be leveraged for multiple agencies
- [x] Determine whether current contracts allows for segmenting by program (rather than a single public and a single private one)—[update from HackerOne](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1581451033021700)

**Comment by waldoj** [comment]
👏👏👏

**Comment by its-a-lisa** [comment]
@afeld would you mind grooming this card so we can move it to in-progress ahead of Monday's meeting?

**Comment by afeld** [comment]
Had good meeting going over the Bounty program with GSA Security—[notes](https://docs.google.com/document/d/19Ts5A13vBJWy0CgzCdFaCO8EGzWtt2y3_mFYYximrfs/edit). @JenniferCalik is going over the [contract materials](https://drive.google.com/drive/folders/14u7n8XfomTL_GAJX0p__VFHhQPl_jn5K) to understand the limitations.

**Comment by ominina** [comment]
awesome! @JenniferCalik 18F has a partner that is really interested in using GSAs bug bounty program, please keep me in the loop as you learn more

**Comment by its-a-lisa** [comment]
@JenniferCalik any update?

**Comment by ominina** [comment]
@JenniferCalik @its-a-lisa let me know if you all made any progress - our partners are still very interested in using the program.

**Comment by JenniferCalik** [comment]
Sorry all for the delay! @afeld, @its-a-lisa and I met today to discuss. Use of the contract for non-TTS-owned web applications would be outside of the current scope. Based on that information, we discussed strategies to overcome this, which @afeld is going to be looking into further.

**Comment by afeld** [comment]
To put it in plainer terms: we'd have to re-compete the contract to be able to offer to other agencies. Also, we just talked to CISA about them offering Vulnerability Disclosure (not necessarily a Bug Bounty) that covers other agencies, which may be of interest. Waiting to hear back from them about where we should draw the lines between the two. Anyway, closing this in the meantime.

**Comment by waldoj** [comment]
I sure appreciate y'all's work on this, Aidan.
