### ISSUE TITLE
brainstorm high-value work

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#275]
## Background information

There are various tasks that I believe could take some up-front (and maybe continued) investment to save the Tech Portfolio and/or TTS a lot of time/headache in the long run. Examples:

- The user management parts of https://github.com/18F/tts-tech-portfolio/issues/19, such as https://github.com/18F/tts-tech-portfolio/issues/179
- https://github.com/18F/tts-tech-portfolio/issues/188, by providing a quicker path to authorization for SaaS

Not sure whether it makes more sense to think about it from a perspective of "what work would be high-value?" (high return for relatively low effort) versus "what work would do best eliminating [toil](https://landing.google.com/sre/sre-book/chapters/eliminating-toil/)?"

## User stories

- As [everyone], I want to work smarter not harder
- As a member of the Tech Portfolio, I want to prioritize work that will save me from ongoing toil

## Implementation

- [ ] Schedule brainstorming session
- [ ] Take notes/pictures/etc of ideas
- [ ] Convert into issues
- [ ] Create a label?

## Acceptance criteria

- We spent X dedicated minutes thinking about our work from this angle
- Issues are filed that would be considered

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
