### ISSUE TITLE
help Federalist track down AWS resources

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#276]
## Background information

@amirbey is looking for the SQS queues:

- https://sqs.us-east-1.amazonaws.com/144433228153/federalist-builds
- https://sqs.us-east-1.amazonaws.com/144433228153/federalist-builds-staging

## User stories

- As a developer on the Federalist team, I want access to the underlying infrastructure so that I can troubleshoot the system

## Implementation

- [x] Confirm queues which AWS accounts the queues are present in (presumably 144433228153)
- [x] Grant @amirbey access to them

## Acceptance criteria

- @amirbey can see/modify the listed SQS queues

**Comment by amirbey** [comment]
@JJediny - the issue states that I was granted access. should I have received an email w/ account details? where I would I login to access this?
