### ISSUE TITLE
create Performance Plan criteria for Tech Portfolio - due 3/27

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#278]
## Background information

With https://github.com/18F/tts-tech-portfolio/issues/171, we are currently using Performance Plan criteria established TTS-wide, based on the GSA template. Solutions is also working on making Solutions-specific measures. [Asked about the status.](https://gsa-tts.slack.com/archives/C3F3HR717/p1577733367002500) We should think through what measures would make sense for the Tech Portfolio specifically, whether it builds on the Solutions ones or not. Also a possibility that we decide few/no Tech Portfolio-specific changes are needed.

While I am the person that needs to put it in HRLinks, it doesn't _need_ to be me that comes up with (at least a first draft of) the criteria.

## User stories

- As a member of the Tech Portfolio, I want to be evaluated on criteria that are relevant to my job, and that the expectations are clear and reasonable
- As the Supervisor of the Tech Portfolio, I want to know how to evaluate the team members

## Implementation

- [x] Come up with some "first principles" for evaluations based on [our responsibilities](https://handbook.18f.gov/tech-portfolio/) and how we work
- [x] Create copy of [template](https://docs.google.com/spreadsheets/d/1Sr4FIV8MSeNrqQYozfW-hV1QG2XrnMAYDeOwGkIk7_M/edit#gid=612468956)
- [x] Review [18F example](https://docs.google.com/document/d/1dxhtK-1THxcQHPBGdrUDGmUGo8Po65K9KL_c41WHgHQ/edit)
- [x] Create Tech Portfolio ("BU")-level measures - due 3/27
   - [x] Get feedback from team
- [x] Create Duty-specific measures - due 4/3
   - [x] Confirm [roles](https://github.com/18F/tts-tech-portfolio/blob/master/roles.md) are reflected
   - [x] Get feedback from team
- [x] Set percentages
- [x] Submit in HRLinks
- [x] Get acknowledgement

## Acceptance criteria

- Team all agrees that "I feel like the criteria I'm being evaluated against are clear"
- All members of the team understand what it would take to get a 5

**Comment by afeld** [comment]
[Deck explaining the process.](https://docs.google.com/presentation/d/1DN8sek5g17eDKi90WEStzFwhVccBqwVMl_yAScXwUjQ/edit)

**Comment by afeld** [comment]
[Work in progress.](https://docs.google.com/document/d/11wBxokRWBsl8Jxjo9OcFsFjEO43HP6juy6Z7_ZN30Gk/edit?usp=sharing) Not quite ready for comment yet.

**Comment by its-a-lisa** [comment]
@afeld I acknowledged in HRLinks today

**Comment by JJediny** [comment]
@afeld I acknowledged 2 days ago - looks good to close
