### ISSUE TITLE
consolidate Airtable accounts 

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#280]
## Background information

https://gsa-tts.slack.com/archives/CNW3GL70S/p1577993634104900?thread_ts=1577988432.100300&cid=CNW3GL70S

I'm probably going to use terminology below incorrectly since I haven't used Airtable before—feel free to correct as we learn more.

cc @melanienleopold https://github.com/18F/tts-tech-portfolio/issues/279

## User stories

- As an Airtable administrator, I want a single place/account to go to manage users and billing.

## Implementation

- [ ] Understand what Airtable accounts exist
- [ ] Understand how best to handle multi-tenancy in Airtable
- [ ] Combine disparate Airtable accounts into a single one

## Acceptance criteria

- The Tech Portfolio is able to see all TTS Airtable projects, users, and billing in one place.

**Comment by afeld** [comment]
Let's do https://github.com/18F/tts-tech-portfolio-private/issues/923 first to determine if we should bother worrying about this.

**Comment by its-a-lisa** [comment]
moving to blocked/waiting until we know the fate with AirTable

**Comment by afeld** [comment]
Sounds like this may not actually be possible without Enterprise.

- [ ] Get a sense of the Enterprise cost

**Comment by afeld** [comment]
Seems we might be able to consolidate folks into a single (or multiple) managed (maybe paid) Workspaces?

**Comment by its-a-lisa-at-work** [comment]
Set up meeting with the account rep that reached out to us, included @melanienleopold on the invite

**Comment by its-a-lisa-at-work** [comment]
Result of meeting today is that the solution is to upgrade to Enterprise accounts
