### ISSUE TITLE
Improve TTS Tech Portfolio Epics

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#284]
## Background information

Epics are a helpful way to organize your work and to create a hierarchy. The idea is to break work down into shippable pieces, so that large projects can actually get done and you can continue to ship value to your customers on a regular basis. Epics help teams break their work down, while continuing to work towards a bigger goal.
 Reference: [Agile Epics: Definition, Examples, & Templates](https://www.atlassian.com/agile/project-management/epics)

https://github.com/18F/tts-tech-portfolio/issues/282

## User stories

As a member of TTS Tech Portfolio, I want to improve the way we manage epics

As a member of TTS Tech Portfolio, I want Epics to be groomed to have enough detail with acceptance criteria and understand what the objective the epic is trying to solve is.

## Implementation

- [ ] Develop criteria/requirements/user stories for how each team member wants to utilize epics
- [x] Document what the relationship between Epics and the TTS Tech Portfolio roadmap
- [ ] Discuss medium for tracking Epics
  - [ ] On the project board vs Mural vs Word Doc
- [x] 'clean up epics' that currently exist

## Acceptance criteria

- All members have a clear understanding of the Epics and have had a chance to provide input into what they're looking to get out of epics
- Decisions based on medium used to track epics have been decided
- All Epics are groomed and in a workable state

**Comment by afeld** [comment]
I believe this is unblocked; moving to Backlog.

**Comment by afeld** [comment]
Covered this in a grooming meeting today—[notes](https://docs.google.com/document/d/1K7UFqVox8y9BThXsTjjtabha9MzFe7sX0E2ExKqTISo/edit).

**Comment by its-a-lisa** [comment]
I checked off the following items because it seems like those were completed with the last [goal meeting](https://github.com/18F/tts-tech-portfolio/issues/304)


- [x] Document what the relationship between Epics and the TTS Tech Portfolio roadmap
- [x] 'clean up epics' that currently exist

I don't believe we've either discussed or come to a consensus on the following items: 
- [ ] Develop criteria/requirements/user stories for how each team member wants to utilize epics
- [ ] Discuss medium for tracking Epics
  - [ ] On the project board vs Mural vs Word Doc

@afeld will these be addressed in your work with [revising the workflow](https://github.com/18F/tts-tech-portfolio/issues/356), should we add it to our next vision meeting, or set up a separate time to discuss?

**Comment by afeld** [comment]
Not sure yet; I'll get back to you.

**Comment by afeld** [comment]
Merging into https://github.com/18F/tts-tech-portfolio/issues/356.
