### ISSUE TITLE
OOO Leave instructions for TTS Tech Portfolio

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#288]
## Background information

https://github.com/18F/handbook/pull/1707

## User stories

- As a ..., I want ... so that ...
- As a ..., I want ... so that ...

## Implementation

- [ ] [first small task]
- [ ] [another small task]

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

**Comment by afeld** [comment]
[The leave page](https://handbook.18f.gov/leave/) seems to be TTS-wide—what's missing? Perhaps that's the first task?

**Comment by its-a-lisa** [comment]
Ahh, gotcha -- nothing really -- I think when I first saw the leave page being created it might have been done under an 18F specific repository? Or I'm going cuckoo ... 

I was thinking we'd have something like the below in our own TTS Tech Portfolio "How We Work" #248  for anything specific to our group; but I especially like the update slack OOO procedure

18F team members should also:
- Submit correct Tock entries
- Update your Slack username and profile (ex: @username | OOO until 7/12 | she)
- Create an event on the 18F Out of Office Calendar (TTS Ops uses it to support on-time Tocking)
- Decline, cancel, or reschedule any meetings you’ll miss
- Product chapter members: add an event to the All Things Product calendar.

**Comment by its-a-lisa** [comment]
Another good example to leverage/replicate is: https://cloud.gov/docs/ops/maintenance-list/

**Comment by its-a-lisa** [comment]
closing in favor of https://github.com/18F/tts-tech-portfolio/issues/248#issuecomment-588531426
