### ISSUE TITLE
Documentation editing workflow improvement - collaborative markdown editor

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#299]
As TTS improving and maintaining documentation on handbook.18f.gov and before-you-ship.18f.gov can be cumbersome. This issue is to track the need for a supplemental tool to improve the current workflow.

### Background
Google docs is not great for managing the conversion of markdown to and from github. There is an open source version of hackmd.io in https://github.com/hackmdio/codimd that has a proven deployment to cloud foundry (e.g. cloud.gov) by the UK government - https://github.com/alphagov/paas-codimd w. a concourse pipeline for it https://github.com/alphagov/paas-release-ci/blob/master/pipelines/plain_pipelines/paas-hackmd.yml.

There is an opportunity to use this to both improve the documentation editing workflow; as well as demonstrating the process of deploying a new and reusable application (with a marketable functionality that many other projects have a need for in real-time/collaborative editing of markdown). Additionally, it would provide us with the experience of conducting the required security documentation (ideally testing OSCAL during) for reusable app deployment on cloud.gov for added demonstration value.

**Comment by afeld** [comment]
> Google docs is not great for managing the conversion of markdown to and from github

If that problem were easier to solve than this one, would this one still be worth pursuing?

**Comment by JJediny** [comment]
<img width="399" alt="Screen Shot 2020-01-09 at 11 12 14 PM" src="https://user-images.githubusercontent.com/6350035/72125241-df3fb900-3335-11ea-8186-10a31930bfa0.png">

**Comment by afeld** [comment]
@JJediny to break out an issue from this one to create a proposal for it. I'm specifically interested in knowing more about the problem we're trying to solve, and what the other options for solving it are (with pros/cons).

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
