### ISSUE TITLE
As the Tech Portfolio, we want a safe way to keep shared passwords

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#30]
Examples:

- AWS root accounts
- Bot/admin accounts in GitHub, NPM, and Docker Hub

Where they are right now:

- Desktop software license keys doc
- KeePass files folder

We need a canonical place to keep these, so we don't have to scramble when onboarding/offboarding or doing incident response.

See also:

- https://handbook.18f.gov/password-requirements/#use-a-password-manager
- #19

**Comment by its-a-lisa** [comment]
This is complete, right?

**Comment by afeld** [comment]
KeePassXC + Drive File Stream works!
