### ISSUE TITLE
Azure admin training

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#300]
## Background information

Part of #162.

## User stories

- As an Azure admin, I want to understand how to organize tenants and manage the overall Azure account in a secure and fiscally responsible fashion.

## Implementation

- [x] Schedule training

## Acceptance criteria

- Meeting is scheduled
- [other definitive thing]

**Comment by afeld** [comment]
General Azure training got moved to 1/17, so asking about rescheduling for a virtual session the following week, if we think it's needed at all. Email subject `Azure Training`.

**Comment by its-a-lisa** [comment]
@afeld mind pointing me in the direction on how to sign up to this training in this issue? I think its gotten lost by other means.

**Comment by its-a-lisa** [comment]
Nevermind, I found it

https://gsa-tts.slack.com/archives/C029KQMBZ/p1578325087012700

**Comment by afeld** [comment]
Completed! [Notes.](https://docs.google.com/document/d/14lh8M1lYaI0jy1y9vDk3M2yQBQxNcr3nSGLXoz92cUE/edit)
