### ISSUE TITLE
provide Mission Essential Function information - due 1/7

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#307]
## Background information

From the `REMINDER: OMA Requirement for TTS MEFs Due Today` email:

> the following information is required by the GSA Office of Mission Assurance:
>
> Content to aid the Common Operating Picture (COP) Working Group MEF/ESA project (MEF stands for "Mission Essential Function.") The information is only needed for Cloud.gov, Login.gov, USA.gov website, and USA.gov Contact Center:
> 
> - MEF Responsibilities and/or products/services resulting from the MEF
> - Systems/software/websites needed to perform MEF
> - Essential records needed to perform MEF
> - Other GSA offices required to accomplish MEF, and a description of what that office does for the MEF

## User stories

- As a member of the COOP team, I want information from the MEFs to understand what is required in an emergency.
- As [everyone], I want MEFs to be available in case of emergency.

## Implementation

- [x] cloud.gov - [doc](https://docs.google.com/document/d/1WKXaHd9fFudRJwWiiabrI8-XiE7917MyDXebKtQLDEQ/edit)
- [x] login.gov - https://github.com/18F/identity-security-private/issues/1397
- [x] usa.gov - [doc](https://docs.google.com/document/d/1ZXAQ97eXoEhqePWumlQqTcJRloEZjcFUxQqMe5heOjw/edit)

## Acceptance criteria

- Answers to each section are provided to Marshall Brown

**Comment by its-a-lisa** [comment]
[Latest update from login.gov](https://gsa-tts.slack.com/archives/C3X5AJ8RK/p1582082146031400?thread_ts=1582041353.030600&cid=C3X5AJ8RK)
