### ISSUE TITLE
better track Sketch users

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#315]
- [ ] Adapt [Trello card](https://trello.com/c/cQuwBtzU/162-tts-tech-portfolio-access-to-jamf) to match this
- [ ] Update spreadsheet
- [ ] Get updated list of Sketch users from JAMF
- [ ] Determine if spreadsheet is needed going forward

**Comment by its-a-lisa** [comment]
Linking here for when grooming the card in case it might be relevant. 

https://gsa-tts.slack.com/archives/CNW3GL70S/p1581520717145200

**Comment by its-a-lisa-at-work** [comment]
@18F/tts-tech-portfolio do you think is still relevant now that we've begun the journey for mac admin removal? Or does that just make the step of getting the list of users from JAMF easier?

**Comment by its-a-lisa-at-work** [comment]
@afeld this is a good OpsRotation task that has nagged me and I'd be grateful if you could get to it!

Currently have an open question about how many licenses we have vs active and I have no clue and I'm blocked from accessing the site because I don't have access to 18f-software@gsa.gov

**Comment by afeld** [comment]
Hoping to tackle with #788.
