### ISSUE TITLE
Vulnerability Disclosure submission improvement

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#316]
## Background

Relate: #159 

## User stories
- As someone triaging/responding to vulnerability disclosures, I don't want to do so in multiple places.
- As someone submitting to vulnerability disclosures, I don't want to do so in multiple places.
## Actions to take:  
- [ ] Test out the submission forwarding email
- [ ] Change submission code snippet is a good idea
## Acceptance criteria: 
- [ ] Actions complete
## Supporting Documentation:
[HackerOne Email forwarding](https://docs.hackerone.com/programs/email-forwarding.html)
[HackerOne Embedded submission form](https://docs.hackerone.com/programs/embedded-submissions-form.html)
## Related Issues: 
cc #77

**Comment by its-a-lisa** [comment]
Based on conversation with our VDP, determined it isn't advantageous to do email forwarding and there is little return in investment -- much better to do the embedded form submission.

**Comment by its-a-lisa** [comment]
[related conversation](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1583867080010200)

**Comment by its-a-lisa-at-work** [comment]
This can stay the way it is now; doesn't seem to be a problem as is and can be taken care when https://github.com/18F/tts-tech-portfolio/issues/1224 happens
