### ISSUE TITLE
TTS programs undergoing FedRAMP assessment need to provide workstations to assessors

### ISSUE THREAD

**Issue by pburkholder** [18F/tts-tech-portfolio#318]
## Background information

The last couple of years cloud.gov has had some real headaches providing assessor pentest teams with properly configured workstations. Apparently there's no mechanism for providing loaner Macs, and most (all?) TTS teams use Macs. Also, we've had issues in the past when Macs and Windows that we provided were insecurely configured, unlike our actual GSA-managed systems.

## User stories

- As a TTS program compliance officer I want to meet FedRAMP pentest requirements in a consistent manner with minimal fuss
- As a TTS program compliance officer, I want to ensure the equipment provided is configured to the GSA enterprise standards as our day-to-day equipment.

## Implementation

Implementation  TBD

## Acceptance criteria

- [x] Process documented in [the Handbook's equipment page](https://handbook.tts.gsa.gov/equipment/#loaners)

attention: @sharms

**Comment by afeld** [comment]
@pburkholder Is this "done enough", or an outstanding/recurring problem?

**Comment by afeld** [comment]
Closing for now; will reopen if needed.

**Comment by pburkholder** [comment]
I have [notes on the process](https://docs.google.com/document/d/1wOSc0hHRiIMtxQNdvAnVjUcy8MtQkreO1Ka3fyWGlfw/edit#heading=h.xe4vi0pzll7s).  They were kept as I was working things out, so I'm not sure it's a repeatable process yet.

**Comment by afeld** [comment]
This has popped up again.

**Comment by josephderosales** [comment]
Instructions provided by GSA-IT:

1. Open a service now ticket requesting "GSA Hardware Request - Loaner".  
2. Provide rationale for request. "ProjectX.gov needs a GSA hardened with the latest approved MacOSX with TTS users permission for 3PAO penetration testing. This is part of an (annual) assessment for FedRAMP Low/Moderate/High FISMA A&A... "
3. Include the contact and shipping info of your 3PAO performing the test.
4. Provide a user name on the device example `3PAOtester01`.
5. Help desk will create a shipping label and mail out to the receiving party.

Although GSA-IT does not currently have a Mac Loaner Program, if there are any spares available, GSA-IT should be able to issue the loaner.

**Comment by afeld** [comment]
Thanks for digging in! Added acceptance criteria up top.

**Comment by pburkholder** [comment]
If  GSA IT doesn't come through, can TTS infra buy a Mac laptop for this purpose?  This is getting really expensive to re-invent every few months.

**Comment by josephderosales** [comment]
Updated Handbook - Pull request submitted https://github.com/18F/handbook/pull/2504

**Comment by afeld** [comment]
Thanks @josephderosales for documenting!
