### ISSUE TITLE
find pilot group for AWS Workspaces

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#320]
## Background information

Kris Rowley (GSA Chief Data Officer) is leading an effort to roll out AWS Workspaces for data science use, and perhaps more broadly. [Notes from initial presentation.](https://docs.google.com/document/d/1enmrfHXf6WduJuMTVhqglFITlx4jLBBXaHHoEHXjUTA/edit) He is looking to present more details and get feedback from 5-7 members of TTS, then possibly have them try it out as part of the next phase of their pilot. Further out, we are looking to see if it would be reasonable as a default place to do development tasks, as an alternative to having local administrator permissions.

## User stories

- As a data scientist / someone doing machine learning, I want access to powerful machines to run large/complex models.
- As a person responsible for Security at GSA, I want to control environments where development is done so that it's not as easy for malware to be installed.

## Implementation

- [ ] Get group of 5-7 who are interested in hearing more, and potentially being the first batch of TTS users
- [ ] Send list to Kris + Rose Lanzano

## Acceptance criteria

- They know who to reach out to for scheduling a presentation

**Comment by afeld** [comment]
@kishorebabu12 Is this still relevant?

**Comment by kishorebabu12** [comment]
@afeld This is not relevant anymore. We terminated all AWS workspaces instances as of last week.

**Comment by afeld** [comment]
Thanks for the reply!
