### ISSUE TITLE
Domain Renewal: Challenge.gov due 3/18

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#324]
Dear .GOV Contact,

This is a reminder that domain CHALLENGE.GOV for which you are listed as a billing point of contact, is due for renewal. 
Domain registration for CHALLENGE.GOV will expire on 03/18/2020.

 Please visit www.dotgov.gov to view and arrange for payment.

## Acceptance criteria
- [x] Pay for Domain Renewal for `CHALLENGE.GOV`
- [x] Pay for Domain Renewal for `CHALLENGES.GOV`

cc https://github.com/18F/tts-tech-portfolio/issues/38

**Comment by afeld** [comment]
Assuming this was done.
