### ISSUE TITLE
As the Tech Portfolio, I want to know the status of response to incidents

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#33]
[The Handbook lays out the steps for a security incident](https://handbook.18f.gov/security-incidents/), but as someone who isn't the respondent, I don't know where they are in that process. https://github.com/18F/security-incidents/pull/118 started to add an [issue template](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) - we should go further with it and make checkboxes for all of those steps.

While we're at it, we should also make sure that the documentation/steps still make sense.

**Comment by JJediny** [comment]
I know this exposes us to potentially taking on more work initially, but it might make more sense to start with a simple email address for `tts-ir` similar to `gsa-ir` until we formalize a ticket/issue procedure that we just asked to be cc-ed anytime gsa-ir is contacted. @afeld ? We can then start templating out how we setup issue tracking concurrently? KISS wise might be the best means to ensure awareness

**Comment by afeld** [comment]
We have one! tts-vulnerability-reports@gsa.gov See #60 for cleaning up our documentation/process around it and the other disclosure methods.

**Comment by afeld** [comment]
This issue is literally just "let's make a checklist."

**Comment by JJediny** [comment]
https://github.com/18F/security-incidents/pull/183

**Comment by its-a-lisa** [comment]
https://github.com/18F/security-incidents/blob/ahoang-issue-template/.github/ISSUE_TEMPLATE.md

Updated it
