### ISSUE TITLE
Perform a new test of Natural Language Processing (NLP) of TTS SSPs

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#335]
### User Story
As a new/existing/future TTS System Owner, I want to have examples of language for security controls, I want to know what is common vs what is unique, and most importantly I want to have a sample/example to work from. 

Furthermore, as the Tech Portfolio, I want to know which controls are common, which are of shared responsibility (and how are they similar), and which can be applied tts-wide as an abstraction. 

### Background
@afeld produced a great working example of taking a corpus of SSPs and parsing the controls into an NLP framework - https://github.com/uscensusbureau/fismatic. Little investment is needed to leverage this past work for newly accessible TTS SSPs.

### Acceptance
- [ ] fork to 18f
- [ ] add a step to the `analysis` python notebook to analyze comparative text from the same controls more in-depth. 
- [ ] add a step to list common nouns, that can help identify unique IaaS/PaaS/SaaS components being used in security control implementation.

**Comment by its-a-lisa** [comment]
@JJediny I was also thinking the other day and came up with a couple of ideas related to this ..

1. I would like to take typical CIO policy and acquisition policy, etc -- and bump it against the NIST 800-53 control set to determine if there is any policy that is written, that unkowningly helps satisfies any controls. Think this also relates to #152 

2. Look into Augmented Writing for SSPs I came across textio.com the other day and thought that is more in line for what we're trying to get at and I agree w/ [the comment ](https://github.com/18F/Security-Compliance/issues/1#issuecomment-575841562) that there is a risk of people just copying boiler plate when presented with examples, so would like to avoid that as much as possible.

**Comment by its-a-lisa** [comment]
great example from today's discussion: https://gsa-tts.slack.com/archives/CG8SNAEQM/p1582733874030300?thread_ts=1582726571.023700&cid=CG8SNAEQM

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.

**Comment by ryanwoldatwork** [comment]
Very interesting concept.
