### ISSUE TITLE
Document use cases for Docusign workflows

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#340]
## User Story
Docusign is available to TTS, there are multiple workflows that require pdf forms and signatures. This issue is to gather those instances and evaluate whether to setup DocuSign reusable templates for them.

## Acceptance Criteria
- [ ] Document a list of workflows whether DocuSign can be leveraged (scoped to the tech portfolio).
- [ ] Publish those as standard forms for others to search and reuse.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
