### ISSUE TITLE
help prep for Hill testimony around 18F and CoEs - due 2/12

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#353]
## Background information

@cbrydges asked for input on some [security/compliance questions](https://docs.google.com/document/d/1MM6lSPCzFbih_uGmPbGUGcU7IlCEutzlfJftbWNDrQs/edit?disco=AAAAJHOYePI).

## User stories

- As a person giving testimony around the security/compliance of our organization, I want to ensure I fully understand the current state.
- As a person responsible for the security/compliance of our organization, I want to ensure the current state is well represented.

## Implementation

- [x] Help fill in the relevant questions
- [x] Send to Security for feedback
- [x] Send to CTO's office for feedback
- [x] Notify @cbrydges 

## Acceptance criteria

- Questions have answers that @cbrydges feels are clear

**Comment by afeld** [comment]
@its-a-lisa did a first pass, I did a second pass. @its-a-lisa Mind taking a look at my suggested edits?

**Comment by its-a-lisa** [comment]
Resolved suggested edits; provided a clarification, and also another comment.

**Comment by afeld** [comment]
Still working on refining.

**Comment by its-a-lisa** [comment]
So sorry!! hit the wrong button and didn't realize I closed it.

**Comment by afeld** [comment]
Just sent to @cbrydges:

> Sent to Security for a look from them (should have thought to do so sooner) and have an open question in there for the CTO's office, but barring any feedback from them, we are done with questions 1, 2, 3, and 7.

Will incorporate anything that comes in from them, but otherwise, considering this done.
