### ISSUE TITLE
review Coding it Forward candidates - due 2/25

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#354]
## Background information

_Do not put any names in this issue._

See email `Fwd: CDF Candidate Referrals - 30 - TTS Tech Portfolio`.

## User stories

- As a member of Talent, I want candidates to be reviewed by the teams they will be working in so that the candidates are a good fit.
- As a member of the Tech Portfolio, I want to review the candidates so that I can get the candidate whose skills and interests are best-suited to the team.
- As a potential Coding it Forward Fellow, I want to understand and be excited about the team I'm joining.

### Money

- [x] Find out the cost
- [x] Confirm budget with Finance

### Candidates

- [x] Resumes reviewed
- [x] Candidates contacted
- [x] Interviews scheduled
- [x] [Candidate preferences filled in](https://docs.google.com/spreadsheets/d/1tEam7iKT0Kcw8RkNokIulAjsNyhTafRn4SvbvE0Wl-s/edit#gid=706457659)
- [x] @JennMoran knows it's complete

## Acceptance criteria

- Preferences filled in in the spreadsheet

**Comment by afeld** [comment]
Started a [tracking sheet](https://docs.google.com/spreadsheets/d/1gfsc9PQ6Vv_vqFG9nxjHDAQVXOkgVDk4F-Z_574zFXE/edit#gid=0).

**Comment by its-a-lisa** [comment]
Thanks, I filled out my section.

Question

1. Is the 2/25 due date the date for the whole task? Is that a hard deadline or suggested deadline? 
1. I volunteered to do the contacting activity in our standup yesterday; just to clarify, I will be contacting the actual candidates to set up the interviews once our whole team has filled in the preference, correct?

**Comment by afeld** [comment]
> Is the 2/25 due date the date for the whole task?

Yep.

> Is that a hard deadline or suggested deadline?

It's the date Coding it Forward asked us to get back to them. We should try and meet it, but probably not the end of the world if we need a little longer.

> contacting the actual candidates to set up the interviews once our whole team has filled in the preference, correct?

Yes please!

**Comment by its-a-lisa** [comment]
Called candidates; moving into `Waiting/Blocked` until I hear from them to schedule.

**Comment by its-a-lisa** [comment]
All done!
