### ISSUE TITLE
revise workflow

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#356]
## Background information

See:

- Linked issues below
- [Notes](https://docs.google.com/document/d/1VbsGTQS9ji-snE8CibF1hFEL00eF02_l6QVnYHfGvCc/edit) from team conversation with @awichman 

## User stories

- As a member of the Tech Portfolio, I want a workflow that is clear to me and that allows me to work effectively.

## Implementation

- [x] Draft a revision to [the documentation](https://github.com/18F/tts-tech-portfolio/blob/master/ProjectBoard.md)
- [x] Get 👍 from team (no major concerns, and clarification questions addressed)
- [x] Update documentation - https://github.com/18F/tts-tech-portfolio/pull/410
- [ ] Update columns
- [x] Update calendar invites to match updated Ceremonies
- [ ] Change Epics issues/column to be Domains
- [ ] Remove labels that haven’t been getting used [consistently]
   - [ ] `grooming: team`
   - [ ] `size: …`
- [ ] Switch `epic:` labels to `domain:`

## Acceptance criteria

- Team [consensus](https://theprimes.com/consensus) on the updated workflow procedures

**Comment by afeld** [comment]
[Drafted.](https://docs.google.com/document/d/10H5iTwkb50AkdMK9k_4kx3EbNtMdyG7-TjE_MJSTfCc/edit) [Passed along to the team](https://gsa-tts.slack.com/archives/CNW3GL70S/p1584471920244400) on 3/17, and waiting until the morning of the 20th to finalize.

**Comment by its-a-lisa** [comment]
@afeld #284 was closed to and to be merged in with this, but I'm not seeing the left over items from that card

- [ ] Develop criteria/requirements/user stories for how each team member wants to utilize epics
- [ ] Discuss medium for tracking Epics
  - [ ] On the project board vs Mural vs Word Doc

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
