### ISSUE TITLE
prep for 18F Team Coffee - due 3/6

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#359]
## Background information	

[Original request](https://gsa-tts.slack.com/archives/C0XUF8XL1/p1582044770090400):

> tell us about the tech portfolio now that it’s had some time to find its feet. It would be helpful to know what they’re doing, what their role is within the organization, what decisions fall to them, etc.

We can move to a later date if we need. Past presentations we can pull from:

- [AMA](https://docs.google.com/presentation/d/1RhIEoLAAbSPNSgNboTfqBrMTQD0E5AbPlegI_MQ5n_0/edit#slide=id.p)
- [All Sol - All Hands Recap](https://docs.google.com/presentation/d/1bXc_eKroQMfm32XTtrIun_-4pnwde9Winm2JV9pd97U/edit#slide=id.g6228a59143_0_0)
- [18F IRL](https://docs.google.com/presentation/d/1m47592Ga75ykhApA1GW-sqwqzAVKCHZaaS_U_GPfTYc/edit#slide=id.p) *Note: never actually presented and just talked

## User stories	

	

- As a member of 18F, I want to understand what the Tech Portfolio is up to to know what I should go to them for, what things I should look forward to, etc.
- As a member of the Tech Portfolio, I want other parts of the org to understand what we're up to, how we do/can support them, etc. so that they know what to come to us for, and to maintain a positive relationship.

## Implementation	

- [x] Get scheduled
- [x] Prepare a deck
- [x] Present

## Acceptance criteria	

- Presented

**Comment by abrouilette** [comment]
We still on for y'all to do ten minutes this Friday?

**Comment by abrouilette** [comment]
@afeld @its-a-lisa @JJediny , 👀 ⬆️ please.

**Comment by afeld** [comment]
Sorry, yes, we will be there!

**Comment by afeld** [comment]
[Slides](https://docs.google.com/presentation/d/1NigIXx3EJIsepR6ktxCAMWfTuBNxh70xsrgpKygM6kA/edit)

**Comment by afeld** [comment]
Done! [Some great kudos.](https://gsa-tts.slack.com/archives/C063B2GTW/p1583525526060800)
