### ISSUE TITLE
New Relic - Setup SIMPLE synthetics monitor/dashboard/alert method for any TTS Domains

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#363]
## User story
As the TTS tech portfolio, we want to set up basic monitoring for all of our public urls. As a TTS System owner I want to have (atleast) basic insight into my cumulative uptime/downtime monitoring (dashboard) and be alerted for outages.

## Background
New Relic Synthetics provides a no-cost tier for a basic ping service to test if a TTS domain endpoint is reachable and returns 200. Uptrends may not be available, there are currently no approved alternatives for ping/uptime metrics monitoring.

## Acceptance Criteria
- [x] Test a sample SIMPLE synthetics check
- [x] Test a sample synthetics dashboard
- [x] Test a sample synthetics alert
   - [x] email `wont fix`
   - [x] slack

Related to https://github.com/18F/tts-tech-portfolio-private/issues/927

**Comment by afeld** [comment]
Duplicate of https://github.com/18F/tts-tech-portfolio/issues/66? If so, want to close one?

**Comment by afeld** [comment]
@JJediny Do you have the latest pushed up somewhere?

**Comment by JJediny** [comment]
https://github.com/18F/newrelic-terraform/

**Comment by its-a-lisa-at-work** [comment]
@JJediny are these issues required to be completed before closing this issue? https://github.com/18F/newrelic-terraform/issues

Should those be on our TTS Project Board as well; is this a repo that is going to stick around for a while that we should [clarify what repositories we manage #625](https://github.com/18F/tts-tech-portfolio/issues/625)

**Comment by JJediny** [comment]
Remaining work move to its own issue https://github.com/18F/tts-tech-portfolio/issues/631

**Comment by JJediny** [comment]
> @JJediny are these issues required to be completed before closing this issue? https://github.com/18F/newrelic-terraform/issues
> 
> Should those be on our TTS Project Board as well; is this a repo that is going to stick around for a while that we should [clarify what repositories we manage #625](https://github.com/18F/tts-tech-portfolio/issues/625)

closed these issues out - moving forward will maintain all issues at the tech portfolio repo
