### ISSUE TITLE
deal with bug bounty open issues

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#37]
Appears there are a handful of [open issues](https://hackerone.com/bugs?subject=tts&report_id=0&view=custom&substates%5B%5D=new&substates%5B%5D=needs-more-info&substates%5B%5D=triaged&reported_to_team=&text_query=&program_states%5B%5D=2&program_states%5B%5D=3&program_states%5B%5D=4&program_states%5B%5D=5&sort_type=latest_activity&sort_direction=descending&limit=25&page=1) that someone needs to check the status on.

**Comment by afeld** [comment]
[Weekly summary from HackerOne](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1563572576017100)

**Comment by rahearn** [comment]
Asked calc team for follow up on 365524 and 438139, and have asked Dawn to verify some search.gov issues. All other issues resolved, disclosed, or moving along with their teams.
