### ISSUE TITLE
Prioritize a list of automation actions - using Github Actions or Circleci

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#376]
## User Story
Automate least value-added work

## Implementation

1. [Github Actions](https://github.com/marketplace?utf8=%E2%9C%93&type=actions)
1. [CircleCi orbs](https://circleci.com/orbs/registry/)
1. ~Docker containers - static scans, report/artifact uploads, etc

- https://github.com/marketplace/actions/scan-with-sonar-scanner

#### Infrastructure Management
1. IaaS resource/user/budget auditing
1. Terraform automation - AWS/Github/New Relic/etc deployments

- https://github.com/marketplace?utf8=%E2%9C%93&query=terraform
- https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
- https://github.com/marketplace/actions/aws-assume-role-github-actions
- https://github.com/marketplace/actions/aws-secrets-manager-actions
- https://github.com/marketplace/actions/aws-assume-role
- https://github.com/marketplace/actions/google-cloud-platform-gcp-cli-gcloud
- https://github.com/marketplace?utf8=%E2%9C%93&type=actions&query=azure

#### Git Workflow
1. Create a list of recent stars/forks for 18f members (to feed tech radar work)
1. Slack alert Due Dates - https://github.com/marketplace/actions/github-issue-due-dates-action
1. Pull Request Review/Approvals

- https://github.com/marketplace/actions/github-script
- https://github.com/marketplace/actions/github-project-automation
- https://github.com/marketplace/actions/github-api-exec-action
- https://github.com/marketplace/actions/open-github-issue
- https://github.com/marketplace/actions/deploy-github-actions
- https://github.com/marketplace/actions/github-environment-variables-action
- https://github.com/marketplace/actions/automate-projects
- https://github.com/marketplace/actions/automatic-pull-request-review
- https://github.com/marketplace/actions/github-graphql-api-query
- https://github.com/marketplace/actions/github-api-request

#### Security (IR/CM)
- https://github.com/marketplace?utf8=%E2%9C%93&category=security&type=actions&query=
- https://github.com/marketplace?category=monitoring&type=actions
- https://github.com/marketplace?category=testing&type=actions

#### Serverless/Cloud.gov/Ping/Webhook triggers
- https://github.com/marketplace/actions/github-action-for-serverless-framework
- https://github.com/marketplace/actions/ping-url

## Acceptance Criteria
- [ ] Exhaust ideation
- [ ] Present/feedback from TTS users
- [ ] Create new issues for all with agreement to implement

**Comment by its-a-lisa** [comment]
Deleting as stale based on the TTS Tech Portfolio Deep Grooming session from 3/30/20; if you have any questions, comments or concerns, please let us know either in the #infrastructure or #tts-tech-portfolio slack channels
