### ISSUE TITLE
prep for Hill testimony, round II - due ASAP

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#377]
## Background information	

Follow-up to https://github.com/18F/tts-tech-portfolio/issues/353. Main questions:

- How many new software purchases did we make in FY19+20?
- Did/do all of them have an ATO?

## User stories	

- As a person giving testimony around the security/compliance of our organization, I want to ensure I fully understand the current state.
- As a person responsible for the security/compliance of our organization, I want to ensure the current state is well represented.

## Implementation	

- [x] Request help from Acquisition/Finance
- [x] Provide answers to @cbrydges 

## Acceptance criteria	

- Answers provided that we feel are accurate

**Comment by its-a-lisa** [comment]
Per the question: "Did/do all of them have ATOs at time of purchase, per the s[lack conversation](https://gsa-tts.slack.com/archives/CD4F3TGB1/p1582759321017600?thread_ts=1582641762.000500&cid=CD4F3TGB1), I've updated our [TTS Software and Systems Inventory](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0) to have an initial authorization date (Column P) and an initial purchase date (Column Q) and put it in a [specialized filter view](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0&fvid=1996350041) . 

TechSmith Camtasia
CircleCI
MaxMind
HubSpot
Opsgenie
AirTable
Asana

But, I will point out, I don't believe the current GSA policy requires an ATO at time of purchase, just that there needs to be an ATO before the product is used.

**Comment by cbrydges** [comment]
With regard to timing - I just want to know it received an ATO per the GSA IT process. If that is not at purchase but prior to use that is fine. With that said - were you able to find out if the 16 in FY19 and the xxx in FY20 followed the approved ATO process and were giving ATOs as applicable? 
Thank you.

**Comment by afeld** [comment]
[Done!](https://gsa-tts.slack.com/archives/CD4F3TGB1/p1583181686024100?thread_ts=1582641762.000500&cid=CD4F3TGB1)
