### ISSUE TITLE
support edge cases when working with Office files

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#378]
## Background information	

https://trello.com/c/euId5KRX/164-determine-the-future-of-office-files-on-macs

## User stories	

_See Trello card for some use cases._ 

## Implementation	

_See checklist in Trello card._

## Acceptance criteria	

- TTS (if not all GSA Mac) users have a desktop option for Office files

**Comment by its-a-lisa** [comment]
moving to waiting/backlog until get survey results back

**Comment by afeld** [comment]
Calling this "as done as we can be for now."
