### ISSUE TITLE
clean up Office 2016 licenses

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#379]
## Background information	

https://trello.com/c/oi3qhS0V/193-revoke-old-office-for-mac-2016-licenses

## User stories	

- As someone managing Macs/software, I don't want TTS licenses to be allocated to people who are no longer using them.

## Implementation	

_See Trello card._

## Acceptance criteria	

- Office license count is under 100, or as low as we can reasonably get it

**Comment by its-a-lisa** [comment]
@afeld picking this card up too; since the MS Office licenses are so expensive, need a better understanding of our current count that we'll need

**Comment by its-a-lisa** [comment]
All done!

**Comment by afeld** [comment]
Yay, thank you! What is our current count?

**Comment by its-a-lisa** [comment]
149
