### ISSUE TITLE
Consolidate and Reorganize TTS Tech Portfolio Google Drive Folders

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#382]
## User story
As the TTS Tech Portfolio, we want a shared team drive to store our collective docs and work products and to share all that we can with other members of TTS for organization awareness/benefit.

## Background
Right now we have two google drive folders:
1. General Drive Folder (type) - this folder is not openly searchable to GSA, but link sharing is allowed this means we can share any folder or file with the content viewable (edit/comment can be granted separately) - https://drive.google.com/drive/folders/1J9-JDqgl6OpVwQZemzcGbEGZCJ8Nmene
2. Team Drive Folder (type) - this folder is only shared with the 3 of us (can't be shared linked to read-only / has to be granted any level of access, contains procurement sensitive files)- https://drive.google.com/drive/folders/0AK0cBcPVg19cUk9PVA

## Acceptance Criteria
- [x] Determine folder structure methodology/taxonomy for the team generally
- [x] Move all files/folder to Team drive folder
- [x] Create a new private team drive for procurement sensitive docs.
- [x] Grant tts@gsa.gov commenter rights on team drive
- [ ] Deprecate General Drive Folder 1

**Comment by its-a-lisa** [comment]
@JJediny seems like we've done most of this except the last item to depricate; not sure what you mean about `General Drive Folder 1` -- would you mind looking into that item and check if it is done so we can close this card?

**Comment by its-a-lisa-at-work** [comment]
Assuming this has been done and closing this item
