### ISSUE TITLE
TTS Tech Portfolio: The Eisenhower Box (Due date: 3/16)

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#383]
## Background information	

During a conversation about workflow, a conversation bout prioritization came up. I had mentioned the [1-2-3 method I had seen before](https://medium.com/@arriane/the-simple-technique-to-make-you-more-productive-with-a-shorter-to-do-list-the-1-2-3-method-9c0e2919cee2) and realized that article mentioned the *Eisenhower Box* which I've also come across during my search for project management. 

On several occasions, various people on the team have [expressed a desire to close unnecessary issues](https://gsa-tts.slack.com/archives/CNW3GL70S/p1582742671042600)

## User stories	

As someone in the TTS Tech Portfolio that has to use our board, I want to know what is important and urgent in a visual manner so I can know what items need to be deleted or delegated. This will solve the problem of having too many issues on the board that overload the cognitive load and do so in a way that enables everyone on the team to provide their own individual opinion on what should be cut, while seeing in what areas we agree and which areas we disagree. 

## Implementation	

- [x] Alyssa writes instructions on how to use to fill out our [TTS Eisenhower Instructions](https://app.mural.co/t/gsa6/m/gsa6/1582753937160/fcf2b779870d63cfdc42802c65e4b5fa54e96d76)	...[ Instructions below](https://docs.google.com/spreadsheets/d/1QUJ0rdGIPdUnR7N5xNdRPkpcQwZdzb_IK9X-f-_kckU/edit#gid=1389857607)
- [x] Get all the issues on the ~board~ [sheet](https://docs.google.com/spreadsheets/d/1QUJ0rdGIPdUnR7N5xNdRPkpcQwZdzb_IK9X-f-_kckU/edit#gid=1389857607)
~- [ ] Get consensus if we plan on having all issues on all the boards we own to be on our project board, or if we plan on having some not on our project board~
- [x] Once instructions are complete and accepted, we set a due date for all TTS Tech Portfolio members to complete 
- [x] Completed by all Tech Portfolio members
- [x] Confirm issues we have consensus on
- [x] Revise votes for issues we have one outlier on
- [ ] Make decisions on remaining issues

## Acceptance criteria	

- Everyone in TTS Tech Portfolio know what to do
- Everyone in TTS Tech Portfolio has completed their section
- We take the completed sections and compare at a planning session

**Comment by its-a-lisa** [comment]
Ok, so I've changed directions a little bit and scrapped the Mural (for now, and I'm not done on my quest to integrate it more into our work) ... but realized that this type of activity is probably done better using Google Sheets. So, I started a [sheet](https://docs.google.com/spreadsheets/d/1QUJ0rdGIPdUnR7N5xNdRPkpcQwZdzb_IK9X-f-_kckU/edit#gid=1389857607) that is ready to be filled in. 

Instructions:

1. For each task, indicate Y or N for the Urgent and Important columns
1. Once you have done that, comment here in this thread and we'll figure out next steps. 

In the meantime, I am going to work towards teaching myself Sheets so that the following logic exists: 
U=Y, I=Y : Do
U=N, I=Y : Decide
U=Y, I=N : Delegate
U=N, I=N : Delete

(if ya'll finish filling it in before I've taught myself, I might need one of you to help me so we don't hold up the task, but in the mean time I'm going to do some OJT and learn through it)

What happens after we've filled it in individually will have to be broken out into three sections (1) agree on the easy items (2) come to consensus (3) decide on the path forward with what we've come up with. These activities can happen in parallel; I suggest we start with first discuss what we all agree about to Do & Delete. Once we've done that, come to a consensus and then focus on the items that need to be delegated and decided.

**Comment by its-a-lisa** [comment]
found this the most helpful graphic https://www.the1thing.com/wp-content/uploads/2017/05/May-25-Eisenhower-Matrix.png

**Comment by afeld** [comment]
@its-a-lisa Mind updating the checklist above, when you get a moment?

**Comment by its-a-lisa** [comment]
Based on yesterday's standup, we decided that we are not going to go forward with this project and instead to storm drain, we're going to close any task that does not relate to one of the current major initiatives based on the [Sprint Planning](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit)
