### ISSUE TITLE
Create a semi-automated google sheet for SaaS/License account auditing/cleanup

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#384]
## User story
As the TTS Tech Portfolio, we have a larger goal of better management of Authentication/Authorization:
- https://github.com/18F/tts-tech-portfolio/issues/19
- https://github.com/18F/tts-tech-portfolio/issues/179

However until we have a better-integrated solution, we still deal with SaaS/License management onboarding and offboarding. There is a need for a better interim solution

## Background
- Microsoft office 2016 - https://github.com/18F/tts-tech-portfolio/issues/379
- dotgov.gov - https://github.com/18F/tts-tech-portfolio/issues/358
- mural.ly - https://github.com/18F/tts-tech-portfolio/issues/317
- sketch - https://github.com/18F/tts-tech-portfolio/issues/315
- airtable - https://github.com/18F/tts-tech-portfolio/issues/280
others with no specific issue to track: 
- omnigraffle
- trello - 
- github
- invision

## Acceptance Criteria

- [x] Create a spreadsheet with **repeatable** API or CSV export instructions for each SaaS/License service.
- [x] Perform a raw export of each service to its own tab (do not modify output/lock tab)
- [x] Assess the ability to cross-reference export(s) to HR Links employee status (by email)
- [x] Find `no matches` and perform an initial cleanup.
- [ ] Assess if there is a ~usage metric that could be used as a proxy for a user no longer needing access.

**Comment by afeld** [comment]
Started one [here](https://docs.google.com/spreadsheets/d/16K3QEUdaXhSjeP-2vVGOX9PulRhlKqXXLnrx_RAZFJc/edit#gid=1913829200).

**Comment by afeld** [comment]
Now that the base spreadsheet is created, we should break this issue up by service, since the considerations for each are slightly different.

**Comment by its-a-lisa-at-work** [comment]
Calling this 'done enough'
