### ISSUE TITLE
update team documentation based on conversation with Ashley

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#388]
## Background information	

_Besides_ the workflow (which has its own issue: https://github.com/18F/tts-tech-portfolio/issues/356), we identified a number of adjustments that need to be made to [our Handbook page](https://handbook.tts.gsa.gov/tech-portfolio/) and the Markdown files in this repository.

cc @awichman 

## User stories	

- As a member of the Tech Portfolio, I want our documentation to clearly and accurately reflect us, both to ourselves and others, so that there isn't confusion about scope/mission/etc.

## Implementation	

- [ ] Identify parts of the [notes](https://docs.google.com/document/d/1VbsGTQS9ji-snE8CibF1hFEL00eF02_l6QVnYHfGvCc/edit) where there was agreement on what needs to be changed
- [ ] Update/create relevant documentation
- [ ] Create new issues or comment on existing ones for areas where there are open questions

## Acceptance criteria	

- All "evergreen" content from the meeting with Ashley has been moved to documentation or issues

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
