### ISSUE TITLE
Mural over limit

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#392]
## User story

As a TTS member, I might want to get added to use Mural but it is currently at limit. 

## Background

![image](https://user-images.githubusercontent.com/31391902/76170997-7ae67d80-615d-11ea-8ea6-d9fee3d7576c.png)

## Acceptance Criteria

- [ ] This gets taken care

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/395.
