### ISSUE TITLE
prep slides for FAS OPC - due 3/12

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#398]
## Background information	

From Greg Rollins:

> FAS OPC Hosts a Monthly call targeting the FAS Acquisition Operations Directors (Monthly FAS OPC/AO Interface Call) every month. ... One of the things we have been trying to do this FY is target an "acquisition best practice" conversation in every meeting.  5-10 minutes on something that is being done in the real world and achieving positive results, with an eye to applicability by the acquisition community.  I thought an abbreviated version of the presentation you gave to last months FSGC could be a good fit (with a few adjustments) and wanted to reach out and see if you'd be willing to present at an upcoming meeting.

I'll have 10 minutes to present on 3/25.

## User stories	

- As a FAS Acquisition Operations Director, I want to ensure that FAS is delivering value from our technology investments quickly.
- As a member of TTS, I want other parts of FAS to understand our expertise around use of agile budgeting to get more business/influence.

## Implementation	

- [x] Create [copy of slides](https://docs.google.com/presentation/d/1IUgK5yUpQZBIoJYqppn2g3xAwW2u-nkr1VxNaycqN1k/edit)
- [x] Get tips about how to adjust for an acquisitions audience
- [x] Adjust slides
- [x] Send to Andrea Burow

## Acceptance criteria	

- Slide deck is ready for presentation

**Comment by michellepetryszyn** [comment]
Slides look really great. Just added one thing on slide 21 re: our acq procurement authority

**Comment by afeld** [comment]
Appreciate it! Cut down the number of slides to fit in the time, though it's still going to be tight.

**Comment by afeld** [comment]
Got pushed to an undetermined future meeting due to coronavirus response.
