### ISSUE TITLE
review Coding it Forward candidates, round II - due 3/13

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#401]
## Background information	

_Do not put any names in this issue._

Follow-up to https://github.com/18F/tts-tech-portfolio/issues/354 with additional candidates. See email `Fwd: Additional CDF Candidates for Project 30 - TTS Outreach`.

## User stories

See https://github.com/18F/tts-tech-portfolio/issues/354.

## Implementation

- [x] Resumes reviewed
- [x] Candidates contacted - due 3/12
   - [x] @AnnabelLombard notified
- [x] Interviews scheduled
- [x] [Fill in tracking sheet](https://docs.google.com/spreadsheets/d/1gfsc9PQ6Vv_vqFG9nxjHDAQVXOkgVDk4F-Z_574zFXE/edit#gid=0)
- [x] Let @AnnabelLombard know the results

## Acceptance criteria

- @AnnabelLombard is aware of candidates we want to move forward with

**Comment by its-a-lisa** [comment]
Done!
