### ISSUE TITLE
complete Website Modernization Plans - due 4/15

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#404]
## Background information	

[Website Modernization Planning for Site Owners](https://docs.google.com/presentation/d/1XnPKfTYgG3HQ4D7sJivnYmPfvteiXgWBsj_eauQZLXo/edit) deck explaining the background and process. Templates:

- [Website Cost Estimator](https://docs.google.com/spreadsheets/d/1jgk46fryuZjhjBoxudujAD6YyaEbE-ZytlHGrslkTpk/edit#gid=1348750722)
- [Website Modernization Plan Worksheet](https://docs.google.com/spreadsheets/d/1gvHxd8RHLiS3vKhbfPx87AreUfLyVqt1e_rKTcwom1A/edit?usp=sharing)

## User stories	

- As someone thinking about web content strategy for GSA, I want to understand the landscape so I can make informed decisions.

## Implementation
   - [ ]  Complete Website Modernization Plan Worksheet
       - [x] [Handbook](https://docs.google.com/spreadsheets/d/1siEkrfn2Jt19hAO3R-gkMGLg0jckr0ftoVkd8xABKgk/edit#gid=1163132370)
       - [x] [Before You Ship](https://docs.google.com/spreadsheets/d/1hk8TZuX_siUqrUXPZBoHWFUuZVFynaJuTtM23RpiRT8/edit#gid=1163132370)
       - [x] [TTS Jobs ](https://docs.google.com/spreadsheets/d/1St95RHP8fP0xfjU17oQybpmq2tDzM5ozS1StKjmm1bw/edit#gid=1163132370)
   - [ ] Complete Website Cost Estimator
       - [x] [Handbook](https://docs.google.com/spreadsheets/d/17sUt8BNJOow7aITNsCyzL-1IxyDrIBLGSHUFXojb1Bk/edit#gid=1348750722)
       - [x] [Before You Ship](https://docs.google.com/spreadsheets/d/1CcqF46Xa6PpJMbi6DZVUGl95cb4305PMbBvD5NJAlNo/edit#gid=1348750722)
       - [x] [TTS Jobs](https://docs.google.com/spreadsheets/d/1qP895LrtB5x4nDBqZh2RegfzBvJmAXpHyYRGnIxEHO4/edit#gid=1979927954)
   - [x] Send to Natalie

## Acceptance criteria	

- Sheets are filled in for all the sites we're the (technical) owners of

**Comment by afeld** [comment]
Deadline extended to 4/15. That said, the Digital Council would love an example to point to, so let's see if we can get at least one done in the next week or so.

**Comment by its-a-lisa** [comment]
@afeld did you recently put in a microrequest for a designer for the Handbook?

**Comment by afeld** [comment]
Content design specifically, yep: https://github.com/18F/handbook/issues/1897

**Comment by its-a-lisa** [comment]
@afeld should we bother taking a stab at the FY that this will be completed at this point, or wait until we go back and get more solid money estimates?

**Comment by its-a-lisa** [comment]
Moving this to Waiting/Blocked for the following reasons:

- [ ] Need feedback from @afeld (or someone who he can direct me to) about the sites redirection for [Handbook](https://docs.google.com/spreadsheets/d/1siEkrfn2Jt19hAO3R-gkMGLg0jckr0ftoVkd8xABKgk/edit?disco=AAAAJPrsseM) and Handbook
- [ ] [question](https://github.com/18F/tts-tech-portfolio/issues/404#issuecomment-607301496) asking in #Digital-Council slack channel
- [ ] Waiting for the Talent team to look over the [ TTS Jobs Modernization Plan Worksheet](https://docs.google.com/spreadsheets/d/1St95RHP8fP0xfjU17oQybpmq2tDzM5ozS1StKjmm1bw/edit#gid=1163132370) and [TTS Jobs Cost Estimator](https://docs.google.com/spreadsheets/d/1qP895LrtB5x4nDBqZh2RegfzBvJmAXpHyYRGnIxEHO4/edit#gid=1979927954)
   - Plan to ping on 4/2 to get a progress update

**Comment by its-a-lisa** [comment]
Just sent to Natalie
