### ISSUE TITLE
determine distribution of our work by portfolio

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#409]
## Background information	

Whenever money or staffing comes up for the Tech Portfolio, leadership always asks "how will/should the cost be broken down by portfolio/funding source?" In other words, how much time are we spending on 18F vs. PIF vs. COEs vs. FCSF projects? My default response is "the majority of our work is TTS-wide, and is thus evenly split" but it would be good to confirm this hypothesis and decide what "even" should mean (headcount?).

Listed some ideas in the Implementation below, but open to others.

cc @HuixianXu @thecapacity 

## User stories	

- As a member of a TTS portfolio, I want to pay my fair share for the Tech Portfolio.
- As a member of the Tech Portfolio, I want to have a clear picture of how our time is split by portfolio so we have a good answer for when it comes up.

## Implementation

Look at the following and determine the labor breakdown by portfolio and which are TTS-wide:

- [ ] In-progress/blocked/waiting/done issues for the past two(?) months
- [ ] Support requests for the past two(?) months

## Acceptance criteria	

- We know how much time we are spending on particular portfolios, and have data to support it.

**Comment by thecapacity** [comment]
<3 the scientific method here, some suggestion on potential data points;
    * % of ATOs
   * % of service requests
   * % of websites/domains supported
   * % of Software License by org (both time spent as well as license allocation - e.g. is it uniform across orgs).
   * % of platform-specific requests (e.g. if it's majority Mac then that might be majority C&M vs. Solutions which is not 100% Mac)
   * % of 'portfolio specific' cards vs. 'general org' (e.g. overcoming 90 day PW resets is org wide vs. helping a portfolio get an ATO).

In addition to "data first then analysis" you could try some "functional changes" and see if that changes things... e.g. if you set aside "x day(s) per [week|month|quarter" for each of the teams where you only worked on that team's requests (maybe proportional to the $) then if you find yourself largely idle (or overwhelmed) for one team it might be a signal to investigate.
    - Full agreement maybe it's "cyclic" and requires a large measurement period, just trying to show an example of how you could maybe test a few "governance models" as a means to figure out types of data to consider collecting

**Comment by afeld** [comment]
Not going to worry about this right now.
