### ISSUE TITLE
As the Tech Portfolio, we need admin access to all TTS email listserve(s)

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#41]
TTS manages a number of interagency email listserves to manage communications around certain communities of practice. The tech portfolio team should have admin rights in the event we need access to remove users/spam/etc and more importantly manage which delegated members of TTS have admin/management rights over the listserve and to better manage attrition/transitions. 

https://listserv.gsa.gov

Currently, known groups include:

List Names | List Descriptions
-- | --
BLOCKCHAIN  | Blockchain COP | Blockchain COP
CODE   | Code.Gov Project | Code.Gov Project
DEVOPS-TODAY  | Dev Ops | Dev Ops
GSAITALERTLIST  | You should insert a short (4-5 line) description of your list here
MOBILEGOV  |  Mobile Gov Community of Practice members work across federal government to create anytime, anywhere government resources and solutions for today and tomorrow. We share information, practices and tools online and through events to keep government on top of this new technology. Managed by Jacob Parcell, the MobileGov CoP sponsors the Federal Crowdsource Mobile Testing Program, the Structured and Open Content Models Working Group, as well as offering programing through webinars and in-person events.
OPEN-DATA   | Open Data in the U.S. Government | Open Data in the U.S. Government
 SECURITY-TODAY | Modern Security and Privacy | Sharing and discussing modern security and privacy developments and best practices.
TEI-NEWS  | TEI News | TEI News

and others https://digital.gov/communities/

**Comment by afeld** [comment]
Just to be devil's advocate: do we? As long as the responsibilities are clear for those who _are_ admins, is there a situation where we'd need to do something administrative on them (in a hurry)?

**Comment by JJediny** [comment]
As multiple admins are allowed for anyone listserve, I think so, as it would give the Tech Portfolio team the ability to better manage users and their authorization/delegations. Also to combat any continuity issues with people leaving/joining, it would be good to establish a mechanism for that user management aspect.

**Comment by afeld** [comment]
Decided this is out of scope for our team.
