### ISSUE TITLE
project manager for the Tech Portfolio

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#411]
## Background information	

From the [workflow revision](https://docs.google.com/document/d/10H5iTwkb50AkdMK9k_4kx3EbNtMdyG7-TjE_MJSTfCc/edit?ts=5e712a25#heading=h.4nqeujkzg8pw):

> Communicating with stakeholders, organizing our work, etc. is a major effort, and it's reasonable for that to be the case given the breadth of our [scope](https://handbook.tts.gsa.gov/tech-portfolio/) and the number of different groups we support.
> 
> -   "You [the Director] will spend the majority of your time engineering the workflow." -Former GSA CTO
> -   "We spent 40% of our time figuring out what to prioritize, and that was intentional." -Former [thoughtbot](https://thoughtbot.com/) Program Manager
> 
> On most product teams, this is an entire job. I am going to request that we get a half-time project manager for three months to see if it helps relieve stress from the team and improve the quality of our work.

## User stories	

- As a member of the Tech Portfolio, I want to ensure that the team stays organized.

## Implementation	

- [x] Submit request through Daisy
- [x] [Finalize budget](https://gsa-tts.slack.com/archives/C03LNNVQ1/p1584715110022300)
- [ ] Get estimate of when the person will be in place
- [ ] Determine whether to have an existing team member serve this role

## Acceptance criteria	

- The Tech Portfolio has a person dedicated to doing project management

**Comment by its-a-lisa-at-work** [comment]
Closing this now and the specifics of it will be addressed in #482
