### ISSUE TITLE
organize COOP documentation

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#416]
## Background information

The [TTS Continuity of Operations (COOP) page](https://sites.google.com/a/gsa.gov/continuity/home/coming-soon---customized-hsso-pages/ocsit) contains outdated documentation. Let's avoid that problem by linking to canonical Google Docs.

## User stories

- As an Emergency Manager, I want to easily be able to find up-to-date COOP documentation so that in the event of an emergency, I can act quickly.

## Implementation

- [x] Get edit permissions on the Google Site page
   - [x] Reach out to Virginia Hummel
   - [x] Permissions confirmed
- [ ] Convert the [Playbook](https://drive.google.com/file/d/1sfSVhVPBteobeqhqnyb152z1PqboOKJI/view) to a Google Doc
- [ ] Clearly distinguish canonical/living documentation from archived materials in [the Drive folder](https://drive.google.com/drive/folders/1m7fgKcG1dLHXRF_IHNl3xyABl6QDOHCD)
- [ ] Move [the folder](https://drive.google.com/drive/u/0/folders/1m7fgKcG1dLHXRF_IHNl3xyABl6QDOHCD) to a [Shared Drive](https://support.google.com/a/users/answer/9310351)?
- [ ] Deprecate [the contact info in] the [Emergency Personnel Roster](https://docs.google.com/spreadsheets/d/1ITXXOu2IAntV8r6snIYHyXlRt1MgIlxpr-GudDP8tqQ/edit#gid=0) in favor of the  [TTS-wide Emergency Contact spreadsheet](https://docs.google.com/spreadsheets/d/1-Hhv5S0M03W4JY1k-CM5vxrZildHUdMaxAoqLTWF2Ts/edit#gid=1295161336)
- [ ] Complete Corrective Action items listed on page
   - [ ] Indicate they are complete

## Acceptance criteria

- The TTS COOP page points to up-to-date documentation

**Comment by pburkholder** [comment]
Can we expand the User Stories to include:

* As an operator of a TTS Mission Essential Function, I know ahead of time how I'll get information and direction in an emergency.

I realized at cloud.gov we're kind of in the dark on how we'd implement a contingency plan that relies on GSA resources.

**Comment by afeld** [comment]
We should definitely do that, but want to keep this particular issue more tightly scoped. That work?

**Comment by pburkholder** [comment]
I just made a PR to our contingency plan for actions in the event of staff reduction or a COOP, and the links I have are pretty embarrassing. If y'all could make even the tiniest improvement to what's available, like a paragraph in `handbook` then I can make a better case that cloud.gov is prepared for most eventualities.  Can you meet me halfway on that?

**Comment by afeld** [comment]
Will be handing off responsibilities (https://github.com/18F/tts-tech-portfolio/issues/630), so closing this, since they will presumably track work elsewhere.
