### ISSUE TITLE
determine the path forward for documentation themes

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#419]
## Background information

TTS themes are a bit all over the place, and in various states of maintenance. Let's take a step back and think more holistically about what templates/starters we want to continue/be offering, and who is going to be responsible for maintaining them.

## User stories

- As someone who ends up being responsible for unmaintained sites (the Tech Portfolio), I want to avoid being in that position so that I can focus on other things.

## Implementation

- [x] Write up [background+proposal](https://docs.google.com/document/d/1LCKZKqoEEYOCwntZpTbHp8bW7tdnPnmmKVJ-YNHAUy4/edit#)
- [x] Share with folks mentioned in https://github.com/18F/uswds-jekyll/issues/190 - due 3/31, to give time for review before the meeting below
- [x] Discuss path forward - schedule
   - [x] Schedule it - on the calendar for 4/1
   - [x] Meet
- [x] Get votes on path forward from stakeholders
- [x] Create follow-up issue(s)

## Acceptance criteria

- A roadmap that has been widely circulated and is generally agreed upon

**Comment by afeld** [comment]
[Took a few notes in the meeting](https://docs.google.com/document/d/1LCKZKqoEEYOCwntZpTbHp8bW7tdnPnmmKVJ-YNHAUy4/edit?ts=5e84bb39#heading=h.d36e3gkuyvh3)—seems like everyone who was there understood the problem and was on the same page about goals. Next steps are for them to indicate (here, or in comments on the doc) about which of the [Options](https://docs.google.com/document/d/1LCKZKqoEEYOCwntZpTbHp8bW7tdnPnmmKVJ-YNHAUy4/edit?ts=5e84bb39#heading=h.8amwb3toikbj) they prefer.

cc @cmajel @davemcorwin @ryanhofdotgov @thisisdano @davemcorwin

**Comment by thisisdano** [comment]
So, the USWDS 2 version of the `uswds-jekyll` theme is [pretty much done](https://github.com/18F/uswds-jekyll/pull/178). It really just needs review. Now, this doesn't do anything to change the opinionated-ness of the theme — it just rebuilds the theme to better use USWDS 2. I've also [applied this theme to the TTS handbook](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/handbook/dw-audit-uswds/) in a [separate draft PR](https://github.com/18F/handbook/pull/1754). 

It feels like there's a place both for a _theme_ like `uswds-jekyll` that could apply to any Jekyll project and and a clone-able _project/starter_ like `federalist-uswds-jekyll` or something else that's a simple way to use that theme in a project, integrate docker, etc etc — perhaps with its own custom settings layered on top. 

I think there's some value in maintaining a `uswds-jekyll` theme that serves as a theme for teams and agencies outside of TTS, but I think that value is still consistent with "opinionating" `uswds-jekyll` and making it more directly useful to TTS, its guides, and any TTS projects that use it.

I guess I don't have an opinion on whether the project/starter should be _the_ canonical and consolidated home/repo for all TTS guides — it _could_ be but needn't be.

**Comment by cmajel** [comment]
👋 I wanted to check back in and see if there were any updates on this yet. Is the conversation on site starter vs theme still ongoing?

For context, here are two project I've encountered recently that used different approaches to the theming problem. 

* The [18F UX-Guide](https://github.com/18F/ux-guide), which currently is using the updated `uswds-jekyll` theme (aka, theme approach). However, it's been tricky to add some needed elements (like search for IDEA Act and the anchor footer for GSA branding).
* The [18F De-risking Government Tech field guides](https://github.com/18F/derisking-gov-tech), which is using a 18F themed version of the [federlist-uswds-jekyll](https://github.com/cmajel/federalist-uswds-jekyll-18Ftheme) (aka, site starter approach). This was flexible enough for the team to make their own adjustments while having key styles and functionality baked in.

**Comment by afeld** [comment]
> Is the conversation on site starter vs theme still ongoing?

Unless there's objection, I strongly suggest we go down the path of [simplifying uswds-jekyll](https://github.com/18F/uswds-jekyll/issues/190), taking out a lot of the YAML configuration and encouraging folks to override the `include`s if they want to customize the footer or whatever.

I'm pretty 👎 on using starters for TTS documentation sites, because of the added work of keeping each up-to-date.

> it's been tricky to add some needed elements like search

Hmm, it should just be a matter of [setting the `search_site_handle` in `_config.yml`](https://github.com/18F/uswds-jekyll#search).

**Comment by hoaiandang** [comment]
We'd like to get a consensus for which option people prefer before going forward. We have the following options (which are elaborated more upon [here](https://docs.google.com/document/d/1LCKZKqoEEYOCwntZpTbHp8bW7tdnPnmmKVJ-YNHAUy4/edit?ts=5e84bb39#)):
1. [Bring uswds-jekyll up to snuff](https://github.com/18F/uswds-jekyll/issues/190)
2. Run with [the new guides template](https://github.com/18F/uswds-jekyll/issues/190#issuecomment-605308240)
3. Merge the sites

To vote for the first option, react with a 👍 
To vote for the second option, react with a 🎉 
To vote for the third option, react with a 🚀

**Comment by tbaxter-18f** [comment]
I don't have a strong opinion, but I do, in general, agree with Aidan's proposal in https://github.com/18F/uswds-jekyll/issues/190#issuecomment-605308240 to make it more opinionated. I think having a more opinionated template leads to more consistency, which helps both with overall organizational branding and technical maintenance. 

So I'm going to give a very tentative 🎉 with the caveat that I'll happily go with the consensus opinion, whatever it may be.

**Comment by thisisdano** [comment]
My first priority is to get a published version of the USWDS 2 version of `uswds-jekyll`. I suppose my _ideal_ setup down the road would be for a very simple version of `uswds-jekyll` that did some nice and useful component templating (and massively improve the documentation) but not too much else... something that could be a useful sandbox-y theme for projects beyond TTS. _Then_ it would be nice if `uswds-jekyll-tts` or suchlike was a child theme (and yes I know that child themes do not exist in jekyll). Generally, I would prefer it if `uswds-jekyll` were more broadly useful, but I understand the desire to have it more opinionatedly power TTS docs sites. This was part of why I'd hoped a simple jekyll theme might power a clone-able TTS template that extended it. But yes, there is a maintenance cost there. I don't know where his puts me in the 1/2/3 continuum, probably closest to 👍 . I am 100% in favor of simplifying `uswds-jekyll`.

**Comment by brentryanjohnson** [comment]
I'm not sure how to respond to this. I understand the intent of having a general theme that can be widely applied to many different sites, and yet, the need for a guides-specific theme drove (at least part) of this conversation to begin with.

On the other hand, once we have an implementation of a guide with the custom work completed, that could effectively serve as the "guide theme." 

So I suppose I vote 👍.
