### ISSUE TITLE
Work on a generalized software integration policy

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#420]
## Background information	

https://trello.com/c/a6cKLzCf/7-work-on-a-generalized-software-integration-policy

## User stories	

- As someone doing TTS Tech Portfolio Ops Rotation, when a question shows up about whether or not it is OK to link an integration, I would like to know how to address the question

## Implementation	

_See Trello card._

## Acceptance criteria	

- There is a software integration policy

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/421.
