### ISSUE TITLE
update telework codes

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#424]
## Background information

See `Telework Code Update Required in HR Links` email.

## User stories

- As someone in charge of time tracking at GSA, I need to account for mandatory telework.

## Implementation

1. [x] [Update Work Schedule Telework Codes](https://docs.google.com/document/d/1uvae7yL0s3GGv55WM9GvdR5Mq2NOKNKwlyEgarHVulU/edit)
   - [x] @afeld 
   - [x] @its-a-lisa 
   - [x] @JJediny 
1. [x] @afeld [Approve Work Schedule Telework Codes](https://docs.google.com/document/d/1Bcxl_YgOy4BFSMLTxq6QRjy3YhsWAzOzhFU-wYglWNQ/edit)

## Acceptance criteria

- Base schedule updated with appropriate telework codes

**Comment by its-a-lisa** [comment]
@afeld , which code does our team fall under?

092 - Routine telework performed as part of a previously approved, ongoing, and regular schedule. Use this code on your regular telework days.


093 - If you telework full time, use this code on all of your telework days.

**Comment by afeld** [comment]
Good question—[checking](https://gsa-tts.slack.com/archives/C047LSLTU/p1585748915027700).

**Comment by afeld** [comment]
Update: 95% sure both of you are Regular, so go ahead and [update your base schedule](https://docs.google.com/document/d/1uvae7yL0s3GGv55WM9GvdR5Mq2NOKNKwlyEgarHVulU/edit), using 092 for the 2+ days a week you are most likely to be in the office, 090 for the remainder.

**Comment by its-a-lisa** [comment]
@afeld double checking -- I believe it should be the other day around, no?

- 090 - Emergency telework performed in response to an emergency situation, including unscheduled telework in response to an OPM operating status announcement that allows it or in response to a Continuity of Operations Plan (COOP) situation. 
  - The **two** days that would normally go in the office
-  092 - Routine telework performed as part of a previously approved, ongoing, and regular schedule. Use this code on your regular telework days.
  - The typical **eight** days that would normally work remotely

**Comment by afeld** [comment]
I'm sorry, you're correct.

**Comment by afeld** [comment]
Done.
