### ISSUE TITLE
investigate services TTS systems are having to use to supplement cloud.gov

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#427]
## Background information

cloud.gov offers a number of [managed services](https://cloud.gov/docs/services/intro/), which is great for teams not having to worry about managing that infrastructure, the compliance, additional user accounts and permissions, etc. That said, there have been a number of cases where a TTS system needs a service that _isn't_ offered, and then need to manage it on its own. 

Example limitations from TTS Programs:
- Federalist: queueing (e.g. AWS SQS)
- Touchpoints: transactional email (e.g. AWS SES) - cc https://github.com/18F/tts-tech-portfolio-private/issues/880
- Data.gov: No Solr brokered service (e.g. no self-managed backend service option)
- Search.gov: Custom High Availability Elasticsearch cluster (e.g. no self-managed backend service option)
- USA.gov: Hard to manage customization and state for traditional CMS applications (e.g. drupal)

Generalized Examples:
- No Vulnerability scanning as-a-service offerings (e.g. SonarQube)
- No Container Registries as-a-service offerings (e.g. [Harbor](https://bosh.io/packages/harbor-app))
- No Git as-a-service offerings (e.g. Gitlab)
- No CI/CD as-a-service offerings (e.g. drone.io, jenkins, etc)
- No queuing backend services offerings beyond Redis (e.g. Kafka, Rabbitmq, etc.) 
    - Requires dev work to migrate to redis (if at all possible)
- 6GB disk quota limit for Applications (e.g. No service broker offering for [Networked File System (NFS)](https://docs.cloudfoundry.org/devguide/services/using-vol-services.html))
- Limited brokered services for AWS managed services (only RDS is offered)
- Brokering GCP/Azure services is not an option to self-authorize a supplemental IaaS provider
- Kubernetes-as-a-Service nor bosh-deployments are offered to customers - self-hosting open source application stacks  are nearly impossible to deploy via a `cf push` given the complexity around the orchestration of backend service requirements. 
   - These project communities are generally maintaining their suggested deployments as docker-compose and/or helm charts. (examples - [Gitlab CE - helm chart only support](https://docs.gitlab.com/charts/installation/deployment.html) | [Defectdojo - helm/docker-compose only](https://github.com/DefectDojo/django-DefectDojo/blob/master/KUBERNETES.md) | [harbor container registry - helm or bosh only](https://bosh.io/packages/harbor-app))

## User stories

- As a developer on a TTS system, I want to manage as little infrastructure (and corresponding compliance) as possible so that I can focus on my application.
- As someone responsible for TTS budget, I don't want duplicate effort of teams spending money building out the same things.

## Implementation

- [x] Get an inventory of what services are being leveraged by which systems - cc https://github.com/18F/g-devops/issues/10
- [x] Eliminate services from the list already brokered by cloud.gov
- [x] Eliminate services from the list that aren't easily [brokerable](https://www.openservicebrokerapi.org/), such as if they:
   - Need UI access
- [x] Prioritize remaining services by how widely they are used in TTS
- [x] Present to cloud.gov team
- [ ] Break out issues for follow-up work, either by the Tech Portfolio or cloud.gov

## Acceptance criteria

- [ ] We have a prioritized list of services that would TTS programs would benefit from having available

**Comment by afeld** [comment]
[Discussion in an Engineering @ Solutions meeting](https://docs.google.com/document/d/1jm5mDHeZQtwulXVtldBU8te7WyeH_MKwNTgoXvGGM7U/edit#bookmark=id.jp6utw9djrea)

**Comment by mogul** [comment]
> Limited brokered services for AWS managed services (only RDS is offered)

cloud.gov switched to brokering [AWS Elasticache (Redis)](https://cloud.gov/docs/services/aws-elasticache/) and [AWS Elasticsearch](https://cloud.gov/docs/services/aws-elasticsearch/) in place of their own k8s-hosted Redis and Elasticsearch, which are now deprecated.

**Comment by afeld** [comment]
A few projects with immediate needs here:

- Data.gov with Solr
- Federalist with SES/SQS
- FormService with MongoDB
- Touchpoints with SES

@JJediny will be reaching out to get the teams together to see if we can combine efforts and expand some brokering offerings.

**Comment by RonWilliams** [comment]
@afeld This is my first time seeing this, but we're onboard with prioritizing the needs identified. We're seeking investment to extend cloud.gov further, but having a list of specific items with clearly identified users is helpful for justification. 

Thanks for pushing this research forward!

**Comment by mogul** [comment]
In the [Security and Compliance Guild meeting today](https://docs.google.com/document/d/1eEWwcWzvd_ua8KfL34Mc30M4iqvNniqAqJXiLWEKwuY/edit#heading=h.ph34wd35l5b8) we also discussed this topic at length. We identified these as other potentially brokerable gap-fillers:

- minimal stack for alerting on logs/metrics. Options that can run entirely in cloud.gov:
  - Existing [log-cache](https://github.com/cloudfoundry/log-cache-cli) + [Monit](https://mmonit.com/monit/) app (no persistence)
  - [promtail](https://grafana.com/docs/loki/latest/clients/promtail/) app + [Grafana Loki](https://grafana.com/docs/loki/latest/) app + brokered S3
  - Possibly [New Relic's FedRAMP'd logging service](https://newrelic.com/products/logs)?
- transactional email (eg SES)
  - Not only for app needs, but also for alerting
- Moderate-or-higher social coding and Moderate-or-higher CI/CD
  - GitHub.com is Li-SaaS, need more than that for supporting Moderate-or-higher teams 
  - login.gov is putting GitLab inside their boundary, but it could be brokerable
 
data.gov is also in need of a transactional email solution (eg SES). We're tackling [adding SES to the Supplementary Service Broker(SSB)](https://github.com/gsa/datagov-deploy/issues/2321) this week (see the "Sketch" section), so hopefully we'll have something reusable soon.

**Comment by ryanwoldatwork** [comment]
I'd like to see guidance on email conventions and DNS configs required, that are related considerations to getting SES working.

I'll shareback what we learn.

I've learned that it is not permitted to send mail using an @gsa.gov address from an external source.

So, now I'm considering a @touchpoints.app.cloud.gov email or a @touchpoints.digital.gov email. Likely the latter.

**Comment by ryanwoldatwork** [comment]
I recently got AWS SES up and running finally.

Technically, its not too bad. DNS records need to be set and verified which typically takes some coordination.

I got hung up on selecting and configuring the "right" email to use. I tried to use an existing @gsa.gov email, which turned out to be a lot more effort (for the org) than using a @touchpoints.digital.gov email.

Early, I pursued the gsa.gov email because it existed and we didn't have a touchpoints.digital.gov email, nor the need for one. But ultimately, I was able to verify the ..digital.gov DNS records successfully; whereas, I could not verify gsa records.

SES could be a good candidate to be brokered. A cloud.gov help page would probably fill the gap as well.

**Comment by adborden** [comment]
@JJediny and I think the next step is to have a meeting with cloud.gov (and maybe leadership). Now that we have a rough idea of a list of services that could be implemented to help TTS programs, we want to answer:
- who should do that work?
- which order should they be implemented?
- who will own the service once launched?

There are several options, and we should discuss with partners before moving forward. For example, Tech Portfolio could own and manage services. For services that would be good for all cloud.gov customers, beyond TTS, the Tech Portfolio could implement services to hand-off to cloud.gov.

Agenda:
- Introduction and background of this work
- What is cloud.gov's capacity for implementing and managing new brokered services?
- If a hand-off to cloud.gov was desired, what would a human-centered design approach look like?

**Comment by adborden** [comment]
The [SES service has already been implemented](https://github.com/GSA/csb-brokerpak-aws/pull/16) by data.gov. In terms of a high-value, low effort brokerable service from the list that would help TTS, this might be the best option.

**Comment by mogul** [comment]
"has already" is a bit of an overstatement... AWS just changed their domain identity verification method, so I'm having to redo some of that work. Also as delivered, it only supports creating a random `@ssb.data.gov` address to send from, which isn't as useful as it could be.

**Comment by afeld** [comment]
[Features that GIVE needs from cloud.gov to ATO](https://docs.google.com/presentation/d/1GdxXgBlxToQB20Zae0GagEUzp6yfDGZFLrgUd2uLb-M/edit#slide=id.ge15ccd3e40_5_14)

**Comment by afeld** [comment]
This is done; see [infrastructure needs](https://github.com/18F/aws-admin/blob/main/docs/tts-infrastructure-needs.md#findings-based-on-tts-system-interviews-and-slack-threads).
