### ISSUE TITLE
Create combined Acquisition/Security Boundary Guidance Documentation

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#430]
There is a clear correlation between a system's 1. Staffing (feds vs contracted staff augmentation) tie together onboarding/offboarding procedures. 2. IaaS/PaaS/SaaS procurement/use corresponds to the tools used to implement security controls and/or adds to the surface area of the system. 

## Acceptance Criteria
- [ ] Draft an outline
- [ ] Coordinate a peer review
- [ ] Update Handbook/before-you-ship

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
