### ISSUE TITLE
TTS Tech Portfolio Weekly idea collection 17-18:20

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#440]
## User story

- Create Agile ATO process
-- 10x version
-- Federalist version
-- SaaS version

## Background

-[10x Site Scanner ](https://docs.google.com/document/d/1MXDbYrwoknlqD8led2no_iavx-KLHYlKqJ_4S2S3BVg/edit)

## Acceptance Criteria

- [ ]

**Comment by afeld** [comment]
What should we do with this issue?

**Comment by its-a-lisa-at-work** [comment]
Going to close for now; but address the problem in https://github.com/18F/tts-tech-portfolio/issues/469 that there is a poor way to collect ideas/user stories outside of issues and that this would make a great epic and example of something that should be roadmapped
