### ISSUE TITLE
propose moving management of various SaaS to GSA IT

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#444]
## Background information

_[Corresponding card in the CTO Trello board](https://trello.com/c/ZeZsOWhl/321-recompete-tts-saas-contracts-groom)_

There are a handful of tools that either:

- Have reached a wide level of use across GSA
- TTS gets regular requests from other teams, to where it seems like there would be demand across the agencies

Prime examples:

- Mural
- Trello
- Zoom [for Government]

Like with Slack, it feels like there's opportunity to have GSA IT do centralized management, and that (if done well) could be better for everyone.

## User stories

- As a member of GSA, I want easy access to modern tools to do my job, particularly now with a fully distributed agency.
- As a member of the Tech Portfolio, I want to offload administrative responsibilities for widely-used SaaS so I can focus on bigger things.

## Implementation

- [x] Create a pitch with the (prioritized?) list of software we'd like to hand off
   - Demand
   - Shortcomings of the current setup
   - What's involved in administering it
- [x] Circulate to Bruce Teng and CTO team
- [x] Get feedback
- [ ] Create issue(s) for next steps

## Acceptance criteria

- The Tech Portfolio and GSA IT are on the same page about what software we want to hand off and why

cc @josephderosales

**Comment by its-a-lisa-at-work** [comment]
Looking to do this activity as soon as possible; [started the engagement ](https://trello.com/c/ZeZsOWhl/321-recompete-tts-saas-contracts-groom#comment-5f2b064124b849131e8e1293)on this with @josephderosales to see when this would make sense to start giving both team's capacity

**Comment by afeld** [comment]
While we'd welcome help, this doesn't _necessarily_ need to go through the CTO team—we can work with the Software License Management group directly.

**Comment by its-a-lisa-at-work** [comment]
Roger! I was doing the OpsRotation work of looking through the board and saw the card already on there so assumed that was a dependency; regardless, letting them know that it is happening is a good move in the right direction; but this vectoring helps as well

**Comment by its-a-lisa-at-work** [comment]
Sent email to the software management team; moving to waiting/feedback until we hear further

**Comment by its-a-lisa-at-work** [comment]
- TTS shared a link to a dashboard that was put together to help drive the conversation
- TTS updated dashboard as we went; the column about the asset type wasn’t there originally
- TTS updated dashboard after the meeting to better reflect how they want/need to see the information (broken up by Desktop & Cloud vs TTS expectations for what should be managed)
- GSA Software Management team mentioned they’re not in a place now to take on the SaaS Management; but that is something they are working towards
- Most, if not all software, will eventually be managed through GSA Software Management
- Still figuring out how the roles/responsibilities/workflow will work out between offices and approvals, license purchases
- Currently, 10 licenses is a threshold for a tier of management
- Much easier to manage if there is a management portal
Moving Next Steps to [new issue](https://github.com/18F/tts-tech-portfolio/issues/788):
- [ ] They’re going to look through the software and put records into their ServiceNow CMDB
- [ ] Eventually give us access to the dashboard; unsure which role at this point
- [ ] Pick a candidate to get managed by them

Updated dashboard: https://app.smartsheet.com/dashboards/Jqgqx4j7xPHCxmrW46q9m59cx6jRfWXpFWQcCcX1

**Comment by afeld** [comment]
Cheryl Grimes reached out to pick this back up again.

**Comment by afeld** [comment]
Whoops, didn't see we had https://github.com/18F/tts-tech-portfolio/issues/788 — closing in favor of that.
