### ISSUE TITLE
decommission epa-notice.usa.gov

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#446]
https://gsa-tts.slack.com/archives/C039MHHF8/p1588178967314900

_Add/remove items, as applicable._

- [ ] Clean up infrastructure
  - [ ] [Ask cloud.gov](https://cloud.gov/contact/) for the organization to be deleted.
  - [ ] Delete any associated AWS resources, and decommission any AWS accounts. Ask in [#infrastructure](https://gsa-tts.slack.com/messages/infrastructure) for help.
  - [ ] If the site was operated on Federalist, contact [federalist-support@gsa.gov](mailto:federalist-support@gsa.gov) to deprovision the [custom domain](https://cloud.gov/docs/management/custom-domains/) for the site
- [ ] [Archive the GitHub repositor(ies)](https://help.github.com/articles/archiving-repositories/). Ask in [#admins-github](https://gsa-tts.slack.com/messages/admins-github) if you need help.
- [ ] Domain changes
  - [ ] Clean up any DNS entries that are no longer needed, from [the DNS repository](https://github.com/18F/dns) or elsewhere.
  - [ ] Update DNS entries to point to new urls or [set up redirect(s)](https://github.com/18F/pages-redirects#domain-redirects).
any external integrations

**Comment by JJediny** [comment]
Status update - https://gsa-tts.slack.com/archives/C2KTQ3URK/p1604341418014900

**Comment by afeld** [comment]
Put in the full decommissioning checklist.

**Comment by amirbey** [comment]
@afeld @JJediny - we (Federalist) have been receiving monthly inquiries regarding this site from GSA IT.  I'd be happy to assist with this decommission.

**Comment by JJediny** [comment]
```
Hello John H Jediny - john.jediny@gsa.gov,
 
Item RITM0785067 submitted with order REQ0565943 has been Rejected. The rest of the order will be processed upon approval if there are any remaining items in the order.
 
For your convenience some details regarding the rejected item are included here.
 
Reject Details:
 
2020-12-03 12:41:28 AM EST - System (Comments)
The request you have submitted has been rejected due to the request pending approval over 30 days
 
 
Requested For: John H Jediny - john.jediny@gsa.gov
Requester: John H Jediny - john.jediny@gsa.gov
Item: Domain Name System (DNS) Request
Item #: RITM0785067
 
Order Details:
 
 
Item: RITM0785067 - Domain Name System (DNS) Request for John H Jediny - john.jediny@gsa.gov
     Requested For: John H Jediny - john.jediny@gsa.gov
     Requested For's Phone: (202) 341-0191
     Supervisor: Aidan L Feldman - aidan.feldman@gsa.gov
     Alternate Phone Number:
     Physical Region: 12 CO
     Administrative Organization: Federal Acquisition Service
     Planning Date: 2020-11-03
     Workstation:
     Do you know the FISMA System?: Yes
     Please select Fisma Group: USAGOV
     System GSA ISSO: 348d6b3c415b1d80cb92eccdcd0e3c07
     System GSA ISSM: d1fc23531b4158d09496ddb6bc4bcb18
     Category: DNS
     DNS Type - Please select the appropriate option: External DNS
     DNS Subtype - Please select the appropriate option: Change Record
     Please enter additional information about this DNS request: Please remove all subdomain records for epa-notice.usa.gov. We (the TTS Tech Portfolio https://handbook.tts.gsa.gov/tech-portfolio/ own all of our dotgov.gov domains and are performing a subdomain cleanup of our organizations dns records). We have worked with the usa.gov (russell.oneill@gsa.gov) to confirm the removal of this record will have no affect.
     Additional Comments: please cc devops@gsa.gov
```

@amirbey we have approval from usagov team to remove records for the site cc @smileytech has been on leave but was going to follow up. If you can shut it down from federalist/DNS side please proceed (We thought this record was being set at GSA DNS)

**Comment by amirbey** [comment]
Hi @JJediny - you're right.  I had assumed the DNS was set within 18f/dns since it was a usa.gov domain.  Perhaps I should wait until we can remove the DNS for this site before taking down the CDN for this site.  Keep me posted.

**Comment by afeld** [comment]
@JJediny Can you post an update on the current status?

**Comment by JJediny** [comment]
@smileytech any update on this GSA says they are not the DNS owners, the domain is a CNAME pointing to Route53 but not managed within https://github.com/18F/dns/search?q=epa-notice

**Comment by davemcorwin** [comment]
@smileytech @JJediny Any updates here? GSA IT is flagging the site again for vulnerabilities.

**Comment by afeld** [comment]
- [ ] @smileytech Create JIRA ticket for DNS change
