### ISSUE TITLE
provide Solutions Profile info to OGP Emerging Tech team

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#447]
## Background information

https://docs.google.com/document/d/13LAfT0YTAvTK1BHcosrFgoxdM6hgdql_yFG63lPBX50/edit#heading=h.bk522bwu8pt5

## User stories

- As a ..., I want ... so that ...
- As a ..., I want ... so that ...

## Implementation

- [x] Provide a list of examples of No vs. Low-risk SaaS from the TTS 24 with a sentence or two about the determinations for each
- [x] Provide Solutions Profile template/guide

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

**Comment by its-a-lisa-at-work** [comment]
Sent the follow up today :)
