### ISSUE TITLE
AWS cross-account user/resource cleanup

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#451]
Related to Epics: 18F/tts-tech-portfolio#19
Related to High-level issues: 18F/tts-tech-portfolio#65 18F/tts-tech-portfolio#70 

As a complement to account standardization (TTS tech portfolio standard users/roles) and account federation. I want the ability to backup/export an existing AWS account for the ability to audit current users/roles as well as resource utilization in a pull/push manner. 

Initial exploration/testing of how to export an AWS account into code.

Acceptance:
- [x] demostrate terraform export for MVP viability
- [x] demonstrate cloudcheckr's ability to perform user and resource utilization auditing/cleanup
- [ ] determined which if the two is the most viable immediate action to perform

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/aws-admin/issues/40.
