### ISSUE TITLE
add faq.coronavirus.gov

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#452]
[Slack thread](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1587155605006100). We can follow the established process of adding to the private bounty first, then moving it over once it calms down.

**Comment by its-a-lisa** [comment]
Waiting for 👍 from outreach on draft language

**Comment by its-a-lisa** [comment]
we moved faq.coronavirs.gov into the scope of the Private Bug Bounty program w/ the language below. This went out to ~500 through a message on the platform.
```
Hello Researchers,
We added a new asset to our private program and disclosed two reports in our public program:
Report 272095: SSRF/XSPA in labs.data.gov/dashboard/validate
Report 798742: Open redirect in eb9f.pivcac.prod.login.gov
As a reminder, the TTS program supports collaboration. If you would like to work with another hacker on a report, invite them to your submission before bounty is awarded to split the payout!
Thank you for your help securing TTS, and happy hunting!
TTS Security Team
```
