### ISSUE TITLE
TTS Tech Portfolio - How We Work: Domain Leaders

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#453]
## Background information

We want to ensure that our domain areas are well-covered.

## User stories

- As a Tech Portfolio member, I want to ensure that acceptance criteria are well-established for all issues in a particular domain.
- As a Tech Portfolio member, I want to ensure that various tasks related to a larger domain are represented.

## Implementation

- [x] Assign
- [x] Confirm with team
- [x] Document

## Acceptance criteria

- All domains are assigned to a particular Tech Portfolio member and [documented](https://docs.google.com/document/d/1scmBeDakkOI8EOyAlVkFNQWvlBqb0SPhrYx-_0P5CdM/edit)
- I know what my responsibilities are as a domain lead

**Comment by its-a-lisa-at-work** [comment]
@afeld & @JJediny I finished this taks; moving to Waiting/Blocked and adding the Feedback Needed label and assigning ya'll so you can take a look and give a thumbs up

**Comment by afeld** [comment]
Added some [risks/concerns](https://docs.google.com/document/d/1scmBeDakkOI8EOyAlVkFNQWvlBqb0SPhrYx-_0P5CdM/edit#heading=h.6gx19b9kkz4j), but other than that, 👍

**Comment by its-a-lisa-at-work** [comment]
Documented in https://github.com/18F/tts-tech-portfolio/pull/509 and [TTS Tech Portfolio - HWW:  Domain Leaders](https://docs.google.com/document/d/1scmBeDakkOI8EOyAlVkFNQWvlBqb0SPhrYx-_0P5CdM/edit)
