### ISSUE TITLE
Mural Admin - Describe the Problem

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#461]
## Background information

When someone departs TTS and has a mural account, the admin is given the option to either deactivate their account or delete their account and transfer their repo

Breaking this out as a actionable, small chunk step related to #317 which is more of an epic until all the chunks are completed

## User stories

As someone in the TTS Tech Portfolio, I would like this activity to get started so that the next time I'm on OpsRotation, this is closer to being solved

## Acceptance criteria

- A [document](https://docs.google.com/document/d/13ZbQ2qMMODfxyyKOgTfioifZ7AW_jq47_9o5r49SnKM/edit#) is started to describe the problem with options for providing a solution

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa** [comment]
moved to waiting/blocked until 3/14 Standup to mention it to @afeld and @JJediny so we can review acceptance criteria and also determine if it has been met

**Comment by afeld** [comment]
Looks good! Go ahead and create the subsequent issue and we can close this one.

**Comment by its-a-lisa** [comment]
created #468 so closing this
