### ISSUE TITLE
Set up continuous deployment for aws-admin

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#467]
## Background information

Broken out from https://github.com/18F/aws-admin/issues/40

## User stories
As the tech portfolio I want a git workflow to manage deployment of a shared terraform state across all accounts and without state conflict.

## Acceptance criteria

- [ ] AWS baseline terraform is setup with continuous deployment using a persistent/shared .tfstate

**Comment by JJediny** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/443

**Comment by afeld** [comment]
They are different; this is for aws-admin, while the other is for tts-tech-portfolio (GitHub).

**Comment by afeld** [comment]
Given how powerful this is, going to stick with running manually for now.
