### ISSUE TITLE
Mural Admin - Develop Approach for Offboarding

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#468]
## Background information

Follow up for #461

## Acceptance criteria

- The options going forward have been refined

**Comment by its-a-lisa-at-work** [comment]
@afeld this is another OpsRotation related one you can pick up if you have extra slack

**Comment by afeld** [comment]
> Instead of removing members from your workspace and transferring their content to a new owner, you can now deactivate them. This will free up their membership seat, and allow the user to request reactivation in the future. All of the user’s content will remain available and, should they be reactivated, would seem as if nothing ever happened.

https://support.mural.co/en/articles/2145569-activate-and-deactivate-members

Given how much of a pain it would be for a user with a lot of boards to do all the transferring, let's go with that. @keithrwilson Mind updating the offboarding template with the word "deactivate"?

**Comment by afeld** [comment]
Never mind, updated in the [old](https://docs.google.com/spreadsheets/d/1IlFY5AAvTyuS7yDHk5_odJGHYZDU_MN9HNGKJ2zXwi0/edit#gid=64154758) and [new](https://docs.google.com/spreadsheets/d/1rp8n78tFHqyvvHzsYuBo_XE3Jg1LwOuOX-R9TMRnZI8/edit#gid=1916685737) templates.
