### ISSUE TITLE
TTS Tech Portfolio - How We Work: Work Structure

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#469]
[TTS Tech Portfolio - HWW - Work Structure](https://docs.google.com/document/d/1tj0Ll8x7OkBtilJQKqkWqVhd_spByEm21n84g6mW0-w/edit#)

## Background information

We currently have too many things going on with the board. 
There are  ...
- Epics in Columns
- Labels that (kind of) relate to Epics
- Major Initiatives as Milestones
- Sprints as Milestones

## User stories

@afeld @jjediny please add some user stories of what you'd like to see. 

Looking for what you see as the painpoints with the labels (do the colors need to change? Need labels to help describe the issue like priority?)
What is working and what is not working with the board? 

## Acceptance criteria

- tts-tech-portfolio/workflow.md pull request accepted

**Comment by afeld** [comment]
@its-a-lisa-at-work Do the list of things that confuse me and the user stories in https://github.com/18F/tts-tech-portfolio/issues/483 work?

**Comment by its-a-lisa-at-work** [comment]
@afeld Yes -- but encourage any other user stories that you can think of...

**Comment by afeld** [comment]
- As someone in the Tech Portfolio creating/managing issues, I want to know:
   - What labels to apply and when
   - What column it should go in
   - If/when it should be added to a milestone
   - Etc.
- As someone in the Tech Portfolio creating/managing issues, I want minimal cognitive overhead / friction in doing so.

**Comment by its-a-lisa-at-work** [comment]
@18F/tts-tech-portfolio ready for review

**Comment by its-a-lisa-at-work** [comment]
Moved to Blocked/Watching because need https://github.com/18F/tts-tech-portfolio/issues/443 to be done before able to update labels for our repos

**Comment by afeld** [comment]
I know it's not ideal, but if you want to tell me the labels you want (or even send a pull request), I can `apply` them for you.

**Comment by its-a-lisa-at-work** [comment]
No longer blocked by #443 now blocked by #574 being applied

Other work related to this can be done; so no rush, but wont' be able to fully complete without that being done

**Comment by its-a-lisa-at-work** [comment]
Closing this since the acceptance criteria has been met; still need the labels to be created but that shouldn't delay this being closed
