### ISSUE TITLE
Shared Engineer interview prep

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#474]
## Background information

[Job post](https://docs.google.com/document/d/1I4dRjWj9OzuuFQJvGppnMCojFsseHLqPPc7pc-IDTbw/edit)

We need to get questions ready for the candidates, adapting [the existing interview materials](https://github.com/18F/tts-tech-portfolio/blob/master/links.md#interviewing) as necessary.

## User stories

- As someone conducting interviews for the Shared Engineer, I want to know what questions to ask to evaluate who will best meet the needs of the role.

## Acceptance criteria

- There is a list of interview questions with criteria/examples of strong/weak answers

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Holding to figure out what next steps are.

**Comment by afeld** [comment]
From Hiring team:

> we are wrapping up debriefs this week and will likely know by next week if there are strong candidates that [18F] won't be moving forward with

**Comment by its-a-lisa-at-work** [comment]
This task is taking a little longer than expected originally; I know I volunteer to help previously, but at this point I have a lot on my plate at the moment and I feel like this is an easy activity to cut. If you need an extra set of eyes, feel free to reach out !

**Comment by JJediny** [comment]
I could sub in here

**Comment by afeld** [comment]
This is on hold until further notice, so closing.
