### ISSUE TITLE
clarify current state of IT Standards / FITARA procedures - due 9/1

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#475]
## Background information

Create a proposal similar https://github.com/18F/tts-tech-portfolio/issues/366 that describes the workload necessary for IT Standards FITARA requests and reviews

Closed https://github.com/18F/tts-tech-portfolio/issues/244 in favor of this

Ideally, what we need is a clear understanding of what happens when someone says "We should use product X" and how long it will be before they have a rationale of why product X can't be used or where it is in the process of being evaluated. And who is going to do that work and what the steps of doing that work entails. 

## User stories

As someone in the Tech Portfolio Director, I would like ...

As a TTS TechPortfolio person doing LiSaaS, I would like to understand what the FITARA and IT Standards are so that I can keep that in mind when I'm doing this work. 

As someone in the TTS Tech Portfolio doing P-Card purchases, I would like

As someone within TTS, I would like to make a suggestion about a tool that I think would be a good fit so that I can start using it. 

## Acceptance criteria

-  Clear understanding of roles and responsibilities as well as process and procedure related to FITARA and IT Standards
---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Might make sense to split this into two issues.

**Comment by its-a-lisa-at-work** [comment]
Should we close this issue and break it out to smaller issues? I think a more attainable activity for the...
- [ ] IT Standards is to determine the workflow for the IT Standards and address @josephderosales suggestion of an IRB
- [ ] Document how FITARA responsibilities fits into someone's https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/roles.md

**Comment by afeld** [comment]
Sounds good to me!

**Comment by afeld** [comment]
I feel our FITARA workflow is fairly well-defined, so I don't think there's an action item there right now. If others disagree, please open a new issue.

For the IT Standards, seems the main question is around intake/prioritization. --> https://github.com/18F/tts-tech-portfolio/issues/742
