### ISSUE TITLE
Document Deputy Director role description

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#482]
## Background information

for anyone that wasnt at the #solutions all-hands: excited to announce @its-a-lisa as Deputy Director of the #tts-tech-portfolio. this is one of those cases where she was actively filling that role before i even realized having one would be helpful. please give her a round of emoji applause!

## User stories

As the TTS Tech Portfolio Deputy Director I would like my position documented so that I can have an understanding of what my job duties are. 

## Acceptance criteria

- The responsibilities of Deputy Director have been properly documented
- For a given task, someone would know it would go to the Deputy Director instead of someone else

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
- [ ] Remove items from the Ops Rotation issue template that are now the responsibility of the Deputy

**Comment by JJediny** [comment]
if we document the director's role not sure we'd need to document the deputy role more than as a backup/delegate for said R/R

**Comment by its-a-lisa-at-work** [comment]
@18F/tts-tech-portfolio I've drafted the  [Deputy Director Role](https://docs.google.com/document/d/1B4rtZd06w7ITABrjrGWRjAfU4f-go2jnuO_D0PokJMw/edit#heading=h.ooqzcf2gdmrq) and created some FAQs to go along with it to address `For a given task, someone would know it would go to the Deputy Director instead of someone else` part. If there is anything that I've missed, let me know. Please comment in any area if there is needed clarity or things have been missed. 

Moving to Waiting/Blocked and adding the Feedback Needed label for other folks within the team to review.

**Comment by afeld** [comment]
@JJediny and I have reviewed. Some small edits/comments, but looks good!
