### ISSUE TITLE
clarify organizing principles of our board

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#483]
## Background information

@its-a-lisa-at-work As requested, documenting a few things about the current state of our board that confuse me:

- `Epics` column vs. (non-sprint) Milestones vs. the `epic: ` labels
- `Ready` column vs. `groomed - accepted` label
- What labels are we no longer using, and thus can delete?

I'm going to 🤐 and not micromanage what those distinctions should be. I defer to you. All I ask is that they are clarified, and that we (particularly "I") don't dwell too long on what the changes should be.

## User stories

- As someone creating/managing an issue in a Tech Portfolio repository, I want to understand what labels/milestones to apply when.
- As someone who spends a lot of time in our board, I want the visual noise to be minimized.

## Acceptance criteria

Points of confusion above are clarified, through either:

- Updating the [workflow documentation](https://github.com/18F/tts-tech-portfolio/blob/master/workflow.md)
- Removing them from the board/repository

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
closing in favor of https://github.com/18F/tts-tech-portfolio/issues/469 

forgot to mention to you during our standup that I'm waiting for user stories from you and @JJediny
