### ISSUE TITLE
resolve all outstanding issues in Pegasys

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#487]
## Background information

It seems we have a number of transactions that needed logs, reconciliation, etc. We need to make sure we are caught up before we could potentially hand off to someone else (https://github.com/18F/tts-tech-portfolio/issues/366).

cc @melanienleopold 

## User stories

- As someone responsible for budget/purchases at TTS, I want to ensure they are properly accounted for so we know that we are managing taxpayer dollars responsibly.

## Acceptance criteria

- [x] All Tech Portfolio transactions in Pegasys are `reconciled` through 7/1/2020.
- [x] Any remaining issues have been asked and documented, with invoices and coorespondence on the current state of follow-up.

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by JJediny** [comment]
Old transactions have been reconciled there are now 33 new transactions that need logs/invoices/reconciling remaining to bring Pcard transactions current that issue is being tracked here: https://github.com/18F/tts-tech-portfolio-private/issues/959
