### ISSUE TITLE
As someone submitting security vulnerabilities, I want up-to-date information about how to do so

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#49]
Currently, we have a number of paths/documentation:

- `#incident-response`
- ~~`#vuln-disclosure`~~ - archived
- https://18f.gsa.gov/vulnerability-disclosure-policy/#reporting-a-vulnerability - says "TTS Bug Bounty is on break"
- tts-vulnerability-reports@gsa.gov
- https://hackerone.com/tts

There is definitely overlap - we should consolidate.

- [ ] Update the list of URLs in scope, for the Bug Bounty and broadly - cc #23

cc #31

**Comment by cryptofilegsa** [comment]
Previous efforts have been made to unify some of these, I've sent you @afeld the incident response playbook for Login.gov.

**Comment by afeld** [comment]
- [ ] Clarify the SLAs

**Comment by adborden** [comment]
Re SLAs, here's a document to be updated: https://github.com/18F/bug-bounty/blob/master/project-instructions.md#slas-your-program-must-meet

Bug bounty refers to a 90-day SLA, but _recommends_ 7-day for high, 30-day for medium.
> Though the 90-day SLA above is the only required timeline, we do (strongly) suggest that your program aims for faster remediation of more severe issues.

We might want to align them better with GSA's policies.

**Comment by afeld** [comment]
Clarified this issue to be about incident reporting, while #77 is about triaging and response.

**Comment by adborden** [comment]
https://github.com/18F/bug-bounty is listed as "OUT OF DATE" with a link to this issue. Since bug-bounty is about documenting how to administer the TTS Bug Bounty program, I'm not sure why this issue is related, or why bug-bounty is out of date.

**Comment by adborden** [comment]
What was the resolution here? https://github.com/18F/bug-bounty still links to this issue. Is there a new doc that should be linked instead?

**Comment by its-a-lisa** [comment]
The Public Disclosures of Vulnerabilities site on TTS was updated -- if there are other things that you think need to be addressed, please let me know and we'll create a new card
