### ISSUE TITLE
Add a slack emoji section to our onboarding materials

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#497]
https://gsa-tts.slack.com/archives/CNW3GL70S/p1591204273071500

## AC:
- [ ] Draft list with definitions on how to use/interpret
- [ ] Get others in TTS to give a quick review
- [ ] Publish list in onboarding guide

**Comment by afeld** [comment]
cc https://github.com/18F/handbook/pull/1920#discussion_r434745149
