### ISSUE TITLE
TTS FedRAMP project management tracking

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#498]
## Background information

TTS has had our [TTS Software and Systems Inventory](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0) and GSA IT Security used a tab within their [LiSaaS spreadsheet](https://docs.google.com/spreadsheets/d/1MPMrCWfLX5CTVVI8hysUK8DFEKGgGw2L2W-T1jat4LM/edit#gid=1742590411). 

The part of the org that does the FedRAMP portion doesn't have a place to track their project work. 

I'm thinking as a way to test Smartsheet for an analysis and since the FedRAMP team has a generic WBS -- that they might be a good candidate to test out the capabilities and make a project tracker. 

## User stories

As someone who is the cloud champion and supporting the GSA IT Security office for FedRAMP packages, I would like a place where we can track our work so that there is real time status

## Acceptance criteria

- The FedRAMP agency authorization team has a place that shows the status of every in-progress system
---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
That acceptance criteria isn't super clear to me—I suggest framing it as "The FedRAMP agency authorization team has a place that shows the status of every in-progress system" or something like that.

**Comment by its-a-lisa-at-work** [comment]
Finally got this complete!!! 🎉 

Invited devops@gsa.gov to the workspace.
