### ISSUE TITLE
Determine which assets should be moved from private to public Bug Bounty

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#50]
> There are a number of assets in scope for the TTS Private program which should be moved to the public program.

https://gsa-tts.slack.com/archives/C5JQCD9PH/p1563575399020300

## Programs

- [x] `*.search.usa.gov` - [yes](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1564419727032900?thread_ts=1564419727.032900)
- [x] https://tock.18f.gov - [yes](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1564672984059600)
- [x] www.fedramp.gov and marketplace.fedramp.gov - [yes](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1565979027084700?thread_ts=1564418395.030000&cid=C5JQCD9PH)
- [x] www.usa.gov - [no](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1563803712020500?thread_ts=1563572576.017100&cid=C5JQCD9PH)
- [x] www.code.gov - [yes](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1564435208039600)

## Steps

- [x] Update the Policies
- [x] Update the Scopes

**Comment by rahearn** [comment]
@JJediny It looks like you've done some follow up with the program owners (or at least mentioned them in a thread). Do you have any other info from them other than `usa.gov` seeming to be not ready to respond in a timely manner? tock is in that same boat

**Comment by afeld** [comment]
Checking about Tock and FedRAMP [in Slack](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1564418395030000).

**Comment by afeld** [comment]
Done!
