### ISSUE TITLE
prep for All-Sol Monthly Meeting - due 6/22

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#500]
## Background information

[From Slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1591215795082000):

> a 10-15 minute timeblock at the next Solutions Monthly Team Meeting to share updates/what’s happening in your worlds/cool things you are working on this summer? Additional idea is to share FAQs that you often hear (Can i use zoom? is GEAR up to date? when does the ATO for Trello end? What did you add to the Handbook recently that we answer many of our FAQs?)

## User stories

- As a member of Solutions, I want to know what the Tech Portfolio is up to so that I'm aware of things that might affect me.

## Acceptance criteria

- We have decided on who is presenting
- We have a slide deck ready

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by awichman** [comment]
@afeld Reminder: the All-Sol Monthly meeting is tomorrow :)

**Comment by awichman** [comment]
@afeld All-Sol monthly meeting has been rescheduled to June 23, 1 PM - 2:30 PM ET. I still would have y'all plan on presenting some time around 2 PM ET.

If the new time doesn't work for y'all, let me know, and I'll schedule you for July.

**Comment by afeld** [comment]
That works, thanks!

**Comment by afeld** [comment]
Decks to pull from:

- [Ask Me Anything](https://docs.google.com/presentation/d/1RhIEoLAAbSPNSgNboTfqBrMTQD0E5AbPlegI_MQ5n_0/edit#slide=id.p)
- [Future of the Tech Portfolio](https://docs.google.com/presentation/d/1m47592Ga75ykhApA1GW-sqwqzAVKCHZaaS_U_GPfTYc/edit#slide=id.p)
- [Sprint Reviews](https://docs.google.com/presentation/d/1EAWRVRpE5t-SqLWTLSA8ed2b1MceAQuJrTKjv7CX8Sw/edit#slide=id.p)

**Comment by its-a-lisa-at-work** [comment]
Put [slides](https://docs.google.com/presentation/d/1SvbZcR5vuFUxT3cemAcoIoqc_229niVZch5ogGh1Kr4/edit#slide=id.g6d737156a1_0_0) together and waiting for feedback from others in @18F/tts-tech-portfolio

**Comment by its-a-lisa-at-work** [comment]
slide deck is complete and ready for meeting today; considering this task closed
