### ISSUE TITLE
Write a script to introduce the authorization project and user research to stakeholders

### ISSUE THREAD

**Issue by hoaiandang** [18F/tts-tech-portfolio#502]
## Background information

We want to write a script to introduce the user research process to stakeholders so that they understand the scope of the project and how their experiences are relevant to that documentation.

## User stories

As a member of TTS, I want to understand how this user research will help me get authorization to use SaaS or how my experiences will be relevant to the project.

As a vendor, I want to understand how this user research will help me understand the steps to being authorized for use at GSA initially and in the medium term.

https://docs.google.com/document/d/1ncc0RfaWG8xsCJEjyoX_SXlHMH8Gi3c7VEjMqm3eKd8/edit#

**Comment by afeld** [comment]
Left some comments—nice work!

**Comment by its-a-lisa-at-work** [comment]
Left some comments—nice work!
