### ISSUE TITLE
Familiarize self with Jekyll structure, methods, and best practices

### ISSUE THREAD

**Issue by hoaiandang** [18F/tts-tech-portfolio#503]
## Background information

As a new member, I need to be able to effectively work within a Jekyll environment and make necessary changes to a Jekyll site

## Acceptance criteria

- [x] Understand how to create a site
- [x] Understand how to change layouts
- [x] Understand how to create posts and pages within a site

**Comment by JJediny** [comment]
Totally misinterpreted this new GitHub dependency feature the other way around ^. The intent was to show this issue's completion as a pre-req to starting that work...
