### ISSUE TITLE
triage devops mailing list messages

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#51]
There are a ton of messages that have come in to the devops mailing list over the past couple months - unclear which are important. While doing so, we should also see what we can do to cut down the noise.

https://groups.google.com/a/gsa.gov/forum/#!forum/devops

**Comment by its-a-lisa** [comment]
Recommend claiming [Email Bankruptcy](https://en.wikipedia.org/wiki/Email_bankruptcy) and close this issue

**Comment by afeld** [comment]
Yeah, no longer relevant.
