### ISSUE TITLE
TTS Tech Portfolio - All Hands - Agenda Prep - due 6/26

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#513]
[Draft agenda](https://docs.google.com/document/d/1E_hfRc87gzYwtXzsGI2iTeRg4K9hd-cx9CveBfVRVGM/edit)

## Background information

We've talked about having an All-Hands; we were going to have one in March before everything hit the fan; and now that we're entering the 'New Normal' its a good time to pick these up again. 

## User stories

As a member of the TTS Tech Portfolio, I would like a day that is dedicated just for the team so that I can bond and get other's perspectives on what we're working on. 

## Acceptance criteria

- [ ] [Draft agenda](https://docs.google.com/document/d/1E_hfRc87gzYwtXzsGI2iTeRg4K9hd-cx9CveBfVRVGM/edit) written and has feedback from team

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@18F/tts-tech-portfolio finished the agenda; appreciate any feedback!

**Comment by afeld** [comment]
Looks great! Only change was to make the breaks more regular, so we're not going for more than 90 minutes at a stretch.

**Comment by its-a-lisa-at-work** [comment]
Agenda presented and followed
