### ISSUE TITLE
deactivate inactive single-channel Slack users

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#518]
## Background information

[We have reached the single-channel guest limit](https://gsa-tts.slack.com/archives/C02KW46DP/p1592318148449400), so need to go through and deactivate some single-channel users. Let's do so in a way that solves the problem once and for all: automatically deactivating inactive users to make room for new ones.

## User stories

- As someone who wants to participate in TTS Slack as a single-channel guest (as a partner or member of the public), I want to be able to be added.
- As someone managing Slack users, I don't want to be blocked when trying to add new ones.

## Acceptance criteria

- Inactive single-channel users are deactivated automatically on a recurring basis

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Some APIs that could be handy for scripting this:

- https://api.slack.com/methods/team.accessLogs
- https://api.slack.com/enterprise/scim#delete-users-id

**Comment by its-a-lisa-at-work** [comment]
Mind if we keep this in the Backlog? I think things that are already Sprint Planned for shouldn't go back into Icebox so they stay as something that gets picked up as soon as possible.

**Comment by afeld** [comment]
Changed the title to be a bit more specific, in line with the acceptance criteria.

**Comment by afeld** [comment]
Cleaned up (enough) in other ways; no longer needed.
