### ISSUE TITLE
determine concrete steps for diversity, equity, and inclusion

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#520]
[**Brainstorming doc**](https://docs.google.com/document/d/1uBcrS5f9liTGRKkqksDMQMUEf9bdU1LjISior_7l50k/edit)

## Background information

The sudden public attention around black lives is a good impetus to spend some dedicated time to brainstorm how the Tech Portfolio can improve diversity, equity, and inclusion. How can the Tech Portfolio improve diversity, equity, and inclusion, from [our roles](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/roles.md) and collectively, within the Tech Portfolio and outside of it (at least what’s in our control to influence)?

As Director, I take full responsibility for planning and implementing this, but welcome feedback and help from the team and beyond.

## User stories

- As the Tech Portfolio Director, I want to ensure the Tech Portfolio and TTS are safe spaces for our staff.
- As a member of the Tech Portfolio, I want to ensure that we actively combat systemic racism within TTS (at least) so that we serve all staff and our users fairly and humanely.

## Acceptance criteria

- [x] There is a prioritized list of clear, achievable tasks for the Tech Portfolio, with issues created for the top ones

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
saw this come across my twitter timeline and seems like this blog might contain some suggestions related to this task

https://jenstirrup.com/2020/06/24/i-have-stepped-down-as-a-microsoft-mvp/

**Comment by afeld** [comment]
[Update from 18F leadership](https://gsa-tts.slack.com/files/T025AQGAN/F017X4Q0FFB?origin_team=T025AQGAN)

**Comment by its-a-lisa-at-work** [comment]
Had a meeting with the TTS Tech Portfolio team today; @afeld is going to create issues from the spreadsheet [DI&E improvements brainstorming sheet](https://docs.google.com/spreadsheets/d/1ZBMJKUCluue6jCBHA8QGfKX7z8a7CNtE7BUrEYgGsyw/edit?usp=drive_web&ouid=101998575189840770976&disco=AAAAKD2djQY)

**Comment by its-a-lisa-at-work** [comment]
Yay, created the top issues and put them in an [epic](https://github.com/18F/tts-tech-portfolio/issues/709)!

**Comment by afeld** [comment]
Appreciate it!
