### ISSUE TITLE
group stormdraining

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#524]
## Background information

https://docs.google.com/spreadsheets/d/1083kGc4JVOVaB7dDaOx9tJaTviszUR7wB39bsaoL1is/edit#gid=0

## User stories

Team is stressed
Have too much on our plates
Looking for quick wins
Be more efficient
Need better focus
Getting rid of toil

## User stories
- [ ] Track where team time is spent for a month

## Acceptance criteria

- There are issues created for things we want to streamline / hand off / stop doing / etc.
- 

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/476

**Comment by its-a-lisa-at-work** [comment]
To be discussed at the Director meeting on 7/14 on next steps and way forward

**Comment by afeld** [comment]
- [x] Have group participate in stormdraining exercide
- [ ] Create issues for doing the actual handoffs/streamlining

**Comment by its-a-lisa-at-work** [comment]
Created a follow up [issue](https://github.com/18F/tts-tech-portfolio/issues/614) and will link individual issues to it
