### ISSUE TITLE
plan Juneteenth anti-racism study day - due 6/19

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#526]
## Background information

_While not necessarily a Tech Portfolio thing, adding an issue for capacity tracking._

Friday 6/19 is Juneteenth, and I want to dedicate a good chunk of the day to studying some anti-racism materials and brainstorming what I/we can do about it (https://github.com/18F/tts-tech-portfolio/issues/520).

## User stories

- As a member of TTS, I want to understand systems of inequality and my role in them so that I can work to dismantle them.
- As a participant in the study day, I want to have a clear agenda so that the time is well used and I get as much out of it as possible.

## Acceptance criteria

- [x] Invite others to participate - [Slack thread](https://gsa-tts.slack.com/archives/C02DJFR0V/p1591983229134400)
- [x] Create [an agenda](https://docs.google.com/document/d/1RJ4_6YkB3OLrVxWOP1z1uDgXVPIGHLC6Es_pz9s8a7M/edit#)

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Created!

**Comment by its-a-lisa-at-work** [comment]
@afeld do you want to do a demo of this on Thursday? If so, please use the demo-able label and i'll put it on the agenda

**Comment by afeld** [comment]
I don't know that there's anything to "demo" per se, but happy to talk about what we did.
