### ISSUE TITLE
propose paths forward for Docker Registries

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#555]
## Background information

TTS has been using Docker Hub for pulling and publishing images, but:

- They have been unresponsive to requests about their security practices
- It's a bit unclear whether Docker Hub is being operated by Docker, Inc. (the American company) or Mirantis
   - The latter is originally a Russian company

We want to:

- Evaluate the risk of using Docker Hub
- Understand the alternatives / contingency plans
   - How disruptive they would be to workflows
   - The effort to manage them

## User stories

- As someone responsible for security in TTS, I want to understand the risks of using Docker Hub (directly).
- As someone responsible for supporting engineers in TTS, I want to have Docker/container workflows that allow people to be productive and secure.

## Acceptance criteria

- [ ] Write up the use cases and risks of Docker Hub, some alternatives/contingencies, and their implications
- [ ] Send to the GSA DevSecOps Tiger Team

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
[Notes from discussion about it](https://docs.google.com/document/d/1VmhZ3KI22RJVvOsbK3hTyIdH2DGPc-wyQZvVbvNc5xE/edit#heading=h.oc1bu7djxf8m)

**Comment by its-a-lisa-at-work** [comment]
Moving to Waiting/Feedback until we can get a contact from Docker Hub

**Comment by its-a-lisa-at-work** [comment]
Related [conversation](https://gsa-tts.slack.com/archives/C039MHHF8/p1598287762020600)

**Comment by its-a-lisa-at-work** [comment]
Got a contact from DockerHub yesterday; waiting for Tamara to send the packet to them  to see how far along the SaaS process we can get.

**Comment by its-a-lisa-at-work** [comment]
We were able to get a contact from the security team so this isn't a priority anymore; planned path forward is to move ahead with the SaaS authorization
