### ISSUE TITLE
Create a CONTRIBUTING.md doc for the Tech Portfolio repo

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#556]
## Background information

Tried to review https://github.com/18F/tts-tech-portfolio/pull/544 but got stuck once I opened it locally in Visual Studio Code and went into the terminal and ran `terraform plan` and got the error code that I can run it with `--destroy ` but I'm not sure if I should do that or not. 

It takes a lot of context switching every time I have to do a pull request with terraform that I would prefer not to have to do and rather there be an investment  in documentation. 

## User stories

As someone reviewing pull requests for for terraform that only does it once in a while, I would like some top level instructions on what I need to do so that I don't always have to ask coworkers every time. 

## Acceptance criteria

- [ ] Alyssa can review a terraform related pull request by just reviewing instructions within the repo rather than looking it up on the internet or having to ask someone
- [ ] All members of the TTS Tech Portfolio know where they should be making changes (through Git/GitHub or Terraform)

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Just FYI that you won't be able to `terraform plan`/`apply` locally due to the state file living on my machine. This is not a great situation, and is one of the problems https://github.com/18F/tts-tech-portfolio/issues/443 is meant to solve.

**Comment by its-a-lisa-at-work** [comment]
ahhhhhhhhhh --- nooowwwwww I get it

**Comment by its-a-lisa-at-work** [comment]
@afeld do you think we'll still need instructions on how to contribute to a terraform pull request once we enable CI/CD? If not, than happy to close this item.

**Comment by its-a-lisa-at-work** [comment]
@jacobian started a [good discussion thread](https://twitter.com/jacobian/status/1291808757744312321?s=20) on twitter about the nuances of how reviewing pull requests for terraform is different than typical code/documentation

**Comment by its-a-lisa-at-work** [comment]
Reopening based on the coworking session that we had this week

**Comment by afeld** [comment]
Merging into https://github.com/18F/tts-tech-portfolio/issues/851.
