### ISSUE TITLE
General Request form procedures

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#557]
[Discussion Document](https://docs.google.com/document/d/1wtRdCwBbHR_DMj7G-LJ-7ghgav6JYkRBhHNmVI8uYks/edit)

## Background information

There are 3 new requests in the General Request form since the beginning of June and as the person on OpsRotation, I'm not sure how to handle these. 

Probably relates to https://github.com/18F/tts-tech-portfolio/issues/475

## Acceptance criteria

- All team members know what to do when they are on OpsRotation and there is a new entry in the General Request form

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
I think we should consider deprecating it in favor of Slack messages or emails.

**Comment by afeld** [comment]
[Discussion notes](https://docs.google.com/document/d/1wtRdCwBbHR_DMj7G-LJ-7ghgav6JYkRBhHNmVI8uYks/edit)

**Comment by JJediny** [comment]
Should be able to close this once https://github.com/18F/handbook/pull/2093 is reviewed/merged

**Comment by afeld** [comment]
- [ ] Remove from [Ops Rotation checklist](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/ops.md#other)

**Comment by JJediny** [comment]
Closed out and/or moved the remaining requests to slack. Form is no longer accepting responses and handbook edits to remove references to it are in progress:
https://github.com/18F/handbook/pull/2093
https://github.com/18F/handbook/pull/2091

and opsrotation:
https://github.com/18F/tts-tech-portfolio/pull/768

**Comment by JJediny** [comment]
conflicting PRs merged closing
