### ISSUE TITLE
move (some) usa.gov assets from private to public bug bounty program

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#564]
https://docs.google.com/document/d/1GXZv35ylMxN36_tObLQrstVZitSvsH57hRbGEXEtN5U/edit#

## Background information	
In attempting to move www.usa.gov from the private to public program, that opened a can of worms. 
[Most recent conversation.](https://gsa-tts.slack.com/archives/C5JQCD9PH/p1580228739001800?thread_ts=1563572576.017100&cid=C5JQCD9PH)

## User stories	

Would like to expand the scope of www.usa.gov to include more usa.gov assets but since they don't own all of them, using *.usa.gov is not feasible and each system would need to be indicated separately. 

## Implementation	

- [x] work with usa.gov to understand if the following has changed
  - [x] usa.gov has a developer on board so vulns get remediated in the allotted time
  - [ ] if usa.gov has figured out what their hosting looks like
- [ ] work with usa.gov related TTS programs to get them under
  - [x] analytics.usa.gov
  - [x] epa-notice.usa.gov 18F
  - [ ] feedback.usa.gov 
  - [x] participation.usa.gov
  - [x] standards.usa.gov 
- [ ] update HackerOne
  - [ ] put the following assets in the private program 
   - [x] owned by usa.gov:  1.usa.gov, blog.usa.gov, go.usa.gov, labs.usa.gov, www.usa.gov	
   - [x] usa.gov redirects: business.usa.gov, gobierno.usa.gov, kids.usa.gov, publications.usa.gov, vote.usa.gov, connect.usa.gov 

## Acceptance criteria	
- Determine which assets from usa.gov are going to be moved from the private to public program
- Scope document page on HackerOne is updated

**Comment by its-a-lisa-at-work** [comment]
moved to waiting/feedback because meeting got pushed to next week

**Comment by its-a-lisa-at-work** [comment]
Met with Russel yesterday and got additional information about what is feasible; started a document to get additional clarity and as a way to ask other folks within TTS if they approve; 

moving into Waiting/Feedback until I hear back from them or 3 days has passed; whichever is sooner.

**Comment by its-a-lisa-at-work** [comment]
Closed this out with H1 today; they are going to update the page.
