### ISSUE TITLE
revisit how to handle p-card limit for software

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#568]
## Background information

In consolidating the p-card purchasing of various SaaS in TTS, we repeatedly hit the $10k p-card limit. Some recent examples:

- GitHub
- Nessus
- ZenDesk

Some options:

- Convert these to contracts
   - @stephencarroll offered to start a list of the things that we would want to buy that aren't on Schedule
- Re-negotiate the $10k limit applied across TTS (as opposed to per program)

## User stories

- As some with software needs, I don't want to be constrained in my usage by a magic dollar threshold.

## Acceptance criteria

- We have a clear plan for how to avoid this problem in general, and what to do with current software where we are hitting the constraint

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by stephencarroll** [comment]
### List
(list is not for reflecting a brand name preference, but rather competitive commercial solutions not easily acquired via GSA Schedules)

- Zendesk
- Hubspot
- UserTesting

**Comment by stephencarroll** [comment]
### Policy Doc
GSA Order 4200.1A (Jan 7, 2015)

### Acq Regulation Site
513.301 Governmentwide commercial purchase card.
      (a) GSA Order, **Guidance on Use of the Credit Card for Purchases (CFO 4200.1)**, establishes procedures for using the Governmentwide commercial purchase card to make purchases and payments

### What it says

See page 17, Section 9.j. - Split Transactions

> A split transaction is the division of a purchase into two or
more transactions to stay within authorized single transaction limit. Micro-purchase
cardholders and warranted contracting officers are strictly prohibited from splitting
purchases to circumvent their purchase card limits. OAS will revoke the charge card
privileges of any cardholder who violates this policy. Cardholders and their approving
officials who participate in split transactions will also be subject to disciplinary action in
accordance with GSA Order, CPO 9751.1 Maintaining Discipline. An example of a split
transaction is as follows:
A micro-purchase cardholder receives an authorization to purchase audio visual
equipment costing $4,000. The cardholder makes a payment of $2,000 on one
day and $2,000 on a following day. The $4,000 exceeds the micro-purchase limit
of the cardholder.
Purchases for individual training classes or registration fees for conferences should be
considered as discrete transactions. For example, if a cardholder is paying for a
training class for two individual employees and each requires registration, treat each
training class as two separate purchases.

### Why this definition isn't applicable to TTS' current usage
TTS is made up of various individual program offices ([at last count](https://docs.google.com/presentation/d/10Qfq1AaQh74q76Pik99kQedvshLBo0qLWZGsH-nrV0w/edit#slide=id.g70b00d154c_1_0), Solutions alone had 14 individual offices), and all of these offices have to use one purchase card maintained by the Tech Portfolio.

Each program office has their own individual needs at distinct times. When program offices happen to use the same tool, these are distinct needs, not in the spirit of the example shown in the policy doc of getting around a total $$ limit.

**Comment by stephencarroll** [comment]
Related to the above, I also reviewed the other policy docs listed at the bottom (OMB, Treasury, etc) and I could find no additional guidance or other examples of split purchases.

It all goes to intent. If someone is truly trying to skirt the limit, they cannot be approved and is against appropriate processes.

However, if program offices need a tool, unbeknownst to other offices, or occurring at time points in the year due to specific needs, that, imo, is not splitting purchases. It's distinct needs.

**Comment by afeld** [comment]
Got concurrence from @HuixianXu [in Slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1594820787088700?thread_ts=1594819114.080100&cid=CNW3GL70S), so considering this closed. Thanks all, and excited this will make our lives much easier!

**Comment by melanienleopold** [comment]
@michellepetryszyn
