### ISSUE TITLE
Update Bio - due 7/14

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#575]
## Background information

OSC has asked for us to make sure we review and update our bios.
Please review your bio by Tuesday, July 14th and add your bio’s link to this [document](https://docs.google.com/spreadsheets/d/1QUeodBn_hkCiUfxb8xIsMXxoyxXAorpK3B6ujLQ45ZQ/edit#gid=0).

## Acceptance criteria

- Bio is Updated

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
- [x] @afeld 
- [ ] @its-a-lisa-at-work

**Comment by its-a-lisa-at-work** [comment]
Updated bio and commented with link
