### ISSUE TITLE
Determine canonical source of How We Work documents

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#576]
## Background information

https://github.com/18F/tts-tech-portfolio/pull/533

## User stories

As a new person coming into TTS Tech Portfolio, I want to go to a single point to have an up to date idea of what the team looks like so that I don't have to be confused and not know what is going on. 

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Is this issue still relevant, given https://github.com/18F/tts-tech-portfolio/pull/574?

**Comment by afeld** [comment]
I think the short answer to this is "in this repository, on our Handbook page, or linked from one of those."
