### ISSUE TITLE
As a team in TTS, I want to keep informed about Tech Portfolio goings-on

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#58]
There used to be [a recurring Infrastructure Leads meeting](https://docs.google.com/document/d/1G03trzrQez5BupOLfuZUJy-boooc1Z9oYj21LYTw4cs/edit) - we should consider if that would be a good thing to reinstate, or if there are other (less synchronous?) ways of communicating out/in.

**Comment by annepetersen** [comment]
Update: feedback occurred in Slack. Right level of info; "super helpful!" even.

**Comment by its-a-lisa** [comment]
Consider closing since we have brought these back.
