### ISSUE TITLE
DRAFT staffing issue: TTS - Resolving Vulnerable Dependencies - 40 hours

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#59]
Wasn't sure what Chapter and Phase labels are appropriate. This _can_ be a `MICROREQUEST` - I'm flexible on how the hours get spread out. Part of https://github.com/18F/tts-tech-portfolio/issues/48.

---

**Project Description**

TTS has a lot of code repositories, and a lot of them have dependencies on packages that have (since?) identified security vulnerabilities. We need to do better as an organization at keeping on top of that. This staffing request is for a backend engineer to do a spike:

- See how far we can get in one-time effort to mitigate that issue long-term
- Identify future steps for improvement

[More details.](https://github.com/18F/tts-tech-portfolio/issues/17) No travel required. Tock line will be [`OPP / Infrastructure Support`](https://tock.18f.gov/projects/1069/) (note there seems to be inconsistency in the name of that one across various places).

**Timeline**

Required:

- Duration of engagement: 40 hours, all at once or spread over multiple weeks
- Last date on which work can be done per the agreement: 1/31/20

**Skill type(s) needed**

- [ ] Back end engineer
  - Number of weeks this role is needed: flexible
  - Hourly commitment per week: flexible

**Prior to closing this issue**

- [ ] Ping @abrouilette that the issue is ready to close, so he can update some things.

**Comment by afeld** [comment]
Holding for [confirming that OPP is ok with this](https://gsa-tts.slack.com/archives/C3UJG8X4P/p1564067323001000).

**Comment by thecapacity** [comment]
@afeld We probably need to be cautious of the IAA scope on this one - i.e. even though there's a Tock line it may not be appropriate given the way the ask is scoped, i.e. TTS wide. For example, depending on the IAA scope, it may not be appropriate for OPP funds to be used to resolve issues across all TTS repositories (e.g. 18F repositories that were built for ASF clients).

Happy to discuss further - I can't get into Tock to check, and I don't know what IAA that line's assigned to at the moment.

@abrouilette do you have an easy way of tracking from Tock to IAA? I don't seem to be able to tag Leah in this thread

**Comment by afeld** [comment]
@thecapacity I have been talking with @JJediny @hkdctol and Cynthia Gilbert about it - see [the most recent Slack thread](https://gsa-tts.slack.com/archives/C3UJG8X4P/p1564067323001000).

**Comment by afeld** [comment]
Closing for now.
