### ISSUE TITLE
groom Infrastructure issues

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#6]
https://github.com/18F/Infrastructure/issues

- [ ] Move non-sensitive ones here
- [x] Close ones that are no longer relevant

**Comment by its-a-lisa** [comment]
@afeld I am removing any infrastructure issues from the https://github.com/orgs/18F/projects/11?fullscreen=true because we can't add the new labels to them since the repository has been archived. If they are still relevant, please move them here.

**Comment by afeld** [comment]
Done!
