### ISSUE TITLE
As a system included in the Bug Bounty, I want my source code to be in scope

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#61]
@pburkholder pointed out that only some of the systems in scope for the Bug Bounty have their source code included:

https://hackerone.com/tts#scope

I don't see a reason not to include the source code for all systems that are in scope.

- [x] cloud.gov
   - https://github.com/cloudfoundry-community/uaa-credentials-broker
   - https://github.com/18F/cf-service-connect
   - https://github.com/18F/cg-uaa-extras
   - https://github.com/18F/cg-sandbox-bot 
- [ ] ~~https://github.com/GSA/search.digitalgov.gov and https://github.com/GSA/search-gov~~ - [waiting until early 2020](https://gsa-tts.slack.com/archives/CG8SNAEQM/p1564502955044500?thread_ts=1564496468.038300&cid=CG8SNAEQM)

cc #60

**Comment by afeld** [comment]
@brittag [checking on what cloud.gov repos should be in scope](https://gsa-tts.slack.com/archives/CG8SNAEQM/p1564503828045000?thread_ts=1564496468.038300&cid=CG8SNAEQM).

**Comment by JJediny** [comment]
https://github.com/18F/before-you-ship/pull/398

**Comment by afeld** [comment]
Closing as not actionable right now.
