### ISSUE TITLE
Coworking: Initiative and Epic creation

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#613]
## Background information

We have identified Initiative owners and now the next step is to build out the initiatives.

## User stories

As the Project Manager for the Tech Portfolio, I would like to provide some dedicated time to help folks think through the initiatives that they own so that we can start building out epics and a roadmap. 

As an Initiative Owner, I would like some help from the Project Manager to think through my initiative so that I don't have to do it by myself.  

## Acceptance criteria
- [x] Project Manager schedule time with each team-member to build out their Initiative with the desired outcomes and key results
- [x] Project Manager coworks with each team member
  - [x] @afeld
  - [x] @jjediny

## Acceptance criteria

- Each team-member has built out their Initiative with Epics
- Each Initiative has the known work represented on our Project Board

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Acceptance Criteria could be more specific: What does "built out" mean?

**Comment by its-a-lisa-at-work** [comment]
Had meetings and started the `Infrastructure Management` and `Mac` Initiative roadmpas
