### ISSUE TITLE
redirect decommissioned sites to archive.org

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#619]
Right now, we redirect most of our [decommissioned](https://before-you-ship.18f.gov/infrastructure/decommissioning/) static sites to the corresponding GitHub repositories. I imagine this is confusing to users, especially if they aren't developers, because they wouldn't know where to look for the content, and it's certainly not easy to use since the navigation and layout is gone. A better experience would be to redirect to the last (good) capture on archive.org, at either

- `https://web.archive.org/[URL]` - latest capture
- `https://web.archive.org/web/[timestamp]/[URL]` - specific point in time

archive.org isn't a government site, but I don't think that means we can't do it. Let me know if you know otherwise.

cc @amirbey, @thebestsophist, [related "Sunset Vault" 10x project](https://trello.com/c/gZTZcR22/52-the-sunset-vault) where this idea came up

**Comment by afeld** [comment]
> is this something that we're doing or that we're watching?

We would do it, presumably.

> If we're doing, could we move over to the TTS Tech Portfolio repo for better issue tracking?

Done.

**Comment by JJediny** [comment]
https://github.com/18F/dns/issues/412

**Comment by afeld** [comment]
Would be nice, but bot planning to tackle in next six months, so closing.

**Comment by afeld** [comment]
Noting in case someone else stumbles upon this thread: Library of Congress has a [Web Archiving](https://www.loc.gov/programs/web-archiving/about-this-program/) program that may serve the need.

**Comment by afeld** [comment]
[Archive-It](https://archive-it.org/) is another.
