### ISSUE TITLE
end-of-fellowship review for Hoaian - due 8/7

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#628]
### Documentation
[Review](https://docs.google.com/document/d/1Sm5PSdDdAwXiCTSMUo1z7yzCc0o_5M3AKvj-U_haHXU/edit)

[Self-reflection](https://docs.google.com/document/d/1vcQnx-GNTCPm2O-g_UJXI9CjKfSlc8Mp2TdDs4aXdv8/edit)

## Background information

Follow-up to https://github.com/18F/tts-tech-portfolio/issues/573.

## User stories

- As a staff member, I want to understand if/how my performance has progressed since my last review.

## Acceptance criteria

- @hoaiandang has been sent written feedback and numeric values for each performance measure (as applicable)
- We met to talk through it

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Should I be assigned to this as well?

**Comment by afeld** [comment]
@its-a-lisa-at-work If you have the bandwidth to take a first pass at filling out the Performance Measures, that would be great.

**Comment by afeld** [comment]
- [ ] @hoaiandang Do a written self-reflection, either in the Performance Measures structure, or just a couple of paragraphs (you can timebox to 30 mins or so)

**Comment by its-a-lisa-at-work** [comment]
@hoaiandang let me know when you've done the above; preferably by 8/5

**Comment by its-a-lisa-at-work** [comment]
@afeld finished my first pass; admittedly the grammar is awful. Hope to get back to it in the next few days to improve it; but realistically it might not happen. I'm going to unassign myself for now.

**Comment by hoaiandang** [comment]
@its-a-lisa-at-work finished the self-reflection!

**Comment by afeld** [comment]
@hoaiandang Thanks! Working through clarifying some parts of the review, but we'll try and get to you by the end of the day.

**Comment by afeld** [comment]
And thanks for writing up that reflection; exactly what I was looking for, thanks!

**Comment by afeld** [comment]
Very helpful for when we host people in similar roles in the future.

**Comment by afeld** [comment]
We have the meeting set for tomorrow, so going to go ahead and close this.
