### ISSUE TITLE
create Performance Profile for Shared Engineer - due 7/31

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#643]
https://docs.google.com/document/d/116sCiYwDWGH0hJ3_ifRq3z34zGHzPsz9G1iFBXEBBhU/edit

## Background information

From @LeighFinkel [in Slack](https://gsa-tts.slack.com/archives/G014S6FS9RA/p1595262758029400):

> massage the description you already created for [the internal posting](https://docs.google.com/document/d/1I4dRjWj9OzuuFQJvGppnMCojFsseHLqPPc7pc-IDTbw/edit) into one for sharing externally - like [this one](https://docs.google.com/document/d/1V9T7NrexD_UP8qQmWcGJGRcSRUdr_pHzjXAsm-rtQ9I/edit)

## User stories

- As someone considering TTS job openings, I want to understand what I would be applying for.

## Acceptance criteria

- [ ] Performance Profile has been approved by Talent

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Is there a due date for this?

**Comment by afeld** [comment]
Not a hard due date, but it's a blocker for Talent, so sooner the better.

**Comment by its-a-lisa-at-work** [comment]
I suggest we create an internal due date to help with prioritization

**Comment by afeld** [comment]
Done.

**Comment by its-a-lisa-at-work** [comment]
@JJediny do you have a thumbs up on this?

**Comment by afeld** [comment]
- [x] Resolve first round of feedback
- [ ] Writing Lab review
- [ ] Resolve feedback from them

**Comment by afeld** [comment]
This is on hold until further notice, so closing.
