### ISSUE TITLE
clarify how to handle p-card segmentation - due 12/8

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#644]
## Background information

Follow-up to #568. We now have consensus within TTS that purchases for the same product for different programs should be considered distinct purchases (as opposed to split transactions). The question now is how to do so in a way that doesn't raise constant false alarms from the p-card office.

## User stories

- As a p-card holder, I want to avoid having to justify transactions that are legitimate.
- As someone in the p-card team, I want to ensure that the p-card isn't being abused through split transactions.

## Acceptance criteria

- [x] We have consensus with the p-card office about how to handle transactions that add up to over $10k for a single vendor across multiple programs
- [ ] we have official correspondence supporting it from GC/Leadership  

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Holding for https://github.com/18F/tts-tech-portfolio/issues/787 to be completed first.

**Comment by melanienleopold** [comment]
Cleaned up [old doc ](https://docs.google.com/document/d/1LxkTsQPA4v4ZpJNpJcnSBX07WVxQQwfVtXKx236EfEU/edit#) with the new process. Still finishing it up and redoing the diagram, but will be ready for tomorrow's meeting.

**Comment by melanienleopold** [comment]
Documentation is finished. Having one more meeting 10/15 to sort out the logistics of changes needed to the Google sheet.

**Comment by melanienleopold** [comment]
Meeting with Ethan 12/22 to make changes to the micropurchase spreadsheet.

**Comment by melanienleopold** [comment]
@afeld this issue is different than what I thought it was. Do you have the correspondence from Legal on this that we can document somewhere? I don't think I was a part of those conversations.

**Comment by afeld** [comment]
I think https://github.com/18F/tts-tech-portfolio/issues/568#issuecomment-658752037 and following messages and things they linked to is everything I had. Not sure that we ever talked to Office of General Counsel about it, as it sounded pretty cut-and-dry at the time. We can certainly triple-check by reaching out to them.

**Comment by melanienleopold** [comment]
@michellepetryszyn and I sent an email to OGC for concurrence.

**Comment by melanienleopold** [comment]
Response from OGC:
[Split purchase question](https://drive.google.com/file/d/1aqiioqBy3_lnrVqpvj0pkyKKEMaQDKHV/view?usp=sharing)
[https://drive.google.com/file/d/134hYensPyahhcnET279LG-1glZDr29Jd/view?usp=sharing](url)
OGC did not give clear concurrence. However, the guidance given aligns with what we were told before.
