### ISSUE TITLE
free up Adobe licenses

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#645]
## Background information

https://trello.com/c/meU2dYBh/209-adobe-creative-cloud-licenses

TTS pays GSA IT for licenses of Adobe Photoshop / Creative Cloud, and we have run out. We believe many aren't actually in use, so plan to confirm that and then reclaim some.

## User stories

- As someone doing design work at TTS, I want access to tools to do so.

## Acceptance criteria

- [x] We have Creative Cloud and Photoshop licenses available for atleast 3 months ahead onboardees

**Comment by its-a-lisa-at-work** [comment]
Can you say more about the implementation? 

Instead of an arbitrary number of 15; do we want to anchor it based on a functional area? Like ... enough so that 1 license for every 3 Designers & Outreach folks ?

**Comment by JJediny** [comment]
@its-a-lisa-at-work ^ Took a quick stab to meet minimal to meet accepted

**Comment by its-a-lisa-at-work** [comment]
Thanks @JJediny much better!!

**Comment by afeld** [comment]
That works.

**Comment by afeld** [comment]
Waiting on Software License Management group.

**Comment by afeld** [comment]
They still plan to do some cleanup, but it sounds like this is no longer a blocker.
