### ISSUE TITLE
complete Capability Assessment Phase 1 - due 8/5

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#650]
## Background information

The GSA Office of Human Resources Management (OHRM) wants to understand where employees are at in terms of capabilities, and what supervisors are looking for, to identify gaps.

- [Presentation](https://drive.google.com/file/d/1XLLuEFLTYP8_oscRobFWIxTquTcBBHj7/view?usp=sharing)
- [One-pager](https://docs.google.com/document/d/13iFwo8DuAKRcz8VFZhznue9C6M-6S3wr4O8BS0QHNYI/edit)
- [Drive folder](https://drive.google.com/drive/folders/1m8j42GZYCR1zbwVHtZvvEDCT6uiBDvOJ)
- [Form](https://forms.gle/wuLq7zdzYwd5DCAr8)

## User stories

- As someone responsible for staffing at GSA, I want to ensure the needs of the positions are being met so that the agency's work can get done.

## Acceptance criteria

- Submit Google Form

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Are there implementation steps of meeting with team members or is this something that doesn't require our input?

**Comment by afeld** [comment]
Unclear.

**Comment by afeld** [comment]
- [ ] Review documentation and expand on implementation steps

**Comment by afeld** [comment]
Told them I need a few more days.

**Comment by afeld** [comment]
Expanded the description a bit. The [one-pager](https://docs.google.com/document/d/13iFwo8DuAKRcz8VFZhznue9C6M-6S3wr4O8BS0QHNYI/edit) goes into more detail.

**Comment by its-a-lisa-at-work** [comment]
Thank you! That really helps greatly and provides a lot of clarity. 

Question specific to the TTS Tech Portfolio -- are the two IT Specialist roles (me and @JJediny ) expected to have the same capabilities or will they differ from each other?

**Comment by its-a-lisa-at-work** [comment]
Another thought -- as a Tech Portfolio -- are there any cross the board capabilities that we'd expect from all people within TTS that we'd add? For instance -- GitHub, Google Sheets, Slack ... ?

**Comment by afeld** [comment]
> are the two IT Specialist roles (me and @JJediny ) expected to have the same capabilities or will they differ from each other?

Appears it's filled out per person.

> are there any cross the board capabilities that we'd expect from all people within TTS that we'd add? For instance -- GitHub, Google Sheets, Slack ... ?

This exercise doesn't go into that level of detail.

**Comment by afeld** [comment]
Ok, filled out the worksheet! I have a much better understanding of the task now that I've done it. The short version:

1. Review the [Capability List](https://docs.google.com/spreadsheets/d/1FSi_1PvTR6CO_ZUTR9c4jR8a6aJANJ03w_X_U-GgryE/edit#gid=260781910).
1. Pick five (that aren't `Fundamental` or for `Supervisor`s or whatever) for the [Team Capabilities](https://docs.google.com/presentation/d/1qRzXYWaHbF1YTZzG7sXZctD-hKrtvkygi5rZ8HQATiI/edit#slide=id.g902306b5ae_0_65).
1. On top of the five `Team Member` Capabilities, pick up to five more that each "Position[/FTE] requires".
   1. Indicate the [`Proficiency Level`](https://docs.google.com/spreadsheets/d/1ALXtAsVmj1hf0YkaNz5cbWAQ1y0uZtXZsWO3XrEZ0Y8/edit#gid=1578535080) that each Position should have for each of those selected Capabilities.
1. Submit the `Team Member` ones via [the Google Form](https://docs.google.com/forms/d/e/1FAIpQLSe9a91JyWx0SezxdWwBPhiz0cVD_F21nGnzhDTswYblFod1ig/formResponse).

@its-a-lisa-at-work @JJediny I welcome feedback, but a) am overdue and b) don't want [us] to spend much more time on this. Will plan to submit the Google Form tomorrow morning, though I'm happy to discuss at one-on-ones or whatever ever after submitted.

**Comment by its-a-lisa-at-work** [comment]
@its-a-lisa-at-work I'm confused, does it need our 👍 or are you showing it to us as a courtesy?

**Comment by afeld** [comment]
The latter, since you had expressed interest.

**Comment by afeld** [comment]
Submitted.
