### ISSUE TITLE
review SaaS authorization discovery deck - due 7/28

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#651]
## Background information

https://docs.google.com/presentation/d/1Ma7PQqGMuCvCR5JSUNxakfYgBvt09ZmRbcXaWdasII4/edit#slide=id.p1

Random notes to self to expand on:

- Lay out the stakeholder groups earlier
- FedRAMP CSPs
- Split up slide with lots of text
- Suggest "will go through and do questions at the end"
- Tighten up the time
- Clarify FedRAMP frustration slide
- Include screenshot of VA site

**Comment by afeld** [comment]
@hoaiandang Done!

**Comment by its-a-lisa-at-work** [comment]
Going to reopen this until I review it as well; will un-assign you @afeld

**Comment by its-a-lisa-at-work** [comment]
totally forgot that I already made comments
