### ISSUE TITLE
determine how to present SaaS discovery findings - due date 7/29

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#652]
## Background information

We have the deck; will send to stakeholders and ask if they would like to have it presented, or just get time to talk through it, etc.

**Comment by its-a-lisa-at-work** [comment]
Is there any entrance criteria/implementation steps of the doc being updated before this happens? Is there a time that you'd need the doc done by? 

Missing related document 'the deck'

**Comment by afeld** [comment]
> Is there any entrance criteria/implementation steps of the doc being updated before this happens?

I think it can happen in parallel.

> Is there a time that you'd need the doc done by?

Ideally before @hoaiandang times out, I suppose.

**Comment by afeld** [comment]
We'll email the deck and ask who wants to meet to talk through it.
