### ISSUE TITLE
TTS Tech Portfolio - August All Hands Due Date - 8/20/20

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#656]
## Background information

Next TTS Tech Portfolio All Hands is 8/26/20. Should have the meeting prepared ahead of time. 

## Acceptance
- [ ] All hands scheduled
- [ ] Agenda drafted and attached to invite

**Comment by afeld** [comment]
This seems larger than a task, and would benefit from Acceptance Criteria.

**Comment by its-a-lisa-at-work** [comment]
Cancelled this month's because there is a major conflict; moved it to the next month and made it a reoccurring meeting
