### ISSUE TITLE
TTS Tech Portfolio -- Vision/Mission Statement

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#660]
## Background information

There have been a few things recently (Deluca Roamap, TTS Vision update, etc) that make us bring up our Vision/Mission statement. 

## User stories

As someone in the TTS Tech Portfolio, I am constantly confused about what is in-scope; I would like for the Vision/Mission Statement to be updated so that I have better clarity on what we're doing

## Acceptance criteria

- We have an updated, relevant and agreed upon Mission/Vision statement that accurately reflects the TTS Tech Portfolio and can be used when necessary

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
A few goals for this, when we get to it:

- Plain language
- Inspirational
- Aspirational

Some phrases that come to mind:

- "Make TTS more productive and secure"
- "Be 'a rising tide that lifts all boats'"
- "Serve TTS, and have positive impact far beyond"

**Comment by afeld** [comment]
[Notes from All Hands](https://docs.google.com/document/d/1hmjgSZXLXcY7pvS-0R-7dkp4zmzykgt9Pv3YRCHgECc/edit#heading=h.va5dc2u9lpuv)

**Comment by afeld** [comment]
Outreach will join to help us work through this on 11/12.

**Comment by afeld** [comment]
[Draft.](https://docs.google.com/document/d/1hmjgSZXLXcY7pvS-0R-7dkp4zmzykgt9Pv3YRCHgECc/edit#bookmark=id.kd54cluzay3q) Waiting on feedback from the team.

**Comment by afeld** [comment]
@its-a-lisa-at-work added herself; adding @amitfreeman-gov as a reminder to review.

**Comment by its-a-lisa-at-work** [comment]
Added my comments, taking my name off

**Comment by amitfreeman-gov** [comment]
The document looks pretty comprehensive.  With respect to the mission statement itself +1

**Comment by afeld** [comment]
Want to thank everyone for the input on this. Going with the following:

**Mission:** We exist to make TTS more productive and secure, empowering our staff and programs to better deliver on their missions.

**Vision:** We strive to make TTS the model for how to do IT in government: human-centered, transparent, and as a force-multiplier for the organization(s) we serve.

They aren't perfect, and they aren't locked in stone, but happy to have something to rally around 🎉
