### ISSUE TITLE
Verify we're using LetsEncrypt for all the certs and not other cert providers Due Date - 9/15

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#663]
## Background information

While reviewing the SaaS Inventory list, it was unclear whether or not we are solely using Lets Encrypt for our certificate authority or if we are still using some legacy certificate providers. 

## Acceptance criteria

- [ ] Certainty that we aren't using other certificate providers that will need to be ATOd

**Comment by JJediny** [comment]
The micropurchase sheet will show all cert requests dating back to FY19

**Comment by its-a-lisa-at-work** [comment]
I jumped ahead and did this to support https://github.com/18F/tts-tech-portfolio/issues/720 

Results:
- one program using DigiCert through GSA
- one programs using SSLMate passively
-  no programs using CertiPath
