### ISSUE TITLE
Action Required for New Relic Agents to use new Endpoint - due by July 30th

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#673]
## Background information
```
Dear GSA TTS New Relic User,

My apologies if you missed the previous notices re: requirement to configure New Relic agents for dedicated FedRAMP Moderate Endpoint by July 30th.  This takes a few minutes ...Instructions attached and we are available to help.

IMPORTANT: After July 30th, the FedRAMP PMO has asked New Relic to stop reporting to the old endpoint for .gov users.   

If you haven't made the change or can't make the change prior to July 30th and wish to continue with the old endpoint we require an acknowledgement  (respond to this email) stating that you understand the old endpoint will no longer be FedRAMP certified and you require more time to make the change.

If you choose not to make the agent configuration change or send an acknowledgment the old agents will stop reporting after July 30th.
```
## Related Information or Documentation

**We notified the known largest users/programs:**
- [x] "api.data.gov" <api.data.gov@gsa.gov>, 
- [x] Touchpoints Support <touchpoints-support@gsa.gov>
- [x] federalist-support <federalist-support@gsa.gov>
- [x] datagovhelp@gsa.gov <datagovhelp@gsa.gov>
- [x] identity-devops@login.gov

**these programs responded back to confirm their awareness to remedy**
- [x] "api.data.gov" <api.data.gov@gsa.gov>, 
- [x] Touchpoints Support <touchpoints-support@gsa.gov>
- [x] federalist-support <federalist-support@gsa.gov>
- [x] datagovhelp@gsa.gov <datagovhelp@gsa.gov>
- [x] identity-devops@login.gov

**Confirm other usage**
- [x] tech portfolio to review new relic insights/dashboard to identify other users/teams to notify
    - [ ] missed tock
    - [ ] missed search.gov
    - [ ] datagovhelp@gsa.gov didn't manage to get directly to their engineers *might need an updated inbox based on https://docs.google.com/spreadsheets/d/1zHWUPcTnsD47enyGnq_buwAk98vfbGAwdzNJ381_5JA/edit#gid=2090999198
- [x] new relic to provide a list of applications still using the old endpoint

**Comment by JJediny** [comment]
@afeld any additional teams/channels come to mind (particularly within 18f)?

**Comment by afeld** [comment]
I have no idea.

**Comment by JJediny** [comment]
Remaining New Relic deployments using the old endpoint based on email received 7/30/2020 from new relic support team:

<img width="733" alt="Screen Shot 2020-07-30 at 8 01 21 PM" src="https://user-images.githubusercontent.com/6350035/88986914-4efd9d00-d2a2-11ea-9398-7a7c94a8c36d.png">

- [x] emailed search.gov team / login / touchpoints / others listed are aware

**Comment by JJediny** [comment]
- [x] Search.gov has confirmed their switch over
- [x] login team is aware and following up per individual dev domain 
- [x] met with analytics team to close out their switch over 
- [x] no remaining usage on the old endpoint reported
