### ISSUE TITLE
Board Automation

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#676]
## User stories

As someone who is doing reoccurring activities, I would like for there to be an easier way to generate and track those tasks so they could be reflected on our board. 

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/882.
