### ISSUE TITLE
Increase security research engagement on Bug Bounty Platform

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#677]
## Background information

Currently, we have up to 300 items triaged with our plan and we aren't getting close to that number; we should work with outreach to assure that folks know that our program exists and increase our engagement and visibility of our program

## User stories

As someone who is doing reoccurring activities, I would like for there to be an easier way to generate and track those tasks so they could be reflected on our board. 

## Acceptance criteria

- [ ] Way forward to better utilize the program

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/641

**Comment by its-a-lisa-at-work** [comment]
Mentioned this to Kristina B. and the outcome will be the following:
- [ ] Determine way forward for Bug Bounty program and the longevity of it
- [ ] Set up meeting with H1 after above is accomplished

We talked about the following activities that outreach could support on
- Twitter account
- Hacker of the Month
- Monthly one-pager

The outcome is that getting a Twitter account is difficult and we'd want to make sure that this is something that wouldn't die immediately; so Alyssa will mention this to GSA to see if it is something they would like to take on and feature TTS until they get things going. The Hacker of the Month will need to be run by legal since there are potential conflict of interest and the monthly one-pager might be good for the Service Catalogue as a web page. 

Going to close this card and will create a new one if/when the meeting is schedule based on the mentioned blocker is figured out from #817
