### ISSUE TITLE
plan for large upcoming SaaS purchases

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#678]
[**List of potential large SaaS upgrades**](https://docs.google.com/spreadsheets/d/1Kg1KHV3J6sSY7RVPJubLK8gaQ3U0_Tg7gyFxQGtNhWA/edit#gid=0)

## Background information

We have a handful of SaaS that we need to upgrade (for one reason or another):

- Slack
- GitHub
- Trello
- Figma

This issue is about working out that plan with the Finance team. Combining them all here since the large increase in $$ means they need to be considered as a whole.

## User stories

- As [everyone], I want to ensure TTS is using SaaS that is fully compliant.
- As someone who manages SaaS for TTS, I want to minimize the amount of effort required to do so.

## Acceptance criteria

- Presented potential large SaaS purchases to Finance and GSA IT for feedback/prioritization

## Follow-ups

- [ ] We have the following identified for each SaaS:
   - Whether we will do the upgrade
   - Funding source
   - When we will do the upgrade (if applicable)
   - Cybersecurity benefits/risks (around upgrading or not) documented
- [ ] The relevant folks in GSA IT for each have been notified

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
- [Notes doc](https://docs.google.com/document/d/1cXeHkcOrteAs3HFLU6DDFc3IqYdqgqHAjkJ72YXryfg/edit#)
- [Spreadsheet](https://docs.google.com/spreadsheets/d/1Kg1KHV3J6sSY7RVPJubLK8gaQ3U0_Tg7gyFxQGtNhWA/edit#gid=0)

**Comment by its-a-lisa-at-work** [comment]
Not clear to me if "whether we do the upgrade" means "not going to do the upgrade so we're going to transition off" or means "not going to do the upgrade so we're going to still use it as is"

**Comment by its-a-lisa-at-work** [comment]
@afeld nudge on the acceptance criteria

**Comment by afeld** [comment]
> Not clear to me if "whether we do the upgrade" means "not going to do the upgrade so we're going to transition off" or means "not going to do the upgrade so we're going to still use it as is"

That will vary. Would create new issues around "figure out what to do about X SaaS" if that's the case.

**Comment by its-a-lisa-at-work** [comment]
What will go into the decision if we're going to do the upgrade?

**Comment by afeld** [comment]
Off the top of my head:

- Budget available
- How hard it would be to acquire
- How strongly GSA IT / we feel about upgrading each, for security/compliance/administration purposes

**Comment by afeld** [comment]
Going to wait until the end of the Fiscal Year.

**Comment by its-a-lisa-at-work** [comment]
Mind if we keep this in the Backlog? I think things that are already Sprint Planned for shouldn't go back into Icebox so they stay as something that gets picked up as soon as possible.

**Comment by afeld** [comment]
The BizOps team is busy with end-of-fiscal-year stuff; we'll hold on this until October.

**Comment by melanienleopold** [comment]
In regards to Trello, GSA IT has an Enterprise account. We could get access to license, but we would have to transfer money through an agreement and pay for them. For context, business class is $9.99 per month and enterprise is $17.50 per month.

**Comment by afeld** [comment]
Yep yep, got [the estimate](https://docs.google.com/spreadsheets/d/1Kg1KHV3J6sSY7RVPJubLK8gaQ3U0_Tg7gyFxQGtNhWA/edit#gid=0&range=F6) from GSA IT.

**Comment by afeld** [comment]
From Amar Singh:

> We are fast approaching following 2 decision points for TTS Slack migration:
>
> 1. Need to notify the contracting officer on or before 11/1/2020, that we will not exercise the next option year for TTS Slack with Slack Plus plan.
> 2. Start the acquisition process for Enterprise license to upgrade in January 2021. (Slack team is available to complete the migration on 01/09/2021 from 12pm-10pm ET).

Therefore, expediting this.

**Comment by afeld** [comment]
`large TTS SaaS purchases` email sent. Waiting to hear from Finance.

**Comment by afeld** [comment]
Closing in favor of the more specific https://github.com/18F/tts-tech-portfolio/issues/982.
