### ISSUE TITLE
P-Card handoff

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#680]
## Background information

A part of [storm-draining](https://github.com/18F/tts-tech-portfolio/issues/664)

## Acceptance criteria

- We don't have a senior Engineer handling P-card responsibilities for SaaS

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by melanienleopold** [comment]
Closing in favor of #856.
