### ISSUE TITLE
Authorizing Official responsibilities clarity

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#683]
## Background information

During our [storm-draining](https://github.com/18F/tts-tech-portfolio/issues/664) activity, the number of hours for Authorizing Official seemed lower considering the number of systems TTS is responsible for so need to get better clarity what the AO responsibilities are from GSA IT Security

## Acceptance criteria

- The responsibilities of the Authorizing Official are clearly documented

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
[Official source](https://www.gsa.gov/cdnstatic/ITSecurity21001L.pdf#page=18)
