### ISSUE TITLE
Fix navigation issues on NSF-SBIR created when upgrading to uswds-jekyll 5.0

### ISSUE THREAD

**Issue by hoaiandang** [18F/tts-tech-portfolio#684]
## Background information
https://github.com/18F/nsf-sbir/pull/1849

## Acceptance criteria

- navigation works as it should

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
This is a repository we should have handed off long ago (https://github.com/18F/tts-tech-portfolio/issues/163), so don't worry about it.
