### ISSUE TITLE
Allow non- @gsa.gov users to GSA GitHub teams

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#69]
As a GSA GH org member, I want to be able to add partners with non gsa.gov email addresses to GH teams so that I can easily control access to multiple repositories and disable access quickly and without human error.

GSA GitHub has a policy that they will only allow gsa.gov users to the GSA org, which prevents us from adding non gsa.gov users to our teams. Any time we need to add a partner, like OMB or the many other agency customers we work with, we need to add each user individually to multiple repos. When a user no longer requires access, it becomes a hunting game to track down each repository they were added to and manually remove that user.

**Comment by gbinal** [comment]
Agreed.   That seems like a problem.   Is that policy in the below repo or somewhere else?

https://github.com/gsa/github-administration

**Comment by afeld** [comment]
Funny, since [we decided the opposite](https://handbook.18f.gov/github/#working-with-outside-collaborators). They are separate policies for separate GitHub orgs, but probably makes sense for us to have consensus at some point.

**Comment by adborden** [comment]
On Thu, 2019-08-08 at 09:18 -0700, Gray Brooks <notifications@github.com> wrote:
> Agreed.   That seems like a problem.   Is that policy in the below repo or somewhere else?
> 
> https://github.com/gsa/github-administration

I don't see it explicitly listed, but it looks like an implicit
assumption
https://github.com/GSA/GitHub-Administration#creating-a-github-account

In the past, I've made requests to gsa-github.support@gsa.gov and
they've told me users must have an @gsa.gov email.

Should I re-open this ticket in that repo?


--
Aaron D Borden
Human and hacker

**Comment by afeld** [comment]
Not sure if they would prefer a GitHub issue or email, but sure.

**Comment by afeld** [comment]
Any idea if they are open to adding them as [Outside Collaborators](https://help.github.com/en/articles/adding-outside-collaborators-to-repositories-in-your-organization)?

**Comment by adborden** [comment]
On Thu, 2019-09-26 at 11:40 -0700, Aidan Feldman <notifications@github.com> wrote:
> Any idea if they are open to adding them as [Outside Collaborators](https://help.github.com/en/articles/adding-outside-collaborators-to-repositories-in-your-organization)?

Yes, that is the current guidance. Anyone without a @gsa.gov email is
added manually to repositories on a per-repo basis.

--
Aaron D Borden
Human and hacker

**Comment by afeld** [comment]
@adborden Do you still want to pursue this? I haven't heard any other teams ask for it, so mind if we a) move this issue to a data.gov repository, or b) close this and instead focus on https://github.com/GSA/datagov-deploy/issues/1079?

**Comment by adborden** [comment]
👍 I am okay to close this. We will likely pursue GSA/datagov-deploy#1079 as our paper cuts with the GSA org keep adding up.
