### ISSUE TITLE
determine hosting choice(s) for AI Portfolio content

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#696]
## Background information

The AI Portfolio is trying to launch a couple of things:

Thing | Visibility | Target delivery date
--- | --- | ---
Use Case Library | Fed-only | September or earlier
Body of Knowledge | public | mid-October

Need to help them figure out what platforms/sites those will be hosted on.

## User stories

- As someone in the AI Portfolio, I want to know the plan to launch my content so that I can get it out into the world.

## Acceptance criteria

We know where the following will be hosted:

- [ ] Use Case Library
- [ ] Body of Knowledge

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Created a [comparison spreadsheet](https://docs.google.com/spreadsheets/d/1cNTD08_vnDlSSs4YdefHeMAthIoLfLESfyd90wZaZX4/edit#gid=0).

**Comment by its-a-lisa-at-work** [comment]
👎  rationale:
Since this is `weeks` I suggest creating smaller issues to go along with it. Also, if there is any other background information, that would be helpful. Should this card have a Due Date to go along with the first target delivery date?

**Comment by afeld** [comment]
I think I've provided all the information I can on this; seems to be in the Digital Council's hands.
