### ISSUE TITLE
write up state of marketing tools

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#700]
https://docs.google.com/document/d/1mlcOb_4B2IHtx3tNx3AeCFSCT7R0az4z8_eXC4rJMZQ/edit#heading=h.5pnetb1rmai3

## Background information

A bunch has gone a bunch of different directions in the past couple months, and [the group retro](https://docs.google.com/document/d/1qgiR0kqlbg6KkIR_RrbymjmkhJ2sHEQuBMWSpdvTcUg/edit#) confirmed there's a lot of uncertainty. We need to take a step back, assess the state of things, and lay out the paths forward. Thinking this could take the form of a flowchart and/or a doc.

## User stories

- As a stakeholder in the purchasing/use of marketing tool(s) at TTS, I want to understand the obstacles to getting the tools I need to be productive.

## Acceptance criteria

- An artifact (doc, flowchart, whatever) that lays out the current state and potential paths, distributed to the stakeholders

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Used an existing meeting to get started on it.

**Comment by its-a-lisa-at-work** [comment]
Is the thought that this will be just for the marketing tool; or could the flowchart and other information be useful for updating the handbook page on buying software that is over 10k?

**Comment by afeld** [comment]
No, it's specific to this tool / set of tools.

**Comment by afeld** [comment]
Draft complete. Waiting on some open questions and reviews in the doc.

**Comment by afeld** [comment]
Sent!
