### ISSUE TITLE
Outreach monthly updates Due Date - 8/14/20

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#703]
## Background information

Had bi-weekly meeting with #Outreach today; they asked if we had any updates for the monthly update; told them we'd let them know by 8/14/20 if we did or didn't

@18F/tts-tech-portfolio if you have any ideas, please let me know! I am thinking ... 
- SaaS Authorization updates
- The instructions for getting pinged to update slack
- Announcement of the joint #wg-acquisition & #g-security-compliance guild on Section 889 coming up

Those are off the top of my head..

**Comment by afeld** [comment]
Those all sound good! Nothing else comes immediately to mind.

**Comment by its-a-lisa-at-work** [comment]
Submitted! Switched out the Section 889 update with the interactive GEAR update
