### ISSUE TITLE
August performance review for Alyssa - due 8/21

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#704]
## Background information

Alyssa has put together two different products to support this activity; a [spreadsheet](https://docs.google.com/spreadsheets/d/1GI6bBGb2ZBzZ_-4BEOW0I6om81Xl-oDfFifyaOVfLqM/edit#gid=524817967) and a [form](https://docs.google.com/forms/d/1H9o3sZVhytIqxyKeNVbslirFaj78seQ9zIKxRKlxBhk/edit); she has no strong preference of the `how` it is done, just that it gets done and she is able to get the feedback. 

## User stories

As someone in the TTS Tech Portfolio who would like written feedback on my performance on a periodic basis I would like my supervisor to provide me a quantitative rating on a bi-monthly basis so that I am getting constant feedback, know where I measure, I have time to course correct and when I know I have a bad streak, how much it will affect my yearly rating overall and I can make better decisions for myself and my performance at a personal level. 

## Acceptance criteria

- A quantitate review has been provided to Alyssa for the period of 06/20-7/20
---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@afeld BTW, the task is groomed; and I started to provide some of myself assestment into the [spreadsheet](https://docs.google.com/spreadsheets/d/1Jk99cPIiQV8sfoGLbgHpC_kRMvRe0ndBrM5AgLzi760/edit?usp=drive_web&ouid=101998575189840770976) from the [form](https://docs.google.com/forms/d/1H9o3sZVhytIqxyKeNVbslirFaj78seQ9zIKxRKlxBhk/edit?usp=drive_web).

**Comment by afeld** [comment]
Nice form! Submitted.
