### ISSUE TITLE
remove Sell from cloud.gov ZenDesk

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#705]
## Background information

[They are no longer using it.](https://gsa-tts.slack.com/archives/G012VQWSVNU/p1597170313016400?thread_ts=1597169625.016200&cid=G012VQWSVNU) cc https://github.com/18F/tts-tech-portfolio-private/issues/968

## User stories

- As someone responsible for SaaS compliance, I want to ensure we're only using authorized (in this case FedRAMP'd) products.

## Acceptance criteria

- We are no longer have ZenDesk Sell enabled / subscribed to

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
https://support.zendesk.com/hc/en-us/articles/360051357554-How-do-I-cancel-my-Sell-trial-account-

**Comment by JJediny** [comment]
<img width="752" alt="Screen Shot 2020-12-30 at 4 54 35 PM" src="https://user-images.githubusercontent.com/6350035/103566383-e7bac900-4e8f-11eb-86ff-e036c959775f.png">
atleast 1 `Sell` seat required and we only hold 1. No further action possible

**Comment by afeld** [comment]
Would you mind contacting support to see if it can be cancelled entirely?

**Comment by afeld** [comment]
And did you try following the instructions above?

**Comment by afeld** [comment]
Waiting on support to reassign admin from Eddie to @JJediny.

**Comment by JJediny** [comment]
Confirmed 
<img width="815" alt="Screen Shot 2021-02-03 at 11 13 13 AM" src="https://user-images.githubusercontent.com/6350035/106775257-f02e2d00-6610-11eb-8493-492e7b7024bb.png">
