### ISSUE TITLE
Specifically advertise upcoming positions at Historically Black Colleges, Women Who Code forums, etc

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#715]
https://github.com/18F/tts-tech-portfolio/issues/709

## Background information

[DI&E improvements brainstorming sheet](https://docs.google.com/spreadsheets/d/1ZBMJKUCluue6jCBHA8QGfKX7z8a7CNtE7BUrEYgGsyw/edit#gid=0)

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
We don't have any upcoming positions, and I think the Hiring team is already doing this, so closing.
