### ISSUE TITLE
Create a role within the TTS Tech Portfolio for a DI&E lead

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#716]
https://github.com/18F/tts-tech-portfolio/issues/709

## Background information

[DI&E improvements brainstorming sheet](https://docs.google.com/spreadsheets/d/1ZBMJKUCluue6jCBHA8QGfKX7z8a7CNtE7BUrEYgGsyw/edit#gid=0)

- What is within the Tech Portfolio's power/scope around DE&I?
- What does it make sense for us to take on?

## User stories

- As the DI&E Lead for the Tech Portfolio, I want to understand my responsibilities.

## Acceptance criteria

- The responsibilities (and non-responsibilities) for a DI&E Lead within the Tech Portfolio are documented
- Someone is assigned the role

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
For such a tiny team, I don't think it's necessary to create a role distinct from the Director. We can revisit in the future if there's interest.
