### ISSUE TITLE
New Relic One Platform - Customer Responsibility Matrix (CRM) - System Security Plan (Due 8/30)

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#722]
## Background information
TTS is the sponsor for New Relic, GSA IT security requires that we complete the SSP/ATO for it based on their FEDRAMP tailored package.  

## Related Information or Documentation
https://drive.google.com/drive/folders/1uywNLa_2c4IiMQy9Ro8-iRZZs7jLj8tp

## Implementation
- [ ] Complete supporting artifacts
   - [x] [New Relic FIPS_199_Security_Categorization.docx](https://docs.google.com/document/d/1Kp0DeAY6DxOoG_sdj2hOFhBZYpObBc2FJvkcI9kNFaw/edit#)
   - [x] New Relic CRM SSP v1.docx
      - [x] Complete write up for 11 Customer Responsibility statements
     - [x] Document unmet requirements as POA&M items
      - [x] Complete the [other sections of the SSP](https://docs.google.com/document/d/1smiL7WfNR6ar3k7N3nsGUrOWHykQm4NzPFBMicRwfLE/edit)
   - [ ] System Diagram
   - [x] New Relic Digital Identity Acceptance Statement.docx

## Acceptance Criteria
- [ ] Completed SSP is submitted for acceptance
- [ ] POA&Ms are agreed to

**Comment by afeld** [comment]
We're going to fill this out, knowing that there will be POA&M items around SSO: https://github.com/18F/newrelic-terraform/issues/9

**Comment by its-a-lisa-at-work** [comment]
This is completed at this point; have a couple of questions for @JJediny; @afeld moving to waiting/feedback to get a secondary review before we send to the ISSO to say that we completed it

**Comment by its-a-lisa-at-work** [comment]
Argh, just remembered that we have to create a system diagram for how we use the application; making that an implementation step and I'll move it back to In Progress to do

**Comment by its-a-lisa-at-work** [comment]
Sent zip file with documents to iSSO today; considering done until we hear back with any updates or corrections need to make

**Comment by its-a-lisa-at-work** [comment]
Will still need a diagram of the GSA instance. Can be pretty simple - just showing outbound to the internet, and any integrations (SSO/SAML etc). Make sure to indicate ports and if path is encrypted.

**Comment by its-a-lisa-at-work** [comment]
Created a [system diagram](https://www.google.com/url?q=https://docs.google.com/drawings/d/17aTP34x4w-D72DEQ6lJsSEW8Sg23ewY7ydd0wqtTkQw/edit&sa=D&source=hangouts&ust=1599247433311000&usg=AFQjCNHNRttAOAlwJTVIu4OdN_f0k5qRjQ) and this is closed until ISE wants additional information; but in that case we can open a new card
