### ISSUE TITLE
DevSecOps through change Panel - Due Date 8/20

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#725]
## Background information

Will be on a panel
- [x] Gather [Talking Points](https://docs.google.com/document/d/13DNMAuhY67b_bzwJVhYH_jL4FgpZlW_xatL4lCVrSW0/edit)
- [ ] Intro sync
- [ ] Participate in panel

**Comment by afeld** [comment]
Waiting to hear back on next steps.

**Comment by afeld** [comment]
We decided to pass on this, given the tight timeframe.
