### ISSUE TITLE
eGov Innovation Budget Submission - due 8/14

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#726]
## Background information

> GSA IT’s Capital Planning and Investment Control Team is preparing the GSA IT Budget Submission for BY2022, and we are reaching out to you for your input on details for the eGov Innovation investment.

See email `REQUEST: eGov Innovation BY2022 Budget Submission (August 14)`.

## User stories

- As someone planning future budget for eGOV, I want to understand the breakdown of previous spend.

## Acceptance criteria

- [Cloud managed services sheet](https://docs.google.com/spreadsheets/d/1z3QlYi6k150Ds70EpYHmQ29ZeYaFYOBZVRCJWsgCrRg/edit#gid=1962278921) is filled in

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
BTW, I think this makes sense as a `Task` so I 👍 for `groom accepted`

**Comment by its-a-lisa-at-work** [comment]
should probably put the `expedited` label as well

**Comment by afeld** [comment]
Clarified some things with Karen Trebon. Since she has better access to budget/contract data than I do, she's going to finish it up.
