### ISSUE TITLE
Offboard Hoaian

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#729]
Assignee: The tasks below are organized by the role needed to complete them. If you canʼt complete
any of the items on your checklist personally, you are responsible for ensuring that an appropriate person
does it.

For compliance tracking purposes we need to show when offboarding actions happened; many need to
occur in a 24-hour window. As you do this work, comment on this GitHub issue as you complete each
task. (PS-4: Personnel termination)

Departing Person
- [ ] Initiate the process via the Leaving TTS Handbook page

Assignee
- [ ] Remove from IaaS
  - [ ] AWS
  - [ ] GCP
  - [ ] Azure 
- [x] [Remove them to the @tech-portfolio user group in Slack.](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group)
- [ ] Remove them to the recurring TTS Tech Portfolio meetings that are relevant for them in [the team calendar](https://calendar.google.com/calendar?cid=Z3NhLmdvdl82aDI5YnF1ZGx0NGVoZTVzOWswOGlmdGZxMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t).
- [x] Remove them to the [@18F/tts-tech-portfolio](https://github.com/orgs/18F/teams/tts-tech-portfolio) team on GitHub.
- Remove from Google Groups
  - [x] [TTS Software](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-software/add)
  - [x] [TTS Technology Portfolio](https://groups.google.com/a/gsa.gov/forum/#!managemembers/devops/add)
  - [x] [TTS Vulnerability Reports](https://groups.google.com/a/gsa.gov/forum/#!managemembers/tts-vulnerability-reports/add)

**Comment by JJediny** [comment]
related https://github.com/18F/tts-tech-portfolio/issues/491

**Comment by its-a-lisa-at-work** [comment]
Changed the checklist to a more relevant checklist; checked off items that are done and updated the onboarding checklist as a related task
