### ISSUE TITLE
Change AWS sandbox usage into a cloud.gov onboarding (vs raw AWS)

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#732]
This issue is to track the feasibility of converting our current sandbox access process into a cloud.gov onboarding and dedicated `org` for billing within cloud.gov for all TTS users.

## Acceptance
- [ ] Plan of Action is developed to document the steps, pros/cons for using cloud.gov instead of raw AWS account access for leadership decisionmaking

**Comment by afeld** [comment]
We already direct folks to personal cloud.gov sandboxes in https://before-you-ship.18f.gov/infrastructure/sandbox/; the AWS sandbox is for people that are needing to work with AWS more directly. Are you thinking something different than that?

**Comment by afeld** [comment]
This will be easier via the new consolidated IAM users (https://github.com/18F/aws-admin/issues/110), and not sure it's worth the effort (due to diversity and low frequency of requests), so closing.
