### ISSUE TITLE
Update the TTS System's Inventory list with updated contacts

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#737]
## Background
The tech portfolio needs a well established and approved list of comms channels to reach out to TTS teams

## Acceptance 
- [x] Comms channels are revetted for each TTS system - https://docs.google.com/spreadsheets/d/1zHWUPcTnsD47enyGnq_buwAk98vfbGAwdzNJ381_5JA/edit#gid=2090999198

**Comment by its-a-lisa-at-work** [comment]
@JJediny thoughts of merging this as a User Story for https://github.com/18F/tts-tech-portfolio/issues/535 and closing this card?

**Comment by its-a-lisa-at-work** [comment]
Sorry, accidentally closed

**Comment by its-a-lisa-at-work** [comment]
@JJediny mind if we have a more clear and concise title for this?

Suggest something like "Update the TTS System's Inventory list with updated contacts"

**Comment by its-a-lisa-at-work** [comment]
@JJediny I'm moving this back to Backlog so we can decide who should be assigned today at the Sprint Planning ceremony

**Comment by afeld** [comment]
This is about re-updating the list.

**Comment by JJediny** [comment]
Closing this issue as we have updated the contact sheet but are migrating management of this information into smartsheet

**Comment by its-a-lisa-at-work** [comment]
@JJediny I don't think this information is going to be transitioned to SmartSheet; opening again until that is clear

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/626

**Comment by afeld** [comment]
Considering this done because the information has been updated; will figure out what information should live where as part of https://github.com/18F/tts-tech-portfolio/issues/626.
