### ISSUE TITLE
go through DevSecOps offerings in CircleCI

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#74]
Let's see if there's anything in here we should recommend/leverage by default.

https://circleci.com/integrations/devsecops/

**Comment by JJediny** [comment]
I took a look through the GRACE repos and SSP this week.

Personal recommendation: we should try to pilot/test the GRACE/devsecops AWS management components for our Sandbox accounts; in conjunction with our related work on better AWS user management #65 #70

**Comment by JJediny** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/202
