### ISSUE TITLE
Documented way to handle ATO expirations

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#743]
## Background information

Follow up from: https://github.com/18F/tts-tech-portfolio/issues/658

https://docs.google.com/document/d/1NC736hj2JEUSorC-JnjUeCFj9b9WLvbibRRIlZYuIG0/edit?disco=AAAAJ9pailY

## Acceptance criteria

- [ ] It is clear who, what, where and when ATO expirations are handled

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by JJediny** [comment]
@rpalmer-gsa is working on a schedule in trello with archer eventually retaining this information, tracking but no action being taken by team

**Comment by afeld** [comment]
Security manages these, so not something we need to develop a process for.
