### ISSUE TITLE
Documented way to handle ATO renewals - Due Date 10/1

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#744]
## Background information

Follow up from: https://github.com/18F/tts-tech-portfolio/issues/658

https://docs.google.com/document/d/1NC736hj2JEUSorC-JnjUeCFj9b9WLvbibRRIlZYuIG0/edit?disco=AAAAJ9pailY

## Acceptance criteria

- [ ] It is clear who, what, where and when ATO renewals are handled

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Duplicate of https://github.com/18F/tts-tech-portfolio/issues/653.
