### ISSUE TITLE
Agari Contract

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#758]
## Background information

Login.gov no longer needs Agari. They can use different cheaper tools already owned by TTS. OA has sent a letter to the contractor to terminate the contract for convenience.

## Acceptance criteria

- [x] Agari contract is closed out

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by melanienleopold** [comment]
Waiting on a refund from two incorrect invoices. The modification is prepared and ready once we received the refund.

**Comment by melanienleopold** [comment]
Setting up a meeting with Agari and ACES to figure out the refund.

**Comment by melanienleopold** [comment]
Agari has been responsive, but waiting on the refund. Pushing for a meeting to figure this out.

**Comment by melanienleopold** [comment]
Refund is in the mail. Waiting for finance to confirm receipt of the check and then will close out the contract.

**Comment by melanienleopold** [comment]
Termination for convenience modification sent to the vendor for signature on 1/14.

**Comment by melanienleopold** [comment]
Contract closed.
