### ISSUE TITLE
GCP IAM Policy  Due Date 9/4

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#759]
## Background information

Updates to Cloud IAM policies to clearly Identify deleted accounts
Hello Google Cloud IAM Customer,

We would like to inform you about the introduction of several updates to the IAM Policy Syntax that will make it easier to manage IAM policies that reference deleted accounts.

These changes will start propagating through the system starting September 14, 2020, and will take several weeks to be fully effective, finishing in early October.

After we make these changes, you will be able to clearly identify deleted accounts and you will be able to specify that a grant should refer to an active account on the Google Cloud Platform (GCP) IAM policies.

What do I need to know?
With the current behavior, deleted accounts remain visible on IAM policies for up to 30 days after deletion in case you decide to undelete them.

Consequently, when a user, group, or service account was deleted, and the email address was re-used on a new account, it was impossible to tell whether

## Acceptance criteria

- [ ] determine if this affects anything existing
- [ ] determine next steps to resolve and/or safely ignore

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
We don't think there's any action here.
