### ISSUE TITLE
Update the Before-You-Ship to a "Before-You-XYZ" series

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#769]
## Background information

I think we should explore of updating the Before You Ship guide to support the other ATO pathways besides Custom Developed software

## Implementation Steps

- [ ] Include the information from 'SaaS ATO Conversation Follow UP'

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
cc https://github.com/18F/before-you-ship/issues/305

**Comment by afeld** [comment]
Closing as stale.
