### ISSUE TITLE
set up remote backend for GitHub configuration in Terraform

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#778]
## Background information

Right now, I hold the up-to-date state file for the Terraform code that configures our GitHub repositories. I want to not be a bottleneck for others, and I want it to not be an annoying recovery if my computer dies.

## Acceptance criteria

- Anyone with credentials is able to `apply` changes to [the `terraform` module in this repository](https://github.com/18F/tts-tech-portfolio/tree/master/terraform)

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@amitfreeman-gov can you say more about what this is `waiting/feedback` on?

**Comment by amitfreeman-gov** [comment]
This may be a general process question on how we do things.  In previous teams, issues would need to be accepted as per the acceptance criteria by someone other than the author - at this stage the change either gets accepted as completed or gets sent back because a verifier was unable to accept it.

**Comment by its-a-lisa-at-work** [comment]
Paired with @amitfreeman-gov and validated that it worked :)
