### ISSUE TITLE
merge TTS subdomains list into canonical GSA one

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#784]
## Background information

Just learned about GSA's [All Websites Spreadsheet](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit#gid=2013137748), which seems to be maintained by OSC and is used for various compliance things like [checking for DAP](https://github.com/18F/tts-tech-portfolio/issues/753). Rather than continue to maintain [our own](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1884617968), let's make sure that data is reflected in the GSA one and delete the sheet so there is one source of truth.

[Digital Council Trello card](https://trello.com/c/MeqzAFlH/40-have-a-canonical-list-of-tts-subdomains)

## User stories

- As someone looking for information about TTS subdomains, I want a canonical place to look.

## Implementation steps

- [x] Document the use cases of what we end up referencing that information/data for (through spreadsheets or manually)
   - Mapping to FISMA systems / portfolios / programs
   - Status, for alerting/scanning purposes
   - Finding email address to forward alerts to
   - TTS ownership (will it be handed off, etc.)
- [ ] Create follow-up issue to sync the New Relic list

## Acceptance criteria

- There is only one sheet that contains information about TTS subdomains

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Just learned that SecOps maintains a list in Netsparker for scanning. @jhoyt22 is on board with having a single source of truth.

**Comment by its-a-lisa-at-work** [comment]
Have made progress; need Feedback
- [Systems to review](https://app.smartsheet.com/reports/98qQ5RV6MMVr5MJhWcW7JM8JHPG6m3557wVCHFj1?view=grid)
- [Systems to update](https://app.smartsheet.com/reports/6M2xgQQhJcqccwxJvXMHfFmWmHwqVGCFrgxjXpw1?view=grid)
- [Systems to transfer ownership](https://app.smartsheet.com/reports/gRMHFvxgwCHfxRHCmFP85gphC7QCp2rHFPch55W1?view=grid)
- [Systems - validated](https://app.smartsheet.com/reports/P9pM3HvX4WjhXV53wj8VqG9J2335x8cHMJJj7hx1?view=grid)

For a complete working list, see below

- [Systems - all](https://app.smartsheet.com/sheets/mv5F78qh76F3fC6c3HMjmjPQccXW3F9Vq7gfqR51?view=grid&filterId=6661252912048004)

**Comment by its-a-lisa-at-work** [comment]
Waiting to get access to the GSA Website list so Ic an update it.

Made progress reviewing some `System Status` and updating systems that on `Federalist`. 

Based on the review from the Federalist List, there seems to be a collection of systems that weren't on either GSA or TTS list. Will probably need a process and procedure in place going forward so that the systems get added to the lists appropriately.

**Comment by its-a-lisa-at-work** [comment]
Met with Rachel; provided her our list; she will let us know when she's incorporated them all and let us know when they're in the sheet and we can deprecate ours.

**Comment by afeld** [comment]
Finally! It's done!
