### ISSUE TITLE
migrate desktop software management to GSA IT

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#788]
## Background information

Follow up from https://github.com/18F/tts-tech-portfolio/issues/444 

## User stories

Implementation Steps: 

- [x] Confirm [the Software License Management group is still not managing SaaS licenses](https://github.com/18F/tts-tech-portfolio/issues/444#issuecomment-680257319)
- [ ] Confirm they will handle upgrading of packages
- [x] Confirm this will carry over to DIGIT
- [x] Pick a candidate to get managed by them
- [ ] Figure out how to help them [maintain "a continual agency-wide inventory of software licenses"](https://insite.gsa.gov/directives-library/software-license-management-21082-cio#) for software purchased in TTS — may be its own issue
- [x] Share docs with digit_it_asset_mgmt_sam@gsa.gov
- [x] Find purchase records
   - [x] Sketch
   - [x] Omnigraffle
   - [x] Sublime Text
- [x] Switch Sketch License Manager email
- [x] Get software added to software request form in ServiceNow
- [x] Update instructions

## Acceptance criteria

- [x] GSA IT is handling all desktop software licensing

**Comment by afeld** [comment]
[Nessus got brought up as something that might make sense to hand off.](https://gsa-tts.slack.com/archives/C039MHHF8/p1610642172003700?thread_ts=1610641796.002200&cid=C039MHHF8)

**Comment by afeld** [comment]
Desktop software licenses the Tech Portfolio manages:

- [Sketch](https://handbook.tts.gsa.gov/sketch/#for-admins)
- [Sublime Text](https://docs.google.com/document/d/1Oy-dh_s2T9KgOYLWs2tu4ZBe9nfIGj7PZWDOX3dQaLg/edit)
- [Omnigraffle](https://docs.google.com/document/d/1XhOxKqXmrYutFuHint_JizyGrBGBvcnn-Z_pjhzrsy8/edit)

**Comment by afeld** [comment]
Emailed the Software License Management group to ask what this would take.

**Comment by afeld** [comment]
Conversation with Software License Management group went very well. ([Notes.](https://docs.google.com/document/d/1BDpKZjot0PugzC40LLIvJkfHfjuGxQtsFe55poLGqUk/edit)) Waiting to hear back from them on next steps.
