### ISSUE TITLE
As a member of the Tech Portfolio, I want a shared understanding of our internal principles and processes

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#80]
Given our team will be growing, we should come together and create some "how we operate" documentation. Running list of things I will propose including:

- We work in the open, with rare exceptions
- We follow the Amazon model of [reversible decisions](https://fs.blog/2018/04/reversible-irreversible-decisions/)
- We follow a two-week sprint model, and keep work prioritized in [our board](https://github.com/orgs/18F/projects/11?fullscreen=true). New Backlog / In Progress items should only be injected outside of that prioritization if they a) can be done in under an hour, and (or?) b) unblock someone.
- Issues in the board should be split to be `size: weeks`, and ideally `size: days`
- We try to minimize [toil](https://landing.google.com/sre/sre-book/chapters/eliminating-toil/) and having to be reactionary for TTS and especially ourselves
- We optimize for team member happiness and productivity
- All meetings have a shared notes doc (if they aren't over Slack), and have clear action items following

Probably makes sense to put this in [our Handbook page](https://handbook.18f.gov/tech-portfolio/).

**Comment by JJediny** [comment]
We maintain at least a 1 FTE backup for coverage for any discreet effort, meaning that for any meeting/issue/effort there is at least 1 backup listening in (but not expected to participate fully - maybe help in note-taking and identifying any open questions). 

There is rarely a need for a co-lead, this backup role is strictly to substitute any lead's role in case of backfill in the event of OOO or another higher priority task.

**Comment by afeld** [comment]
Written up in [notes from Oct 2019 All-Hands](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#heading=h.m84egu41cfkv).
