### ISSUE TITLE
Update documents and p-card package for new p-card holder - due 9/14

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#820]
## Background information

A new purchase card holder is starting on 9/14. They will be taking over a majority of p-card purchases.

## User Stories
As the current p-card holder, I want to make sure documents and guides are up to date so the new person can start as soon as possible and have resources to learn how to do the job.

## Acceptance criteria

- [ ] Purchase card [Google folder](https://github.com/18F/tts-tech-portfolio/issues/820#issue-695956569) is updated and organized.
- [ ] All guidance and tutorials are provided
   -  [x] FITARA
   -  [x] 889 sourcing waiver
   -  [x] tax exempt form
   -  [x] Pegasys (cheatsheet)
   -  [x] Micropurchase sheet walkthrough (scripts, fields, workflow)

---

**Comment by melanienleopold** [comment]
Ready for review: [P-card Process](https://docs.google.com/document/d/1LxkTsQPA4v4ZpJNpJcnSBX07WVxQQwfVtXKx236EfEU/edit#). I will be adding the 889 and tax exemption information to this document.

**Comment by its-a-lisa-at-work** [comment]
@melanienleopold is this related to what we mentioned at the Retro, or is that a different issue that we should make a card for?
