### ISSUE TITLE
review updated Federalist Site Review guide+template - due 10/19

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#833]
## Background information

Email thread `Fwd: Federalist Site Review Guide and Template`.

- [Federalist Site Review Guide](https://docs.google.com/document/d/11lUbDP86iIEP5F8_San6qT8814bt0OsgAv1N00PxxNY/edit#heading=h.tyjcwt)
- [Guide Comment Matrix](https://docs.google.com/document/d/1p5E0_MkfzqgkT9GrrtljN_hyq4frUX20/edit)
- [Federalist Site Review Template](https://docs.google.com/document/d/1wNfn8rjTG6ImRZrhaSp6k5RVyvLrSwOS9k7qEwYzL9s/edit)
- [Template Comment Matrix](https://drive.google.com/drive/folders/1jkNrIljsw_dRPDoRl9u26_jBaxuQ1gyv)

## Acceptance criteria

- [x] Feedback provided to ISC on documents.

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Meeting scheduled 10/20.

**Comment by its-a-lisa-at-work** [comment]
Provided feedback and updated Comment Resolution Matrix
@afeld the TL;DR is that it looks really good and is definitely an improvement from where we were originally. It is still not clear to me what the relationship is between the Hosting Agency (GSA) and the Site Owner Agency and who is owning the risk. I also recommend you check out the Comment Resolution Matrix to see which of your comments got accepted and rejected; nothing popped out to me as anything too crazy.
