### ISSUE TITLE
Software Bill of Materials (SBOM) w/ Supply Chain Risk Management (SCRM) Lead

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#839]
## Background information

Based on a prior work position, Alyssa has been involved in Supply Chain Risk Management activities prior to coming to TTS. 

When Alyssa started working with TTS, she joined the SCRM Champs WG as a representative for TTS. 

Alyssa presented to the SCRM Champs WG on Software Bill of Materials as someone who has been attending the quarterly Multistakeholder meetings. 

Since this was just a carryover task and not something that has been established as an initiative, the thought going forward is that someone from TTS OA would attend the meetings instead of Alyssa. 

As a result of the presentation and with the onboarding of the new business development person, Alyssa arranged a meeting for Kelley and Rebecca to meet. 

The meeting with Rebecca and Kelley resulted in a discovery that TTS is listed on a roadmap to take on the SBOM initiative for GSA. 

A meeting between Rebecca and Dom landed on the decision that it would be best if GSA is able to provide funds to help support piloting a tool for TTS to use to produce SBOMS for the TTS custom software. 

We just had the discussion with the Supply Chain Risk Management lead and we’re going to try to go forward with getting Ion Channel on the purchase card before the 30th to support the Software Bill of Materials effort. 

## Acceptance criteria
- [x] Meet with GSA Supply Chain Risk Management to follow up conversation related to Software Bill of Materials and determine how the two offices can support each other

-  [x] Get leadership buy-in
- [x] Prioritize it within @its-a-lisa-at-work workload
- [x] @melanienleopold  will need to check on whether or not she is able to use other GSA offices line items or if that is considered an assisted acquisition
- [ ] Will need to get this through...
  - [ ] IT Standards
  - [ ] IT Security
  - [ ] FITARA

## Acceptance criteria

- [x] TTS is keeping track of Software Bills of Material through a paid tool to track at the portfolio level

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Sounds like there's a specific action item on this; mind if we narrow the issue or break out a smaller one?

**Comment by its-a-lisa-at-work** [comment]
@afeld updated the acceptance criteria to... `Meet with GSA Supply Chain Risk Management to follow up conversation related to Software Bill of Materials and determine how the two offices can support each other` so that it can capture the work related to today's meeting and will create a more concrete one with action items that come from today

**Comment by its-a-lisa-at-work** [comment]
We got the thumbs up for Alyssa to be the SCRM lead from @DsaleGov and we bought the tool with OPC; now we just need to get this tool through the IT Standards process and I'll that to this task https://github.com/18F/tts-tech-portfolio/issues/852
