### ISSUE TITLE
staffing plan

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#85]
Our team has ~2.5 members right now and are able to keep up with incoming requests and _some_ proactive stuff, but we could do more. We have a very long [Icebox](https://github.com/orgs/18F/projects/11?fullscreen=true), and it would be great to churn through those more quickly. This could mean one or more of:

- Having a mechanism to request short-term staff on an ongoing basis - cc #48 
- Getting contract support
- Increasing our number of full-time staff

Dom suggested doing some forecasting as a proposal of what a Low, Medium, and High increase of throughput would look like.

**Comment by afeld** [comment]
Per Dom, we:

- Should assume a per-person cost of ~$200k
- Would need to determine how that cost should be spread out across programs
- Would need to present the case to different parts of TTS to ensure they are supportive of the TTS overhead being raised

**Comment by afeld** [comment]
@its-a-lisa-at-work While this may help in the future when hiring does open up again, I don't see it as being useful until then. Ok with me closing?

**Comment by its-a-lisa-at-work** [comment]
Idk, it seems like a natural activity to do once we have the Strategic Plan, plus @amitfreeman-gov brought up some good points about thinking about what we're missing on the team in the last All Hands we had; plus, I left the meeting with @DsaleGov thinking that this is the type of thing that he was looking for from us...

**Comment by afeld** [comment]
Folding into https://github.com/18F/tts-tech-portfolio/issues/890.
