### ISSUE TITLE
create guidance for reviewing pull requests

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#851]
### Originating question: 
Do we [TTS Tech Portfolio] have internal guidelines on how-we-work related to pull requests?

### Problem statement

Alyssa was under the assumption that they’d wait to get merged until all people listed as reviewers had approved if they were listed. And that doesn’t seem to be the case. 

Not sure if the solution would be a technical or policy related one.

## Acceptance criteria

- [ ] All people within the TTS Tech Portfolio are on the same page with who, when and why a pull request that affects our TTS Tech Portfolio internal team operations or external team duties is merged
- [ ] Documented in the canonical source

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Anything we want to add beyond https://github.com/18F/tts-tech-portfolio/pull/848, or good enough to close this?

**Comment by its-a-lisa-at-work** [comment]
@afeld about your above comment 

> Anything we want to add beyond #848, or good enough to close this?

I think that is a perfect example of something that this issue is talking about -- it got merged w/o all of the listed reviewers having reviewed it -- I literally had no idea that it existed and was related to this and it got merged. I would assume that whatever we write, would hopefully be policy to prevent that from happening...

**Comment by afeld** [comment]
[Conversation about how to review Dependabot pull requests](https://gsa-tts.slack.com/archives/C03EMDS6P/p1609171527217500)

**Comment by its-a-lisa-at-work** [comment]
can we bump this up to happen sooner rather than later? Pull Requests keep getting merged without me having a chance to look at them; this is the latest example: https://github.com/18F/tts-tech-portfolio/pull/1155

**Comment by afeld** [comment]
There are things here that can be improved, but they probably need to be discovered as we go, and may be somewhat specific to each repository (e.g. https://github.com/18F/handbook/issues/2443). Closing as not-quite-actionable.
