### ISSUE TITLE
Respond to cloud.gov

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#853]
## Background information

https://github.com/cloud-gov/product/issues/1174

## Acceptance criteria

-  [x] Have provided cloud.gov with a clarification about statuspage

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Responded in that thread, which I think is sufficient for now.
