### ISSUE TITLE
Retro with Identity PMO - Due Date 10/28

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#855]
## Background information

The Identity PMO is looking to deploy a system. There seemed to be difficulty throughout the process to fulfill their needs from supporting organizations (Tech Portfolio, Acq). In order to make sure things go smoother the next time the Identity PMO or similar office has a request, we should capture lessons learned from this activity. 

## Acceptance criteria

- [x] Retro has been conducted
- [ ] Any action items from retro have been had cards created

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Put a soft due date on this, since it won't be useful much further out.

**Comment by afeld** [comment]
Meeting with them on Thurs; will see where we're at.

**Comment by its-a-lisa-at-work** [comment]
Brought up the [idea](https://gsa-tts.slack.com/archives/C017KUF5DL4/p1602261175051700) of a retro to them today

**Comment by its-a-lisa-at-work** [comment]
Moving to waiting/feedback -- scheduled with @jpyuda, Philip Lam, @melanienleopold & devops@gsa.gov for 10/28/20 at 14:00-14:50 Eastern

**Comment by its-a-lisa-at-work** [comment]
We had the [retro](https://docs.google.com/document/d/1Zhc7mggG0_-W7OmLbsCldHtc3tUExVMmEXTfnNJE29c/edit#) and only action item was to link up with the CTO's office and I scheduled something for next Tuesday
