### ISSUE TITLE
Set up time with Kristina Britt to talk about Consolidated Sync dashboard

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#858]
## Background information

In the latest outreach sync, TTS Tech Portfolio and Outreach briefly talked about the consolidated sync dashboard that Alyssa put together. Both sides determined that we should set up a time aside from the regular meeting to go into it more in depth. 

## Acceptance criteria

- [ ] Solutions Outreach have received a demo on our consolidated communication dashboard

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Explained the update spreadsheet to Outreach at our last meeting.
