### ISSUE TITLE
Inventory Simple Email Services (SMTP/POP3) services/solutions

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#86]
Two-tier approach:
- [ ] Create documentation for getting access to AWS Simple Email Service (SES) for using in test/dev work for clients (caveat we need a test domain in the same account with a Route53 DNS record to attach for DMARC/SPF requirements)
- [ ] Document setup/options to support for a production TTS service.

**Comment by afeld** [comment]
What’s the use case that inspired this, out of curiosity? Would love to see
if this is something that could be brokered by cloud.gov.

**Comment by afeld** [comment]
[Sending through a GSA email](https://gsa-tts.slack.com/archives/C03EMDS6P/p1583165919042800?thread_ts=1583156598.033100&cid=C03EMDS6P) is also an option.

**Comment by afeld** [comment]
Not going to worry about this right now; will wait for it to come up as a system-specific need.

**Comment by afeld** [comment]
Previous issue around this: https://github.com/18F/tts-tech-portfolio-private/issues/880
