### ISSUE TITLE
identify obstacles to cloud.gov use across GSA (not just TTS)

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#866]
## Background information

Related to https://github.com/18F/tts-tech-portfolio/issues/827, but focused GSA-wide rather than specific to TTS.

Between FAS Cloud Services, GRACE, and the Content Management Platform (CMP), there are a lot of platforms (and thus systems) in GSA that aren't using cloud.gov but potentially could. This:

- Limits TTS' visibility in GSA
- Means that GSA is spending a lot of money/time on system operations and platforms that could be saved
- Is revenue sitting on the floor for cloud.gov

While this is arguably out of scope for the Tech Portfolio, I think with a small amount of effort (making the connections from cloud.gov to IDT and FAS, at least) we can get things rolling here.

## Acceptance criteria

- (Prioritized?) list of obstacles to various systems in GSA leveraging cloud.gov

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by JJediny** [comment]
Closing as we are not planning to take action on this within the next 6 months
