### ISSUE TITLE
ensure Tech Portfolio-owned sites have the DAP subagency parameter - due 10/1

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#867]
## Background information

- [More info](https://docs.google.com/document/d/1ESeQ_EaGR9RfL6Zs7pII5UFmwE0TuNwMEJDhRTg-gd8/edit)
- [Report](https://docs.google.com/spreadsheets/d/12_9xUr6JKh_rlVjUCxZCAHXNefxO9MEo3oJEZuHatjQ/edit#gid=2013137748)

## Acceptance criteria

Added to:

- [x] Handbook - https://github.com/18F/handbook/pull/2139
- [x] Before You Ship - https://github.com/18F/before-you-ship/pull/485
- [x] chat.18f.gov - https://github.com/18F/chat/pull/17
- [x] JoinTTS - https://github.com/18F/join.tts.gsa.gov/pull/393

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@afeld for reviewing the 18F/join.tts.gsa.gov#393 would that best be done through pairing? Or can you give me the 101 on what I should be looking out for when doing the review of this sort?

**Comment by afeld** [comment]
Responded in https://github.com/18F/join.tts.gsa.gov/pull/393#issuecomment-712454255.

**Comment by afeld** [comment]
Done!
