### ISSUE TITLE
website modernization plan update - due 10/8

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#873]
## Background information

`ACTION BY OCT 8: Website Modernization Data Call Update` email:

> I know it has been a while since we last connected but wanted to reach out and touch base with you regarding your website cost estimates and modernization/decommission plans that were submitted back in April. The purpose of this touch base is to see if your plans are still on track or if there have been any updates that you can share. In addition to providing a status update for your sites, we also would like to know of any success stories/accomplishments or lessons learned in the process of modernizing and/or decommissioning your sites.
>
> We request that you please add your updated information in [this spreadsheet](https://docs.google.com/spreadsheets/d/1MzcbBfEYZOQdHmnUu4b8-0UGpscgjdKAMEOg4KdzntU/edit#gid=1917713972) by **COB October 8th**. The instructions to use this sheet are included in the 'Instructions' tab. The data that was submitted for your plans earlier this year is also pre-populated (as reference) in the sheet (Columns E and F).
>
> If you have developed your individual action plans using [this template](https://docs.google.com/spreadsheets/d/1wKCfZg50UsHs-NdXDXrB8SEFexGj62Ie09UG7jMZItU/edit#gid=1129003319) (as suggested in the previous email) to document how you plan to make small, incremental improvements to your sites, please share those with me. If not, I highly encourage you to please use this template (or any other that works for you) to track your progress, in alignment with the timeline you developed for modernization for your individual sites and maintain a record so it is easier for you to provide information when we reach out to you for regular updates/progress.

## Acceptance criteria

- Fill out spreadsheet for sites owned by Tech Portfolio

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
@its-a-lisa-at-work Where can I find the Modernization Plans?

**Comment by its-a-lisa-at-work** [comment]
Sorry for the delay

   - [ ]  Complete Website Modernization Plan Worksheet
       - [x] [Handbook](https://docs.google.com/spreadsheets/d/1siEkrfn2Jt19hAO3R-gkMGLg0jckr0ftoVkd8xABKgk/edit#gid=1163132370)
       - [x] [Before You Ship](https://docs.google.com/spreadsheets/d/1hk8TZuX_siUqrUXPZBoHWFUuZVFynaJuTtM23RpiRT8/edit#gid=1163132370)
       - [x] [TTS Jobs ](https://docs.google.com/spreadsheets/d/1St95RHP8fP0xfjU17oQybpmq2tDzM5ozS1StKjmm1bw/edit#gid=1163132370)
   - [ ] Complete Website Cost Estimator
       - [x] [Handbook](https://docs.google.com/spreadsheets/d/17sUt8BNJOow7aITNsCyzL-1IxyDrIBLGSHUFXojb1Bk/edit#gid=1348750722)
       - [x] [Before You Ship](https://docs.google.com/spreadsheets/d/1CcqF46Xa6PpJMbi6DZVUGl95cb4305PMbBvD5NJAlNo/edit#gid=1348750722)
       - [x] [TTS Jobs](https://docs.google.com/spreadsheets/d/1qP895LrtB5x4nDBqZh2RegfzBvJmAXpHyYRGnIxEHO4/edit#gid=1979927954)

**Comment by afeld** [comment]
Done.
