### ISSUE TITLE
clean up recurring Purchase Card purchases

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#892]
## Background information

John's card is temporarily unavailable. Melanie has taken over his monthly purchases for the beginning of the month including Github, Circle CI, and Data Dog. These purchases need to be logged and the SaaS inventory needs to be updated with a column on which purchases are on which card.

## Acceptance criteria

- [x] Melanie's beginning of October purchases are logged and reconciled in Pegasys.
- [x] SaaS inventory includes a column reflecting who makes which pcard purchases.

---

**Comment by melanienleopold** [comment]
Waiting on HubSpot and Github logs. @JJediny to review the SaaS inventory to double check the pcard column is correct.

**Comment by JJediny** [comment]
based on transition to smartsheet closing this issue, until then the micropurchase sheet is the source of truth for pcard holder
