### ISSUE TITLE
Identity Testing Micropurchase

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#894]
## Background information

There is a micropurchase request pending for Testing Services for Software. The Identity PMO wants to test four different products for identity proofing. The Statement of Work is pending legal review.

## Acceptance criteria

- [ ] It is determined whether or not the purchase can be made and the purchase is completed or canceld.

---

**Comment by afeld** [comment]
Waiting on OGC.

**Comment by melanienleopold** [comment]
Closed in favor of [913](https://github.com/18F/tts-tech-portfolio/issues/913)
