### ISSUE TITLE
Statuspage migration to Atlassian account

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#898]
## Acceptance criteria

- [definitive thing]
- [other definitive thing]

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@afeld @JJediny do ya'll know if this is overcome by events? The general title of "Statuspage migration to Atlasssian account" 

If so, we should close this issue

**Comment by afeld** [comment]
Still necessary/useful I think. Unclear how much the Tech Portfolio needs to do, relative to the teams/individuals using StatusPage (cloud.gov and login.gov).

https://support.atlassian.com/statuspage/docs/migrate-to-an-atlassian-account-from-statuspage/

**Comment by JJediny** [comment]
The transition for all my zendesk and statuspage accounts have been automagically rolled under my google oauth account. Closing as I think this has resolved itself - reopen if I missed something
