### ISSUE TITLE
create October Tech Portfolio All Hands agenda - due 10/29

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#904]
## Background information

We have our regular All Hands coming up. Need to figure out what we're going to do with the time.

## Acceptance criteria

- [x] There's a written agenda shared with the team for input

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
[Thread with ideas](https://gsa-tts.slack.com/archives/CNW3GL70S/p1603256948194300)

**Comment by afeld** [comment]
[List of topics for voting](https://docs.google.com/document/d/1hmjgSZXLXcY7pvS-0R-7dkp4zmzykgt9Pv3YRCHgECc/edit)

**Comment by afeld** [comment]
Created!
