### ISSUE TITLE
revise project management workflow - due 5/28

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#907]
## Background information

In this (at least interim - https://github.com/18F/tts-tech-portfolio/issues/868) state of me doing project management for the team, need to find a balance between what is optimal for the team and realistic with the time I can spend on it. Ideas:

- no Epics or Themes - cc https://github.com/18F/tts-tech-portfolio/issues/740
- single name for columns
- ceremony descriptions match meeting names
- remove milestones
- required labels
- what does "groomed" mean
- disambiguate cards vs issues
- only one person besides the author needs to give a thumbs-up on grooming of an issue for it to be `accepted`
- clarify prerequisites to ceremonies

## Acceptance criteria

- [x] [Workflow documentation](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/workflow.md) updated
- [ ] Acknowledgement of full team
- [ ] Set reminder to check in to see how it's working

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
More related to https://github.com/18F/tts-tech-portfolio/issues/766 but I suggest we use other Theme specific (like the [Software Assurance](https://github.com/orgs/18F/projects/24?fullscreen=true)) boards for the `Icebox` instead of a column on this board. 

Think it could work out by doing the ordering/prioritizing from the Theme specific board and when it comes time to Planning, moving groomed cards into the `Backlog`

tagging in @karareinsel because I know they do something similar

**Comment by karareinsel** [comment]
@its-a-lisa-at-work I'm happy talk about our processes.

**Comment by afeld** [comment]
Open to that! Just to say out loud: I created this issue to write down some ideas I didn't want to forget, but not all the changes need to happen, and not all the changes need to happen at once. Title makes this round of intended changes sound more major than I think they will end up being. Like everything, I hope we can optimize the workflow itself for change 😄 

Want to make a separate issue around "make it easier to manage the Icebox"?

**Comment by afeld** [comment]
> The title makes this round of intended changes sound more major than I think they will end up being.

That is to say: this issue is mostly about updating the workflow doc to reflect what we've been doing in practice.

**Comment by afeld** [comment]
Want to get this done for the two folks joining the team in the next couple weeks, so moved it up.
