### ISSUE TITLE
HackerOne Conference Speaking Engagement - Due Date 10/22

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#908]
## Background information

Been asked to fill in for a panelist who had to drop out of the HackerOne Security@ conference. 

## Acceptance criteria

- [x] Speaking Engagement is accepted

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Moving to Waiting/Feedback because submitted form ([events-20-0785)](https://docs.google.com/spreadsheets/d/1HqsdJ-pHZcg4n8vWwfOo8-sxAFfP1LtWxRVBWEbZnMA/edit#gid=0) and now just waiting.

**Comment by its-a-lisa-at-work** [comment]
The request got approved, so I'm good to go to speak.

**Comment by afeld** [comment]
PHEW!
