### ISSUE TITLE
As someone doing development at TTS, I don't want to worry about my development setup

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#91]
I have a proposal in my head...the short version is that "language/package isolation and keeping project setup information up-to-date is hard...use containers for development instead." This would also propose slimming our recommended installations (cc https://github.com/18F/laptop/issues/184). Projects like [CF Local](https://pivotal.io/cf-local) and [`pack`](https://buildpacks.io/docs/) may make this even easier.

This is a placeholder issue to write a longer proposal. _Please don't leave feedback on this issue until that's written._

**Comment by JJediny** [comment]
Closing in favor of broad discussion at https://github.com/18F/laptop/issues/184
