### ISSUE TITLE
Close out SaaS Application Monitoring Tool Call Order 001 - due 11/6

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#914]
## Background information

The SaaS Application Monitoring Tool (New Relic) Call Order 001 Period of Performance ended in April. The call order needs to be closed out. 

## Acceptance criteria

- [x] The contractor commits to not invoicing anything more for the call order. 
- [x] Any remaining funds are deobligated.
- [x] The contract is closed out in ASSIST.

**Comment by afeld** [comment]
Is there a due date for this?

**Comment by melanienleopold** [comment]
Waiting on Finance to finish closing out in ASSIST.
