### ISSUE TITLE
Post Login.gov RFI on Github

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#915]
## Background information

The Office of Acquisition has a Request for Information for Login.gov that they want to be posted on Github in addition to eBuy.

## Acceptance criteria

- [ ] RFI is posted on Github and readable

**Comment by melanienleopold** [comment]
[Link to RFI](https://github.com/18F/office-of-acquisition/pull/2)

**Comment by its-a-lisa-at-work** [comment]
Done w/ my part; un assigning myself for now; feel free to add me back if you have any questions, comments or concerns
