### ISSUE TITLE
clean out New Relic users

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#917]
## Background information

New Relic is switching to user-based pricing; TTS has a lot of users in there that haven't been active in a long while.

This can be done as a one-time manual review; can consider more automated/robust solutions for the future.

## Acceptance criteria

- User list is down to only active users who should still have access

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
See email `Full list of TTS New Relic users attached`.

**Comment by afeld** [comment]
Similar to https://github.com/18F/aws-admin/issues/39 — may make sense to consolidate communications around them.

**Comment by JJediny** [comment]
Blocked / waiting for: https://docs.google.com/spreadsheets/d/1XiDJUrTTZPKKE3_CYmfzizybWsB6yHfDpRz6PEoQKJA/edit#gid=665574795

**Comment by JJediny** [comment]
minus a few none responses to follow up we're close enough to estimate cost - closing until New Relic announces a date for their pricing model change.
