### ISSUE TITLE
IaaS single sign-on solution for TTS staff

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#931]
In order to test out SCIM or Auth2 for IaaS/PaaS/SaaS services mapped to GSA TTS users we need to setup an overall Active Directory Sync with GSA IT.

## Acceptance Criteria
- [ ] Determine with IaaS service to leverage for sync service.
- [ ] Establish a technical AD sync with GSA IT

**Comment by amitfreeman-gov** [comment]
Unclear whether this issue is captured in other open issues.  We need to revisit this one to see if it is still relevant.

**Comment by afeld** [comment]
Merging into https://github.com/18F/aws-admin/issues/48.
