### ISSUE TITLE
Decommission/Rehome 18F/SBIR Github Repo

### ISSUE THREAD

**Issue by amitfreeman-gov** [18F/tts-tech-portfolio#950]
_Add/remove items, as applicable._

- [x] Notify any users of the system, via banner across the site, email, Slack, etc. Ideally, help them find alternatives, make sure they're off in time, etc.
- [ ] Export any relevant [records](https://handbook.tts.gsa.gov/records-management/) and store in Google Drive.
- [ ] Clean up infrastructure
  - [ ] If the site was operated on Federalist, contact [federalist-support@gsa.gov](mailto:federalist-support@gsa.gov) to deprovision the [custom domain](https://cloud.gov/docs/management/custom-domains/) for the site
- [ ] [Archive the GitHub repositor(ies)](https://help.github.com/articles/archiving-repositories/). Ask in [#admins-github](https://gsa-tts.slack.com/messages/admins-github) if you need help.
- [ ] Domain changes
  - [ ] Clean up any DNS entries that are no longer needed, from [the DNS repository](https://github.com/18F/dns) or elsewhere.
  - [ ] Update DNS entries to point to new urls or [set up redirect(s)](https://github.com/18F/pages-redirects#domain-redirects).

  - [ ] Remove any external integrations
    - [ ] [Slack](https://handbook.tts.gsa.gov/slack/#integrations)

**Comment by afeld** [comment]
cc https://github.com/18F/nsf-sbir/issues/1913

**Comment by afeld** [comment]
Repository transfer scheduled for 4/15.

**Comment by afeld** [comment]
Transferred! They are working with @apburnes on changes to the Federalist setup, but that's being handled elsewhere.
