### ISSUE TITLE
As a member of the Emergency Backup Group, I need to understand my reponsibilties

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#96]
[Notes from meeting](https://docs.google.com/document/d/1t01CvIpZG-Hrh_ZDkn912fKG1vKLVgaaGoukwQR9X3U/edit)

- [x] Determine who the NAAS backup should be
- [x] Read [TTS page on Continuity site](https://sites.google.com/a/gsa.gov/continuity/home/coming-soon---customized-hsso-pages/ocsit)
- [x] Read [Eagle Horizon prep doc](https://drive.google.com/file/d/16bYUlrsdq6Si5bLXGPzhV70SPc_cVvi9/view)

**Comment by JJediny** [comment]
TTS coop plan has been circulated for comment we will reopen when there is an action based on any feedback
