### ISSUE TITLE
give out new Sketch licenses

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#97]
Blocked by not being able to sign into the License Manager.

- [x] Contact GSA IT Help Desk to [whitelist Sketch emails](https://www.sketch.com/support/licensing-and-sales/license-manager-email-issue/) will help - `REQ0472189`

Who's waiting:

- [ ] [Jeremy Z](https://gsa-tts.slack.com/archives/C0488U4H6/p1568220253004300)
- [x] [Porta](https://gsa-tts.slack.com/archives/C039MHHF8/p1567690297061100)
- [ ] [Robert J](https://gsa-tts.slack.com/archives/C0488U4H6/p1567528436001200)

[Instructions, for once unblocked](https://docs.google.com/document/d/18Htav6TIgasBvvSroI8H_sQXxnvMlra2k9iabBwQYUs/edit#heading=h.lst2f6h7we2f)

**Comment by afeld** [comment]
Unblocked! Sent https://github.com/18F/handbook/pull/1481 to people who requested to get the required info from them.

**Comment by its-a-lisa** [comment]
As an Administrator of Sketch need further directions of what to do after signing into license manager and once the user has provided their device information. 

Problem trying to solve: What are the next steps so that the user can start using sketch once they've provided the information.

**Comment by afeld** [comment]
Does this do it?

https://handbook.18f.gov/sketch/

**Comment by its-a-lisa** [comment]
closing as stale
