### ISSUE TITLE
Better understand DNS at TTS

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#972]
## Implementation Steps
- [ ] Read up 
  - [ ] [TTS IaC](https://18f.gsa.gov/2018/08/15/shared-infrastructure-as-code/?)

## Acceptance Criteria

- [ ] Alyssa feels as though this is done

**Comment by its-a-lisa-at-work** [comment]
https://gsa-tts.slack.com/archives/C039MHHF8/p1604937584256300?thread_ts=1604936259.255300&cid=C039MHHF8

**Comment by afeld** [comment]
https://before-you-ship.18f.gov/infrastructure/domains/

**Comment by its-a-lisa-at-work** [comment]
read through; don't need to understand it more than I currently do
