### ISSUE TITLE
come up with criteria to decommission a site

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#979]
## Background Information

[Trello card](https://trello.com/c/4TBwBLTN/45-decommissioning-criteria)

## Acceptance Criteria

- [ ] Documented criteria for whether a site should be decommissioned or not
- [ ] Security and TTS Leadership have signed off on it

**Comment by afeld** [comment]
Forgot that I was asked to facilitate a conversation around this at the Digital Council meeting. Sounds like we are carrying forward with it, so putting this in Waiting until our next meeting.

**Comment by its-a-lisa-at-work** [comment]
Mentioned in today's standup, Natalie has the next steps so moving from `Blocked/Watching`

**Comment by afeld** [comment]
We decided to hold on formalizing [what's in the notes doc](https://docs.google.com/document/d/1Nt4EBHFVRtEfQ1h1eqkmpZ6nGQkMFYPVkKfMsXFVQLA/edit#bookmark=id.7l2e1ftk6ruq), so closing for now.
