### ISSUE TITLE
Schedule kickoff meeting for Software Concierge

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#990]
## Background information

Melanie has been assigned as the software concierge for the tech portfolio. As part of this assignment, there will be a kickoff meeting to start the process.

## Acceptance criteria

- [ ] Meeting is complete with @its-a-lisa-at-work @josephderosales @CinnyaSm and @afeld 

---

**Comment by afeld** [comment]
Blocked by https://github.com/18F/tts-tech-portfolio/issues/989.

**Comment by melanienleopold** [comment]
Meeting is scheduled for 1/12.
