### ISSUE TITLE
decommission connect.gov

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#995]
_Add/remove items, as applicable._

- [x] Domain changes
  - [x] Clean up any DNS entries that are no longer needed, from [the DNS repository](https://github.com/18F/dns) or elsewhere.
  - [x] [Delete the domain registration from DotGov](https://home.dotgov.gov/management/#how-do-i-delete-my-domain)
  - [x] Update inventories
    - [x] [TTS subdomains](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1884617968)
    - [x] [GSA websites](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit#gid=2013137748)
- [x] Notify other parts of GSA
  - [x] Notify your ISSM

**Comment by afeld** [comment]
@JJediny I left all the checkboxes in there intentionally; can you either check them off or reopen the issue if they aren't done?

**Comment by JJediny** [comment]
Closed https://github.com/18F/dns/pull/496
