### ISSUE TITLE
Ethics Training - due 11/16

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#997]
## Background Information

Annual training, found in [OLU](https://gsaolu.gsa.gov/).

## Acceptance Criteria

- [x] Everyone has the training completed

**Comment by its-a-lisa-at-work** [comment]
Completed my training on Friday; removing myself as assignee

**Comment by afeld** [comment]
Same. Please remove yourself when complete, and last person, please close the issue. Thanks!

**Comment by afeld** [comment]
Everyone confirmed they completed it.
